### ISSUE TITLE
proxy all traffic without matching the domain names in haproxy

### ISSUE THREAD

**Issue by styk-tv** [jcmoraisjr/haproxy-ingress#101]
Problem and solution seems to be provided here https://superuser.com/questions/1209568/proxy-all-traffic-without-matching-the-domain-names-in-haproxy

However not providing -host prevents access (nothing is returned by haproxy, not even default backend) And then providing -host: * is causing a parsing error `error: error converting YAML to JSON: yaml: line 10: did not find expected alphabetic or numeric character` (example below)

```
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: echo
  namespace: default
  annotations:
    ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: *
    http:
      paths:
      - path: /echo
        backend:
          serviceName: http-svc
          servicePort: 8080
```

Could you please confirm definition and if it is currently possible to proxy all traffic without matching domain name?
