### ISSUE TITLE
Prometheus exporter example

### ISSUE THREAD

**Issue by dobesv** [jcmoraisjr/haproxy-ingress#107]
I was able to hook this up to prometheus by adding a sidecar container to the deployment:

```
      - name: prometheus-exporter
        image: quay.io/prometheus/haproxy-exporter:v0.9.0
        args:
          - --haproxy.scrape-uri=http://127.0.0.1:1936/haproxy?stats;csv
        ports:
          - name: prom-metrics
            containerPort: 9101
```

And using CoreOS prometheus operator, a service and servicemonitor:

```

apiVersion: v1
kind: Service
metadata:
  labels:
    app: haproxy-prom-metrics
  name: haproxy-prom-metrics
  namespace: haproxy
spec:
  ports:
  - name: prom-metrics
    port: 9101
    targetPort: prom-metrics
  selector:
    app: haproxy
  sessionAffinity: None
  type: ClusterIP

---

apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: haproxy
  namespace: prometheus
  labels:
    app: haproxy-prom-metrics
spec:
  jobLabel: app
  selector:
    matchLabels:
      app: haproxy-prom-metrics
  namespaceSelector:
    matchNames:
    - haproxy
  endpoints:
  - port: prom-metrics
    interval: 30s
    path: /metrics

```

Maybe this information will help somebody.

**Comment by jcmoraisjr** [comment]
Great, just labeling this as an enhancement in order to properly update the `examples`. Tks!

**Comment by remoe** [comment]
Use this prometheus deployment as a base installation:

https://github.com/coreos/prometheus-operator/tree/master/contrib/kube-prometheus/manifests

Here is a working sample:

Add this to haproxy-ingress manifest:

```yaml
apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  labels:
    run: haproxy-ingress
  name: haproxy-ingress
  namespace: ingress-controller
spec:
  updateStrategy:
    type: RollingUpdate
  selector:
    matchLabels:
      run: haproxy-ingress
  template:
    metadata:
      labels:
        run: haproxy-ingress
    spec:
      hostNetwork: true
...
      serviceAccountName: ingress-controller
      containers:
...
      - name: prometheus-exporter
        image: quay.io/prometheus/haproxy-exporter:v0.9.0
        args:
          - --haproxy.scrape-uri=http://127.0.0.1:1936/haproxy?stats;csv
        ports:
          - name: prom-metrics
            containerPort: 9101              
```

```yaml
apiVersion: v1
kind: Service
metadata:
  labels:
    app: haproxy-prom-metrics
  name: haproxy-prom-metrics
  namespace: ingress-controller
spec:
  ports:
  - name: prom-metrics
    port: 9101
    targetPort: prom-metrics
  selector:
    run: haproxy-ingress
  sessionAffinity: None
  type: ClusterIP
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: haproxy
  namespace: monitoring
  labels:
    app: haproxy-prom-metrics
    k8s-app: haproxy-metrics
spec:
  jobLabel: app
  selector:
    matchLabels:
      app: haproxy-prom-metrics
  namespaceSelector:
    matchNames:
    - ingress-controller
  endpoints:
  - port: prom-metrics
    interval: 30s
    path: /metrics
```

It's important to know that Prometheus manifest match the Service Monitors:

```yaml
apiVersion: monitoring.coreos.com/v1
kind: Prometheus
...
  serviceMonitorSelector:
    matchExpressions:
    - key: k8s-app
      operator: Exists
```
