### ISSUE TITLE
Weight based routing from HTTPRoute

### ISSUE THREAD

**Issue by prasadrajesh** [jcmoraisjr/haproxy-ingress#1110]
**What are you trying to do**
I am trying to use weight based routing on backend (feature of HAProxy) to make sure I can use canary deployment to switch traffic for same hostname/FQDN. 

**What HAProxy Ingress should do or how it should behave differently**
I tested with provided default template in this repo. But the controller can't add custom weight at backend. Even I looked the code https://github.com/jcmoraisjr/haproxy-ingress/blob/master/pkg/converters/gateway/gateway.go seems no logic implemented here. Please correct me if I am wrong.

**Comment by jcmoraisjr** [comment]
Weight based routing is supposed to work with Gateway API:

https://github.com/jcmoraisjr/haproxy-ingress/blob/222a777f6b17be515e0475611743f94ff66bee7c/pkg/converters/gateway/gateway.go#L295-L307

and also with Ingress resources, see the [blue/green example](https://haproxy-ingress.github.io/docs/examples/blue-green/).

Can you update us with a few more detail, like what you tried to do, what was expected and what happened? Maybe you have a bug instead of a feature request.

**Comment by prasadrajesh** [comment]
Hi @jcmoraisjr , I was testing with below httpRoute. 

```
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: coffee
spec:
  parentRefs:
  - name: cafe
  hostnames:
  - "test1.prod.test.net"
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /
    backendRefs:
    - name: example-service
      port: 80
      weight: 90
    - name: example-service1
      port: 80
      weight: 10
 ```
 
 And used template https://github.com/jcmoraisjr/haproxy-ingress/blob/master/rootfs/etc/templates/haproxy/haproxy.tmpl
 
 At the end I am getting as below
```
backend <backend name>
....
server <server1_name> <server1_ip>:8080 weight 128
server <server2_name> <server2_ip>:8080 weight 128
```

So default getting 128. @jcmoraisjr I think you are right this is bug.
