### ISSUE TITLE
retry-on configuration 

### ISSUE THREAD

**Issue by saggiyogesh** [jcmoraisjr/haproxy-ingress#1151]
**What are you trying to do**

Trying to use `retry-on` option with ingress

`retry-on`  is available with haproxy as per below doc link
https://www.haproxy.com/documentation/haproxy-configuration-manual/latest/#retry-on

Any way to configure it with ingresses.

**Comment by jcmoraisjr** [comment]
This seems to be the type of config that can be added via a config snippet, doc [here](https://haproxy-ingress.github.io/docs/configuration/keys/#configuration-snippet). HAProxy has tons of config options, and we choose to add as our config keys just the ones harder to be configured otherwise.

**Comment by saggiyogesh** [comment]
@jcmoraisjr is this correct way to configure 

```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    haproxy-ingress.github.io/balance-algorithm: roundrobin
    haproxy-ingress.github.io/maxconn-server: "500"
    haproxy-ingress.github.io/ssl-redirect: "false"
    haproxy-ingress.github.io/config-backend: |
      retry-on 503 502
      retries 3
     
```
