### ISSUE TITLE
Longest matching path does not match when host name is empty

### ISSUE THREAD

**Issue by pmint93** [jcmoraisjr/haproxy-ingress#1156]
**Description of the problem**

Rules that has longest path but without `host` field are put into default backend map, which has lowest precedence, so it won't match if it overlap with other rules that has `host` field specified

**Expected behavior**

Traffic of `example.com/foo` should goes to `foo-service`
As guided in [kubernetes ingress](https://kubernetes.io/docs/concepts/services-networking/ingress/#multiple-matches): precedence should be given first to the longest matching path

**Steps to reproduce the problem**

1. Create 2 ingresses as bellow:

_To route all traffic with prefix `/foo` to `foo-service`_

```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: foo-ingress
spec:
  ingressClassName: haproxy
  rules:
  - http:
      paths:
      - path: /foo
        pathType: Prefix
        backend:
          service:
            name: foo-service
            port:
              number: 80
```

_To route traffic of `example.com/` to `baz-service`_

```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: baz-ingress
spec:
  ingressClassName: haproxy
  rules:
  - host: example.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: baz-service
            port:
              number: 80
```

2. Go to `http://example.com/foo` to see that request are unexpectedly route into `baz-service`

**Environment information**

HAProxy Ingress version: `v0.14.6`

**Comment by jcmoraisjr** [comment]
This happens because host match has precedence over path overlap, so a path overlap only happens under the same host. This is better described [here](https://kubernetes.io/docs/concepts/services-networking/ingress/#name-based-virtual-hosting):

> For example, the following Ingress routes traffic requested for first.bar.com to service1, second.bar.com to service2, and any traffic whose request host header doesn't match first.bar.com and second.bar.com to service3.

**Comment by pmint93** [comment]
Thanks for pointing it out
However I found a workaround for this use case, this is a note for whoever want to do so.

```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    # 1. Using server-alias-regex to match any domain
    # 2. We're intentionally make the regex so long to make HAProxy Ingress put this rule at the first line of the front map file, so that it has the highest precedence
    # Why ? Since HAProxy Ingress sort regex rule before write into front map file based on rule length https://github.com/jcmoraisjr/haproxy-ingress/blob/master/pkg/haproxy/types/maps.go#L386
    # So if the host-specific rule "<host>/*" is longer than "<any>/foo", the "/foo" rule will not take effect, that's not what we want
    ingress.kubernetes.io/server-alias-regex: ".?.?.?.?.?.?.?.?.?.?.?.?.?.?.?.?.?.?.?.?.?.?.?.?.?"
  name: foo-ingress
spec:
  ingressClassName: haproxy
  rules:
  - host: "*.dummy"
    http:
      paths:
      - path: /foo
        pathType: Prefix
        backend:
          service:
            name: foo-service
            port:
              number: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    ingress.kubernetes.io/path-type: regex
  name: baz-ingress
spec:
  ingressClassName: haproxy
  rules:
  - host: example.com
    http:
      paths:
      - path: /*
        pathType: ImplementationSpecific
        backend:
          service:
            name: baz-service
            port:
              number: 80
```
