### ISSUE TITLE
aws elb integration

### ISSUE THREAD

**Issue by redr0bin** [jcmoraisjr/haproxy-ingress#117]
Hi, 
tried to put haproxy-ingress on amazon behind the elb. All went well, but now I don't understand the further steps, I have 3 nodes/3 ingress pods, how do I expose these to elb ?

Thanks.

**Comment by ausmith** [comment]
@redr0bin depends a little on your implementation, but I will try to mention all the edge cases here. The haproxy-ingress containers will need to first be exposed via host ports. That configuration may look like:

```
          ports:
            - containerPort: 80
              hostPort: 80
              name: http
            - containerPort: 443
              hostPort: 443
              name: https
```

Now that we have the ports exposed for 80 and 443 from the kube node, we need to give the ELB access to those ports via security groups. 

You will next need to determine where you want TLS to terminate. If you wish for it to terminate at the haproxy-ingress containers then I suggest you use proxy protocol v2 from the ELB to the haproxy-ingress containers ([haproxy-ingress docs](https://github.com/jcmoraisjr/haproxy-ingress#use-proxy-protocol) and [ELB docs](https://docs.aws.amazon.com/elasticloadbalancing/latest/classic/enable-proxy-protocol.html)). If you wish for the ELB to terminate TLS then you will need to add your certificate to the ELB. This entire paragraph assumes you are using classic ELBs and not NLBs or ALBs. If either of those are in use then I suggest similar steps but using Target Groups instead of direct ELB instance membership.

Hope this helps!
