### ISSUE TITLE
Ingresses not merging correctly

### ISSUE THREAD

**Issue by lawrencedudley** [jcmoraisjr/haproxy-ingress#119]
Hey,

Firstly - the HAProxy ingress is awesome. Really good. There's a couple of little bits missing, this is one of them. I'm not 100% with Go but may, err, have a go at fixing this.

In short:

We use [Cert Manager](https://github.com/jetstack/cert-manager) with Kubernetes. When a certificate request is created over HTTP, we already have one ingress in existence as follows:

```yaml
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ingress
spec:
  rules:
  - host: domain.name.com
    http:
      paths:
      - backend:
          serviceName: service-name
          servicePort: 80
  tls:
  - hosts:
    - domain.name.com
    secretName: https-domain-name-com
```

The secret won't exist at this stage.

When Cert Manager tries to issue the cert, it creates another ingress:

```yaml
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  labels:
    certmanager.k8s.io/certificate: domain-name-com
    certmanager.k8s.io/domain: domain-name-com
    certmanager.k8s.io/managed: "true"
  name: domain-name-com
spec:
  rules:
  - host: domain.name.com
    http:
      paths:
      - backend:
          serviceName: cm-service-name-http-yraja
          servicePort: 8089
        path: /.well-known/acme-challenge/P3WfK2LwwwYCZqNla2LrZc5ewxihhhWlju91pXWoENs
```

What I expected:

The HAProxy ingress would merge these two ingresses, pointing the  /.well-known/acme-challenge/P3WfK2LwwwYCZqNla2LrZc5ewxihhhWlju91pXWoENs traffic at cm-service-name-http-yraja and all other traffic at service-name.

What I saw:

The second ingress was ignored.

---

I'm not sure if this is down to not explicitly setting a path on the main service? Could be - not sure.
