### ISSUE TITLE
Problem with ssl-redirect="false"

### ISSUE THREAD

**Issue by kmathmann** [jcmoraisjr/haproxy-ingress#120]
If i request my node on port 80 with a host that is not specified in any ingress config i get the result code 302 "Found" with the same location as i requested but instead of http it uses https.

I understood ssl-redirect="false" like it should disable this behavior. But the strange thing is that when i use a host in a ingress that then the behavior is gone for that host.

If i request `http://foo.bar/` or `http://bar.foo/` i get a response from the ingress-default-backend (google_containers defaultbackend).
But when i request `http://example.com` i get the 302 page again.

Did i miss something? I only want to get the defaultbackend's 404 response in that cases too.

I use the canary tag.

### Request
```bash
curl --request GET \
  --url http://SERVER_IP/ \
  --header 'Cache-Control: no-cache' \
  --header 'Host: example.com'
```

### ConfigMap
```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: haproxy-ingress
  namespace: ingress-controller
data:
    dynamic-scaling: "true"
    backend-server-slots-increment: "4"
    ssl-redirect: "false"
```

### Ingress
```yaml
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: app-ingress
  namespace: ingress-controller
  annotations:
    ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: bar.foo
    http:
      paths:
      - path: /app
        backend:
          serviceName: http-svc
          servicePort: 8080
  - host: foo.bar
    http:
      paths:
      - path: /app
        backend:
          serviceName: http-svc
          servicePort: 8080
      - path: /nodejs
        backend:
          serviceName: nodejs
          servicePort: 8080
```

### haproxy-deamonSet
```yaml
apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  labels:
    run: haproxy-ingress
  name: haproxy-ingress
  namespace: ingress-controller
spec:
  ....
  template: 
    ...
    spec:
      ...
      containers:
      - name: haproxy-ingress
        image: quay.io/jcmoraisjr/haproxy-ingress:canary
        args:
        - --default-backend-service=$(POD_NAMESPACE)/ingress-default-backend
        - --reload-strategy=multibinder
        - --configmap=$(POD_NAMESPACE)/haproxy-ingress
        - --sort-backends
  ...
```
