### ISSUE TITLE
balance-algorithm not picked up

### ISSUE THREAD

**Issue by julianvmodesto** [jcmoraisjr/haproxy-ingress#15]
Seems like the balance-algorithm isn't being set w/ v0.2.1 at least.

My ConfigMap:
```
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: kube-system
  name: ingress-haproxy-controller
  labels:
    app: ingress-haproxy-controller
data:
  balance-algorithm: hdr(X-Real-IP)
```

The haproxy.cfg sets the balance-algorithm to round robin.
