### ISSUE TITLE
[Questions]Multiple Haproxy-controller on the same cluster with multiple namespaces

### ISSUE THREAD

**Issue by Zwordi** [jcmoraisjr/haproxy-ingress#159]
Hello ,

I'm doing my first steps with haproxy-ingress.
I think that i'm trying to do something which is not possible with haproxy-ingress.

I have an app let's say demo. It's running under his namespaces demo.
His services are correct and my ingress ressources too, everything it's working and i just make a changes to the roles, clusterroles etc as i didn't make it run under _ingress-controller_ namespace but under _demo_ namespaces.

Now i have a copy of this app let's say staging. It's running under his namespaces staging.
I had to load again some clusterrolesbinding or edit them in order to add my ingress-controller account of my staging namespaces .

```
subjects:
  - kind: ServiceAccount
    name: ingress-controller
    namespace: staging
  - apiGroup: rbac.authorization.k8s.io
    kind: User
    name: ingress-controller
    namespaces: staging
```

Haproxy pods start fine and i see that he his taking his configuration from the demo ingress ressource instead of the staging so all my call for my staging env are not working.

Did I misused the haproxy-ingress or do i miss somethings ?

**Comment by veeshall** [comment]
@Zwordi, I would check the below things

1) Ingress-class in your haproxy pod
```
apiVersion: extensions/v1beta1
kind: Deployment
....
....
        image: quay.io/jcmoraisjr/haproxy-ingress
        args:
        - --default-backend-service=$(POD_NAMESPACE)/ingress-default-backend
        - --default-ssl-certificate=$(POD_NAMESPACE)/tls-secret
        - --configmap=$(POD_NAMESPACE)/haproxy-ingress
        - --ingress-class=ingress-$(POD_NAMESPACE)
```

2) Your Ingress Resource, is it referring to the above ingress-class
```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: xxxxxxx
  annotations:
    kubernetes.io/ingress.class: ingress-staging
```
Also check the ClusterRoleBinding, may be it should be like below
```
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: ingress-controller-staging
```

**Comment by jcmoraisjr** [comment]
3. check rbac config [here](https://github.com/jcmoraisjr/haproxy-ingress/blob/master/docs/haproxy-ingress.yaml) and example [here](https://github.com/jcmoraisjr/haproxy-ingress/tree/master/examples/rbac).

Please provide more information like your ingress resources, deployment and what exactly isn't working if you still have any problem.

**Comment by Zwordi** [comment]
Hello

@veeshall 

Your example with the deployment was the bit of stuff i was missing to properly understand how to use the ingress.class instruction.

Now my ingress ressources doesn't get any endpoint even if i specify:
```
status:
  loadbalanecr:
  ingress:
   - ip
```
And none of my request (url) are working.

So as i say on my first post i don't have an ingress-controller namespaces working with haproxy-deployment on it. I change all the namespaces reference on the rbac setup for each namespaces and now i think it's why i have this behavior.

I should have all my haproxy-controller deployment only on the ingress-controller namespaces with ingress.class setup in order to target each ingress ressource on each namespaces.

@jcmoraisjr 

I will make a test this afternoon by deleting all my current rbac stuff related to the haproxy and by recreate it accordingly to the examples.
