### ISSUE TITLE
503 for first backend server in latest and v0.6-beta.1 when dynamic-scaling is true

### ISSUE THREAD

**Issue by swapnil1988** [jcmoraisjr/haproxy-ingress#175]
**This issue is observed in latest and v0.6-beta.1, this issue is not observed in v0.5**

Basically when a new ingress resource is added the first server0000 is always disabled and gives a **503 Service Unavailable** error other backend servers (server0001 ...) works fine.

```
######                                                                                                                           
###### Backends                                                                                                                  
######                                                                                                                           
backend abc-svc-8089                                                                                 
    mode http                                                                                                                    
    balance roundrobin                                                                                                           
    server server0000 10.44.0.8:8078 maxconn 1 weight 1 check port 8078 inter 2s  // **gives 503 always**                                               
    server server0001 10.44.0.10:8078 maxconn 1 weight 1 check port 8078 inter 2s // **this works fine**           
    server server0002 127.0.0.1:81 maxconn 1 check disabled inter 2s            
    server server0003 127.0.0.1:81 maxconn 1 check disabled inter 2s            
    server server0004 127.0.0.1:81 maxconn 1 check disabled inter 2s            
    server server0005 127.0.0.1:81 maxconn 1 check disabled inter 2s            
    server server0006 127.0.0.1:81 maxconn 1 check disabled inter 2s            
    server server0007 127.0.0.1:81 maxconn 1 check disabled inter 2s
```

**All endpoints when accessed directly work which means all the endpoints are active**

**Comment by jcmoraisjr** [comment]
Hi, how was your test that conclude the first endpoint always give 503?

Give more details about your env, which default ingress configuration you changed, your ingress resource, how you provisioned your k8s, etc. so I can also reproduce.

**Comment by swapnil1988** [comment]
Hi @jcmoraisjr, Thanks for the reply.

Below are the details 

**K8s version 1.10.4** is a bare metal install using kubeadm.

**Default Ingress configuration changed**

```
    "dynamic-scaling": "true",
    "max-connections": "5000",
    "syslog-endpoint": "127.0.0.1:5140",
```
"backend-check-interval": "2s", is default and is some how causing the issue. I kind of disabled it by changing the interval to "backend-check-interval": "99999999999999h", and the issue disappeared. 

**Ingress resource:**

```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: app-ingress
  namespace: app-namespace
  annotations:
    kubernetes.io/ingress.class: "app-name"
    ingress.kubernetes.io/ssl-passthrough: "false"
    ingress.kubernetes.io/ssl-redirect: "false"
    ingress.kubernetes.io/rewrite-target: "/"
    ingress.kubernetes.io/maxconn-server: "1" //This is the extra piece which is not supported in v.0.5 
    ingress.kubernetes.io/slots-increment: 20
spec:
  rules:
  - http:
      paths:
      - path: /app-name
        backend:
          serviceName: app-svc
          servicePort: 8089
```
