### ISSUE TITLE
Support for sticky-sessions

### ISSUE THREAD

**Issue by RTBathula** [jcmoraisjr/haproxy-ingress#18]
I want to know way to implement sticky-sessions

**Comment by jcmoraisjr** [comment]
This is a v0.4 (next release) feature. I'll update this issue just after implement it.

**Comment by RTBathula** [comment]
Is there a way I can mount /usr/local/etc/haproxy/haproxy.tmpl and write configuration there like 
`backend bk_web
  balance roundrobin
  cookie SERVERID insert indirect nocache
  server s1 192.168.10.11:80 check cookie s1
  server s2 192.168.10.21:80 check cookie s2`

**Comment by jcmoraisjr** [comment]
Sure. Use `v0.3-beta.2` or `canary` version (releasing `v0.3` later this week) and mount `/etc/haproxy/template/` to a configmap whose key is `haproxy.tmpl` and value is your new template.

Create the configmap:

`kubectl create configmap haproxy-tmpl --from-file=haproxy.tmpl`

Configure the deployment:

```
      containers:
      - ...
        volumeMounts:
        - name: tmpl
          mountPath: /etc/haproxy/template
          readOnly: true
      volumes:
      - name: tmpl
        configMap:
          name: haproxy-tmpl
```

This strategy doesn't work on `v0.2` because `.cfg ` would be removed.
