### ISSUE TITLE
haproxy requires restart after a TLS secret is updated

### ISSUE THREAD

**Issue by qwylz** [jcmoraisjr/haproxy-ingress#181]
When a TLS secret is updated, the haproxy ingress controller notices and updates the relevant file with the updated data reasonably soon after the secret is updated.  Yeah!  :-)  However, the running haproxy instance will never be able to read the updated TLS data (this is by design of haproxy).  Boo.  :-(  In order for haproxy to start to use the new TLS cert/key, haproxy **must** be restarted.

Please instrument the ingress controller so that it restarts haproxy after updating TLS cert/key files.  This could be done either immediately after writing a new TLS file or after a short delay (a minute or so?), so that a single restart could account for multiple TLS secret updates all happening about the same time.

**Comment by jcmoraisjr** [comment]
Hi, couldn't reproduce here. Just after I update a tls secret - both default or per domain certificate - HAProxy is reloaded and the new certificate is used on new handshakes. Using v0.6-beta.1. Please describe your controller version and all the steps to reproduce the problem.

**Comment by qwylz** [comment]
I am so sorry to have wasted your time on this.  You are correct:  haproxy is restarted as is required.  I am using the same version.  It turns out I had a mistake in my ingress definitions that caused this that I did not catch until you said that it works.

For anyone who might make the same mistake, here's what I did wrong:

My original ingress definitions looked like the following (note that the `my.org` tls secret is a wild card cert for the domain):

```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: haproxy
  name: some-ingress
spec:
  tls:
  - secretName: my.org
  rules:
  - host: app1.my.org
    http:
      paths:
      - backend:
          serviceName: app1-service
          servicePort: 80
        path: /some/path
```

The ingress definitions are supposed to look like this (note the `hosts` list under `spec.tls`):

```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: haproxy
  name: some-ingress
spec:
  tls:
  - secretName: my.org
    hosts:
    - app1.my.org
  rules:
  - host: app1.my.org
    http:
      paths:
      - backend:
          serviceName: app1-service
          servicePort: 80
        path: /some/path
```

No matter how many times I've looked at the ingress definitions, I never noticed the mistake.  I didn't find it until taking a closer look for something I had done wrong that made it not work for me when it worked for you.

Thank you for time and, again, thank you for a great ingress for haproxy!
