### ISSUE TITLE
Support for gRPC services in haproxy ingress

### ISSUE THREAD

**Issue by syd-shopin** [jcmoraisjr/haproxy-ingress#184]
Hi @jcmoraisjr, 

Do haproxy ingress supports gRPC application running in GKE Cluster?

**Comment by Scukerman** [comment]
HAProxy does not support gRPC natively. All what it can do is to loadbalance tcp traffic.
So the answer is both yes and no.

**Comment by jcmoraisjr** [comment]
HAProxy 1.8 only support incoming http/2 requests. end-to-end http/2 is a 1.9 roadmap.

I'd try ssl-passthrough and let your backend do the ssl-offload. Let us know if this work. Need at least v0.6-beta.1 in order to use HAProxy 1.8.

**Comment by Scukerman** [comment]
@jcmoraisjr ssl-passthrough doesn't work currently, need to merge https://github.com/jcmoraisjr/haproxy-ingress/pull/183

**Comment by jcmoraisjr** [comment]
Indeed. Btw using v0.6 (HAProxy 1.8) isn't required if using ssl-passthrough since haproxy ingress will tcp-proxy the request if the sni extension match the hostname of your service. So change to v0.5 with ssl-passthrough if trying to use grpc.

**Comment by jcmoraisjr** [comment]
Hi, regarding the error perhaps the client is complaining that the server doesn't speak http/2 during the tls handshake. Try changing to `quay.io/jcmoraisjr/haproxy-ingress:v0.6-beta.2` which implements h2 in the frontend and has fixed ssl-passthrough.

Regarding the warning: a ssl passthrough connection means that haproxy will only inspect for the sni extension in order to know where to proxy the request - without ssl-offloading - ie without know nothing about path and http headers, doing a plain old tcp proxy. Because of that only the first service is used, the other service name and all paths are ignored. The only way to differentiate two passthrough connections is using different host names. You can of course use several dns entries or even a wildcard name to the same ip address.

**Comment by syd-shopin** [comment]
@jcmoraisjr I have changed the image to `quay.io/jcmoraisjr/haproxy-ingress:v0.6-beta.2` and disabled ssl-passthrough, it is now communicating over HTTP2 but I am still getting some errors. 

**Since we are not allowing ssl-passthrough we are running backend gRPC services on insecure channel. We are getting below error**

```
debug_error_string = "{"created":"@1532409533.776273285","description":"Received http2 :status header with non-200 OK status","file":"src/c
ore/ext/filters/http/client/http_client_filter.cc","file_line":92,"grpc_message":"Received http2 header with status: 502","grpc_status":1,"value":"
502"}"
```

**If we run the backend gRPC services on secure channel we are getting below error :** 

```
debug_error_string = "{"created":"@1532406686.742454221","description":"Received http2 :status header with non-200 OK status","file":"src/c
ore/ext/filters/http/client/http_client_filter.cc","file_line":92,"grpc_message":"Received http2 header with status: 400","grpc_status":1,"value":"
400"}"
```
Is there something wrong how we are communicating with backend services? 
Thanks

**Comment by jcmoraisjr** [comment]
HAProxy 1.8 doesn't support outgoing h2 connections - between haproxy and your backends - which should explain the errors above. Try using ssl-passthrough with v0.6. I couldn't find the time yet to build a grpc lab in order to see, test and know what's really supported.

**Comment by syd-shopin** [comment]
HI @jcmoraisjr, 

I tried using **v0.6-beta.2** with ssl-passthrough enabled, but still getting same error : 

```
E0725 10:19:38.679815692   29362 ssl_transport_security.cc:1228] Handshake failed with fatal error SSL_ERROR_SSL: error:100000f7:SSL routines:OPENS
SL_internal:WRONG_VERSION_NUMBER.
Traceback (most recent call last):
  File "vessel_cli.py", line 30, in <module>
    response = stub.GetVessel(vessel)
  File "/usr/local/lib/python2.7/dist-packages/grpc/_channel.py", line 514, in __call__
    return _end_unary_response_blocking(state, call, False, None)
  File "/usr/local/lib/python2.7/dist-packages/grpc/_channel.py", line 448, in _end_unary_response_blocking
    raise _Rendezvous(state, None, None, deadline)
grpc._channel._Rendezvous: <_Rendezvous of RPC that terminated with:
        status = StatusCode.UNAVAILABLE
        details = "Connect Failed"
        debug_error_string = "{"created":"@1532513978.680145151","description":"Failed to create subchannel","file":"src/core/ext/filters/client_ch
annel/client_channel.cc","file_line":2673,"referenced_errors":[{"created":"@1532513978.680142189","description":"Pick Cancelled","file":"src/core/e
xt/filters/client_channel/lb_policy/pick_first/pick_first.cc","file_line":210,"referenced_errors":[{"created":"@1532513978.680131139","description"
:"Connect Failed","file":"src/core/ext/filters/client_channel/subchannel.cc","file_line":641,"grpc_status":14,"referenced_errors":[{"created":"@153
2513978.679992032","description":"Handshake failed","file":"src/core/lib/security/transport/security_handshaker.cc","file_line":248,"tsi_code":10,"
tsi_error":"TSI_PROTOCOL_FAILURE"}]}]}]}"

```
Also, when I check my haproxy controllers log I can see some warnings: 

```
severity:  "WARNING"  
 textPayload:  "ignoring ssl passthrough of shippy.example.com as it doesn't have a default backend (root context)"  
severity:  "WARNING"  
 textPayload:  "ignoring path /Vessel/GetVessel of ssl passthrough host shippy.example.com"
```

I am not sure why it is giving me warning of not having default backend. I configure it using below command: 

```
$ kubectl run ingress-default-backend \
  --namespace=ingress-controller \
  --image=gcr.io/google_containers/defaultbackend:1.0 \
  --port=8080 \
  --limits=cpu=10m,memory=20Mi \
  --expose

```
It is up and running without any errors. 

As you mentioned because of ssl-passthrough only the first service is used, the other service name and all paths are ignored. I am only using one gRPC service to test. 

haproxy-ingress-rules.yaml: 

```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: "haproxy"
    ingress.kubernetes.io/ssl-passthrough: "true"
  name: haproxy-ingress
  namespace: grpc
spec:
  tls:
  - hosts:
    - shippy.example.com
    secretName: tls-secret
  rules:
  - host: shippy.example.com
    http:
      paths:
      - path: /Vessel/GetVessel
        backend:
          serviceName: vessel
          servicePort: 50052
```

I am unable to figure out if the problem is with haproxy or with backend service or how we are communicating with the backend service. 

I really appreciate your help in this. 
Thanks!

**Comment by jcmoraisjr** [comment]
Try to change `path: /...` to just `path: /` and ssl-passthrough will start to be used.

I think `tls:` will be ignored since your backend will do the offload. Try removing this as well if you still have any problem.

**Comment by syd-shopin** [comment]
@jcmoraisjr changing path to `path: /` worked!!! 

**But in this case only 1 micro-service is working at a time.** 

vessel_rule.yaml

```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: "haproxy"
    ingress.kubernetes.io/ssl-passthrough: "true"
  name: shippy-ingress
  namespace: shippy-grpc
spec:
  rules:
  - host: shippy.example.com
     http:
        paths:
          - path: /
             backend:
                 serviceName: vessel
                 servicePort: 50052
```
With above rule my **vessel service** runs perfectly. 

cons_rule.yaml

```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: "haproxy"
    ingress.kubernetes.io/ssl-passthrough: "true"
  name: shippy-ingress
  namespace: shippy-grpc
spec:
  rules:
  - host: shippy.example.com
     http:
         paths:
           - path: /
              backend:
                  serviceName: consignment
                  servicePort: 50051
```
With my above rule **consignment service** runs perfectly. 

**But If I want to run both the services it is not possible, as you said earlier:** 

> Because of ssl-passthrough only the first service is used, the other service name and all paths are ignored. The only way to differentiate two passthrough connections is using different host names. 
> You can of course use several dns entries or even a wildcard name to the same ip address. 

**In this case if I change my ingress_rules file to add multiple hosts will it work??** 

```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: "haproxy"
    ingress.kubernetes.io/ssl-passthrough: "true"
  name: shippy-ingress
  namespace: shippy-grpc
  spec:
  rules:
  - host: shippy_vessel.example.com
     http:
        paths:
          - path: /
             backend:
                 serviceName: vessel
                 servicePort: 50052
  - host: shippy_consignment.example.com
     http:
         paths:
           - path: /
              backend:
                  serviceName: consignment
                  servicePort: 50051 
```

> If this type of configuration works with multiple hosts for multiple micro-services then why we use HAProxy Ingress Controller. We can easily use Kubernetes Service to achieve the same result. 

I don't know may be I am getting this wrong. You can correct me. 

**Is there any possibility of using multiple micro-services without multiple host names with HAProxy Controller.**  

Thank you @jcmoraisjr for your prompt replies.
