### ISSUE TITLE
how to configure option httplog in the configmap

### ISSUE THREAD

**Issue by dcowden** [jcmoraisjr/haproxy-ingress#185]
I feel like i must be missing it-- how do i get 'option httplog' into the frontend configuration for the ingress controller?

i found tcp-log-format and https-log-format and http-log-format. However, these seem to be intended to activate custom formats, and further the documentation says they are only used when syslog is in use ( i'm using the default configuration, which is sending data to stdout ).

Our ingress controller has generated this haproxy frontend config:

```
######
###### HTTPS frontend (tcp mode)
######
frontend httpsfront
    bind *:443
    mode tcp
    tcp-request inspect-delay 5s
    tcp-request content accept if { req.ssl_hello_type 1 }
    default_backend httpsback-shared-backend

``

But we want this:

```
######
######
frontend httpsfront
    bind *:443
    mode tcp
    option httplog
    tcp-request inspect-delay 5s
    tcp-request content accept if { req.ssl_hello_type 1 }
    default_backend httpsback-shared-backend
```

**Comment by dcowden** [comment]
as a side note, it appears that /etc/haproxy/template/haproxy.tpml explicitly turns off request logging:

defaults
    log global
{{- if $cfg.LoadServerState }}
    load-server-state-from-file global
{{- end }}
    maxconn {{ $cfg.MaxConn }}
{{- if $cfg.DrainSupport }}
    option persist
{{- else }}
    option redispatch
{{- end }}
    **option dontlognull**

I'm trying to do performance analysis, so i need option httplog

**Comment by dcowden** [comment]
looking at the [source for the template](https://github.com/jcmoraisjr/haproxy-ingress/blob/master/rootfs/etc/haproxy/template/haproxy.tmpl#L120), it seems like there's no way to inject options httplog ,


unless specifying log-format {{ $cfg.HTTPSLogFormat }} will activate it.

For now i'll try a workaround of specifying a custom log format that's as the same as httplog would have given

**Comment by dcowden** [comment]
Ok, I'm stuck i think.
I tried defining https-log-format, but it doesnt work because It is only used when syslog is used.

My problem is that I need performance/request logging, but I want the data to to stdout ( so that it is in the docker logs ) vs syslog.

Unless i'm missing something, its not possible to configure the ingress controller to send request logging to stdout, because all of the options are [conditional on syslog](https://github.com/jcmoraisjr/haproxy-ingress/blob/master/rootfs/etc/haproxy/template/haproxy.tmpl#L127)

Is there a workaround/option?  Right now the only thing i know to do is to make a derivative image, and change the template in there, which i'd rather not do!

**Comment by dcowden** [comment]
For those others trying to get timestamps in the docker logs: 

The plot thickens-- it appears that haproxy itself wont send data to stderr/stdout-- only syslog.

I found this thread that [helps](https://github.com/dockerfile/haproxy/issues/3)

There i mention of starting up syslog/rsyslogd so that the data appears in stdout, but this doesnt appear implemented in this container.

[This discussion is also relevant](https://github.com/docker-library/haproxy/pull/39):

I can't believe it is this difficult to get standard access logs into the docker logs!  I feel like i'm missing something easy!

**Comment by Scukerman** [comment]
HAProxy doesn't support any other logging but syslog.

Check these issues out to find your own way of exposing logs to stdout\stderr:
https://github.com/jcmoraisjr/haproxy-ingress/issues/110, https://github.com/jcmoraisjr/haproxy-ingress/issues/74

**Comment by dcowden** [comment]
Thanks @Scukerman!

I  will try the sidecar approach.

**Comment by dcowden** [comment]
Thanks for the suggestion @Scukerman , I got the sidecar running. I'm seeing some odd behavior, though,i'm hoping someone has seen.

When i first start up the ingress ( with sidecar as described in #110), I get logging perfectly.

However, after about 1 minute or so, no further access logs show up.  Restarting the pod restores logging for about the same period of time, then it stops.  

There are no errors in access_log or the haproxy log. Anyone have ideas?

**Comment by Scukerman** [comment]
I don't use the sidecar approach because it's a lot easier to get all the logs in one place. I run a separate pod with `jumanjiman/rsyslog` image and use `rsyslog-pod.my-namespace:514`.
Running this way I haven't see anything like you described.

P.S. I use Deployment instead of DaemonSet.

**Comment by dcowden** [comment]
awesome! thanks for the help! i'll try that!

**Comment by dcowden** [comment]
SOLVED-- for documentation purposes, i've documenting what worked for me.

@Scukerman  is right that a centralized deployment of a syslog is best.  This prevents the need to restart the ingress pods when changing thigns, which is nice.

Sadly, I couldn't take advantage of that strategy because my ingress controllers use hostNetwork:true, since we are on cni and k8s < 1.9.  a service providing in-cluster syslog isn't resolvable by DNS.

I used this sidecar strategy, which works well:

```
apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: ingress-lb
  namespace: ops
  labels:
    name: ingress-lb
spec:
  updateStrategy:
    type: RollingUpdate
  selector:
    matchLabels:
      run: haproxy-ingress
  template:
    metadata:
      labels:
        run: haproxy-ingress
    spec:
      hostNetwork: true
      serviceAccountName: nginx-ingress-serviceaccount
      containers:
      - name: access-log
        image: jumanjiman/rsyslog
        ports:
        - name: udp
          containerPort: 514
          protocol: UDP
      - name: haproxy-ingress
        image: quay.io/jcmoraisjr/haproxy-ingress:v0.6-beta.1
        args:
        - --default-backend-service=$(POD_NAMESPACE)/default-http-backend
        - --allow-cross-namespace
        - --configmap=$(POD_NAMESPACE)/haproxy-ingress
        - --sort-backends
        - --v=3
        ports:
        - name: http
          containerPort: 80
        - name: https
          containerPort: 443
        - name: stat
          containerPort: 1936
        readinessProbe:
          httpGet:
            path: /stats
            port: 1936
            scheme: HTTP
        livenessProbe:
          httpGet:
            path: /stats
            port: 1936
            scheme: HTTP
          initialDelaySeconds: 10
          timeoutSeconds: 1
        env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
```

Advice for newcomers, I stumbled on the combination of haproxy's log format and yaml escaping.  Here's a working configmap, which does a custom log format escaped correctly:

```
apiVersion: v1
kind: ConfigMap
metadata:
  name: haproxy-ingress
  namespace: ops
data:
  balance-algorithm: "leastconn"
  drain-support: "true"
  use-proxy-protcol: "true"
  proxy-body-size: "100m"
  ssl-redirect: "true"
  timeout-connect: "5s"
  timeout-http-request: "300s"
  timeout-queue: "300s"
  timeout-server: "300s"
  timeout-server-fin: "300s"
  syslog-endpoint: "localhost:514"
  http-log-format: "%ci:%cp->%b/%s\\ method=%HM\\ uri=%HU\\ rcvms=%TR\\ serverms=%Tr\\ activems=%Ta\\ bytes=%B\\ status=%ST"
```

Finally, and again for newcomers, here's the manifests to deploy a stand-alone syslog server for haproxy, in the case your ingress controllers are using hostPort instead of hostNetwork. We will move to this approach when we can use hostPort 

```
apiVersion: v1
kind: Service
metadata:
  name: ingress-access-logs
  namespace: ops
  labels:
    k8s-app: ingress-access-logs
spec:
  ports:
  - port: 514
    targetPort: 514
    protocol: UDP
  selector:
    app: ingress-access-logs
---

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: ingress-access-logs
  namespace: ops
  labels:
    name: ingress-access-logs
spec:
  revisionHistoryLimit: 2
  replicas: 1
  template:
    metadata:
      labels:
        app: ingress-access-logs   
    spec:      
      serviceAccountName: nginx-ingress-serviceaccount
      containers:
      - name: access-log
        image: jumanjiman/rsyslog
        ports:
        - name: udp
          containerPort: 514
          protocol: UDP
```
