### ISSUE TITLE
How to configure support for statefulset

### ISSUE THREAD

**Issue by aland-zhang** [jcmoraisjr/haproxy-ingress#204]
How to configure support for statefulset？
For example: mysql statefulset replicas 3 ，Headless Service mysql. How to configure 3 tcp ports for mysql-0.mysql.svc.default.cluster.local;  mysql-1.mysql.svc.default.cluster.local ； mysql-2.mysql.svc.default.cluster.local 。

**Comment by jcmoraisjr** [comment]
See tcp-services configmap [doc](https://github.com/jcmoraisjr/haproxy-ingress#tcp-services-configmap). Create three lines with public port number (key), and namespace/service-name:service-port (value).

**Comment by aland-zhang** [comment]
This requires three Headless Service matches to match the statefulset pod

**Comment by aland-zhang** [comment]
Forward Traffic to all Pods of a StatefulSet
There is the usual way of forwarding traffic to a Service matching a StatefulSet. Create a Service with the pods label selector as selector, and use the service name as Backend ServiceName.

```
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: http
spec:
  serviceName: "nginx-set"
  replicas: 2
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: gcr.io/google_containers/nginx-slim:0.8
        ports:
        - containerPort: 80
          name: http
----
apiVersion: v1
kind: Service
metadata:
  name: nginx-set
  labels:
    app: nginx
spec:
  ports:
  - port: 80
    name: http
  clusterIP: None
  selector:
    app: nginx
Create another service for StatefulSets pods with selector.

apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  labels:
    app: nginx
spec:
  ports:
  - port: 80
    name: http
  selector:
    app: nginx

And Use the service in the ingress Backend service name, as:

backend:
  serviceName: nginx-service
  servicePort: '80'
That will forward traffic to your StatefulSets Pods.

 Forward Traffic to specific Pods of a StatefulSet
There is a way to send traffic to all or specific pod of a StatefulSet using voyager. You can set hostNames field in Backend, traffic will only forwarded to those pods.

For Example the above StatefulSet will create two pod.

web-0
web-1
Those are the host names.

Now Create a ingress that will only forward traffic to web-0

apiVersion: voyager.appscode.com/v1beta1
kind: Ingress
metadata:
  name: test-ingress
  namespace: default
spec:
  rules:
  - host: appscode.example.com
     tcp:
      port: '7800'
        backend:
          hostNames:
          - kafka-0
          serviceName: kafka #Same service name
          servicePort: '8000' 
  - host: appscode.example.com
     tcp:
      port: '7900'
        backend:
          hostNames:
          - kafka-1
          serviceName: kafka  #Same service name
          servicePort: '8000' 
```
