### ISSUE TITLE
HAProxy Ingress Basic Authentication Error

### ISSUE THREAD

**Issue by aland-zhang** [jcmoraisjr/haproxy-ingress#217]
HAProxy Ingress Basic Authentication Error 

logs:

```
[ALERT] 261/023244 (202) : parsing [/etc/haproxy/haproxy.cfg:222] : error detected while parsing an 'http-request auth' condition : missing closing '}' in condition.
--
  | [ALERT] 261/023244 (202) : Error(s) found in configuration file : /etc/haproxy/haproxy.cfg
  | E0919 02:32:44.757126       7 controller.go:316] unexpected failure restarting the backend:
  | exit status 1

```
the ingress:

```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: haproxy-ingress
    ingress.kubernetes.io/auth-realm: 'john::admin'
    ingress.kubernetes.io/auth-type: basic
  name: nodejs
spec:
  rules:
    - host: nodejs.10.10.128.62.nip.io
      http:
        paths:
          - backend:
              serviceName: nodejs-mongodb-example
              servicePort: 8080
            path: /
```
