### ISSUE TITLE
Feature Request: Add unique ID header

### ISSUE THREAD

**Issue by roynasser** [jcmoraisjr/haproxy-ingress#230]
Hi, is it possible to implement https://cbonte.github.io/haproxy-dconv/1.8/configuration.html#4.2-unique-id-format and the associated https://cbonte.github.io/haproxy-dconv/1.8/configuration.html#unique-id-header configurations?  They are quite useful for end2end logging of requests.

Is there a way of adding "custom" configuration snippets into different areas of the haproxy configuration through annotations or configmaps for different resources so we can add different options which arent specifically supported?

**Comment by jcmoraisjr** [comment]
Hi, unique-id-header and format are frontend configs so you can use config-frontend configmap option if you want them globally configured.

**Comment by GMartinez-Sisti** [comment]
I'm using this configmap to get these values, and others:

```yaml
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: haproxy-int
  namespace: ingress-controller
data:
  max-connections: "10000"
  ssl-ciphers: ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-SHA384:ECDHE-RSA-AES256-SHA384:ECDHE-ECDSA-AES128-SHA256:ECDHE-RSA-AES128-SHA256
  ssl-options: no-sslv3 no-tlsv10 no-tlsv11 no-tls-tickets
  syslog-endpoint: localhost:514
  http-log-format: "%ci:%cp\\ [%t]\\ %ft\\ %b/%s\\ %Tq/%Tw/%Tc/%Tr/%Tt\\ %ST\\ %B\\ %CC\\ \\ %CS\\ %tsc\\ %ac/%fc/%bc/%sc/%rc\\ %sq/%bq\\ %hr\\ %hs\\ %{+Q}r\\ {request_id=%ID\\ ssl_version=%sslv\\ ssl_cypher=%sslc}"
  https-log-format: "%ci:%cp\\ [%t]\\ %ft\\ %b/%s\\ %ST\\ %B\\ %tsc\\ %ac/%fc/%bc/%sc/%rc\\ %sq/%bq\\ %hr\\ %hs"
  use-proxy-protocol: "true"
  config-global: |
  config-frontend: |
    unique-id-format %{+X}o\ %ci:%cp_%fi:%fp_%Ts_%rt:%pid
    unique-id-header X-Request-ID
    capture request header Host len 64
    capture request header X-Request-ID len 64
    capture request header User-Agent len 200
```
