### ISSUE TITLE
CORS Broken?

### ISSUE THREAD

**Issue by james-powis** [jcmoraisjr/haproxy-ingress#264]
```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    ingress.kubernetes.io/enable-cors: "true"
...
```

Ha proxy works but inspecting requested page through ingress (which works) is lacking any access-control-allow-origin: "*" headers.

My understanding is that CORS when enabled should by default accept *
