### ISSUE TITLE
Haproxy farm failover 

### ISSUE THREAD

**Issue by cpradipdevops** [jcmoraisjr/haproxy-ingress#279]
Hi there, i am trying to do farm fail-over with haproxy ingress
Want to achieve one service(web) as a active and another service(web_bkp) would be standby. And if some pods of service =>web crash any time and my RC takes time to come back with new pods, during the time my ingress should redirect the traffic to the secondary service i.e web_bkp which was as standby.

Below is my ingress yaml:

```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: test-ing
  annotations:
    ingress.kubernetes.io/rewrite-target: "/"
    ingress.kubernetes.io/ingress.class: "haproxy"
    ingress.kubernetes.io/config-backend: |
        # detect capacity issues in production farm
        acl MAIN_not_enough_capacity nbsrv(web) le 2
        # failover traffic to backup farm
        use_backend web_bkp if MAIN_not_enough_capacity
spec:
  rules:
  - host: test.example.com
    http:
      paths:
      - path: /
        backend:
          serviceName: web
          servicePort: 5000
      - path: /
        backend:
          serviceName: web_bkp
          servicePort: 7000
```

By default if i do curl "http://test.example.com" it point to service 'web', but if i scale down the no if  pods to 2 or 0 of service web, ingress does not fail over traffic to backup farm i.e web_bkp.
Am i doing any mistake in my configuration please suggest. Or there would be some other way to achieve this.
