### ISSUE TITLE
haproxy-ingress is not resolving the correct pod/container port to use

### ISSUE THREAD

**Issue by mhyllander** [jcmoraisjr/haproxy-ingress#280]
I am using dynamic scaling with DNS to resolve the backend server IP addresses. The k8s services are headless (ClusterIP: "None"). I have noticed that haproxy-ingress does not correctly determine the pod port to use, instead it is using the port exactly as specified in the Ingress object. If the Ingress object specifies a port name instead of a port number, then haproxy-ingress produces an invalid haproxy configuration.

For example, given the following resources:

```yaml
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: platform-ticket
  namespace: platform
  labels:
    app: ticket
    release: platform
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ticket
      release: platform
  template:
    metadata:
      labels:
        app: ticket
        release: platform
    spec:
      containers:
        name: ticket
        image: path:tag
        ports:
        - name: http
          containerPort: 80
          protocol: TCP
      imagePullSecrets:
      - name: acr-reader-secret
---
apiVersion: v1
kind: Service
metadata:
  name: platform-ticket
  namespace: platform
  labels:
    app: ticket
    release: platform
spec:
  clusterIP: None
  ports:
  - name: http
    port: 9899
    protocol: TCP
    targetPort: http
  selector:
    app: ticket
    release: platform
  sessionAffinity: None
  type: ClusterIP
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: platform-ticket
  namespace: platform
  annotations:
    ingress.kubernetes.io/use-resolver: kubernetes
    kubernetes.io/ingress.class: haproxy
  labels:
    app: ticket
    release: platform
spec:
  rules:
  - host: ticket.example.com
    http:
      paths:
      - backend:
          serviceName: platform-ticket
          servicePort: http
        path: /v1/auth
  tls:
  - hosts:
    - ticket.example.com
    secretName: example.com-tls
```

Notice that the ingress `backend.servicePort` is "http", which matches the service's port name. But this will not work with haproxy, because it tries to use "http" as the port number in the configuration file. If I change `backend.servicePort` to 9899, which is the port number used by the service, it will create a valid backend definition:

```
backend platform-platform-ticket-9899
    mode http
    balance roundrobin
    server-template server-dns 100 platform-ticket.platform.svc.cluster.local:9899 resolvers kubernetes resolve-prefer ipv4 init-addr none check inter 2s
```

but this will still fail, because the pod is listening on port 80, not port 9899, so haproxy's health check will fail and it will not find a backend server that is UP.

The configuration above works with nginx-ingress, which does the appropriate manifest lookups to determine port number to use. I believe haproxy-ingress should also do this: check the service's `targetPort` and the pod's `containerPort` to get the correct pod port.
