### ISSUE TITLE
Failed to run a s non-root v0.7-beta.6

### ISSUE THREAD

**Issue by steven166** [jcmoraisjr/haproxy-ingress#292]
First of all: great ingress-controller!
I have an issue when I try to run it as non-root (because security...). When I try to run it I get the following error: 
```
link /ingress-controller/ssl/<secret> /ingress-controller/ssl/shared-frontend/+default.pem: permission denied
```

Somehow the folder /ingress-controller/ssl/shared-frontend has a weird file permission:
```
d-w-r-sr--    2 10000000 root          4096 Jan 23 09:11 shared-frontend
```
Could you help me with this, as it is a requirement for us to run the ingress as non-root.

Daemonset manifest:
```
apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  labels:
    app: haproxy-ingress
    component: haproxy-ingress
  name: haproxy-ingress
  namespace: kube-ingress
spec:
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: haproxy-ingress
      component: haproxy-ingress
  template:
    metadata:
      annotations:
        prometheus.io/path: /metrics
        prometheus.io/port: "10254"
        prometheus.io/scrape: "true"
      creationTimestamp: null
      labels:
        app: haproxy-ingress
        component: haproxy-ingress
        disruption: low
    spec:
      containers:
      - command:
        - sh
        - -c
        - echo > /etc/haproxy/haproxy.cfg && /dumb-init
          -- /start.sh --default-backend-service=$(POD_NAMESPACE)/default-backend
          --default-ssl-certificate=$(POD_NAMESPACE)/tlsi-maxxton-net --configmap=$(POD_NAMESPACE)/haproxy-ingress
        env:
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        - name: POD_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.name
        # tag: v0.7-beta.6
        image: quay.io/jcmoraisjr/haproxy-ingress@sha256:65dc8f5b2a7e6833f45cc96daea9119095e434cbaa65a20482a85e16b2ad854e
        imagePullPolicy: Always
        name: haproxy-ingress
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        - containerPort: 8443
          name: https
          protocol: TCP
        - containerPort: 1936
          name: stat
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /healthz
            port: 10253
            scheme: HTTP
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        resources:
          limits:
            cpu: "1"
            memory: 2Gi
          requests:
            cpu: 300m
            memory: 2Gi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /ingress-controller/ssl
          name: ingress-controller-ssl
        - mountPath: /ingress-controller/cacerts
          name: ingress-controller-cacerts
        - mountPath: /var/lib/haproxy
          name: ingress-controller-var
        - mountPath: /var/run
          name: ingress-controller-var-run
      dnsPolicy: ClusterFirst
      nodeSelector:
        zone: router
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000000000
      serviceAccount: haproxy-ingress
      serviceAccountName: haproxy-ingress
      terminationGracePeriodSeconds: 30
      volumes:
      - emptyDir: {}
        name: ingress-controller-ssl
      - emptyDir: {}
        name: ingress-controller-cacerts
      - emptyDir: {}
        name: ingress-controller-var
      - emptyDir: {}
        name: ingress-controller-var-run
  templateGeneration: 36
  updateStrategy:
    rollingUpdate:
      maxUnavailable: 1
    type: RollingUpdate
```
**versions**
kubernetes: version.Info{Major:"1", Minor:"11+", GitVersion:"v1.11.2-gke.26", GitCommit:"25365995b58530998bdcd4ea6383682858a0fb7b", GitTreeState:"clean", BuildDate:"2018-12-11T02:37:25Z", GoVersion:"go1.10.3b4", Compiler:"gc", Platform:"linux/amd64"}
haproxy-ingress: v0.7-beta.6
