### ISSUE TITLE
HTTPS proxy backend handling above version 0.5

### ISSUE THREAD

**Issue by protometa** [jcmoraisjr/haproxy-ingress#298]
I have a particular case where I use haproxy-ingress to handle TLS and load balance for a squid proxy deployment. That is with a `quay.io/jcmoraisjr/haproxy-ingress:v0.5` controller and an ingress resource like so
```yaml
kind: Ingress
apiVersion: extensions/v1beta1
metadata:
  name: proxy-ingress
  annotations:
    kubernetes.io/ingress.class: haproxy
    certmanager.k8s.io/cluster-issuer: letsencrypt-prod
    certmanager.k8s.io/acme-challenge-type: dns01
    certmanager.k8s.io/acme-dns01-provider: route53
spec:
  tls:
  - hosts:
    - proxy.example.com
    secretName: example-com-tls-prod
  rules:
    - host: 'proxy.example.com'
      http:
        paths:
        - path: '/'
          backend:
            serviceName: squid-service
            servicePort: 80
```
I can use the proxy just fine with
```
curl --proxy https://proxy.example.com ...
```
But when I try to upgrade the controller to `v0.6` or `v0.7-beta.5`, the curl will only return `default backend - 404`.
