### ISSUE TITLE
Problem with ssl-redirect: true

### ISSUE THREAD

**Issue by reymonlu** [jcmoraisjr/haproxy-ingress#299]
Hi,
I want to redirect all my traffic in HTTP to HTTPS but the option ssl-redirect: true in the configmap of the HAproxy ingress Controller seems to be ignore.
Here is my files : 

**HAproxy daemonset-set**
```yaml
apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  labels:
    run: haproxy-ingress
  name: haproxy-ingress
  namespace: ingress-controller
spec:
  updateStrategy:
    type: RollingUpdate
  selector:
    matchLabels:
      run: haproxy-ingress
  template:
    metadata:
      labels:
        run: haproxy-ingress
    spec:
      hostNetwork: true
      serviceAccountName: ingress-controller
      containers:
      - name: haproxy-ingress
        image: quay.io/jcmoraisjr/haproxy-ingress
        resources:
          limits:
            cpu: 50m
            memory: 100Mi
        args:
        - --default-backend-service=$(POD_NAMESPACE)/ingress-default-backend
        - --configmap=$(POD_NAMESPACE)/ingress-controller-leader-haproxy
        ports:
        - name: http
          containerPort: 80
        - name: https
          containerPort: 443
        - name: stat
          containerPort: 1936
        livenessProbe:
          httpGet:
            path: /healthz
            port: 10253
        env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
```

**HAproxy configMap**
```yaml
    apiVersion: v1
    data: |
      ssl-redirect: true
    kind: ConfigMap
    metadata:
      name: ingress-controller-leader-haproxy
      namespace: ingress-controller
```

I tried to put annotation in my Ingress but it seems to be ignored too:
**Here is an example of my Ingress Rule**
```yaml
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    ingress.kubernetes.io/ssl-redirect: "true"
    kubernetes.io/ingress.class: haproxy
    kubernetes.io/ingress.rewrite-to-https: "true"
  labels:
    cattle.io/creator: norman
  name: grafana
  namespace: prometheus-grafana
spec:
  rules:
  - host: xxxxx.com
    http:
      paths:
      - backend:
          serviceName: prometheus-grafana
          servicePort: 80
```

Thanks for your Help
