### ISSUE TITLE
No Downtime Deployment : Need Help

### ISSUE THREAD

**Issue by dcowden** [jcmoraisjr/haproxy-ingress#303]
I'm trying to get a very basic  'no downtime' deployment working, and I'm not getting the results i expect. I could use some help, because I'm sure i'm missing a relatively simple configuration detail.

**TL;DR**
I have haproxy-ingress in front of a very basic nginx-deployment, and then i update it using a rolling update, while running fortio to generate load

**Expected Result**: all responses are HTTP/200, and all are fast.

   **Actual Result Part 1** without -dynamic scaling and --reload-strategy=reuse, clients see 503 errors 

   **Actual Result Part 2** WITH dynamic_scaling and --reload-strategy=reuse,   all responses are HTTP/200, but a decent fraction always take as long as the timeout-connect setting?

**More Details**
I'm using v0.7-beta.7.

I did a number of tests, and finally narrowed the behavior down to timeout_connect in the configmap by process of elimnation.  The client always receives long ( but successful ) responses just over the timeout_connect value.  In the below example,  the haproxy configmap looks (in part) like:

```
kind: ConfigMap
  timeout-connect: 8s
  timeout-http-request: 8s
  timeout-keep-alive: 1m
  timeout-queue: 5s
```
I used 8 seconds so there's no confusiong with 5 second TCP retransmissions.  Here are fortio results,captured while doing a rolling update ( some irrelevant stuff removed:)
```
dcowden@ubuntu:~/gitwork/ingress-503-combat$ fortio load -H "Host: ingress-test.ecom.dev.colinx.com" -c 8 -qps 100 -k -a -t 60s  --stdclient  -timeout 250s https://172.25.19.33/
Fortio 1.3.1 running at 100 queries per second, 2->2 procs, for 1m0s: https://172.25.19.33/
15:51:31 I httprunner.go:82> Starting http test for https://172.25.19.33/ with 8 threads at 100.0 qps
Starting at 100 qps with 8 thread(s) [gomax 2] for 1m0s : 750 calls each (total 6000)
15:52:38 W periodic.go:487> T000 warning only did 627 out of 750 calls before reaching 1m0s
... warnings like this...
....
WARNING 96.20% of sleep were falling behind
Aggregated Function Time : count 4810 avg 0.10967379 +/- 0.4746 min 0.02131236 max 8.898015937 sum 527.530918
# range, mid point, percentile, count
>= 0.0213124 <= 0.025 , 0.0231562 , 19.48, 937
> 0.025 <= 0.03 , 0.0275 , 22.49, 145
> 0.03 <= 0.035 , 0.0325 , 23.18, 33
> 0.035 <= 0.04 , 0.0375 , 23.56, 18
> 0.045 <= 0.05 , 0.0475 , 23.64, 4
> 0.05 <= 0.06 , 0.055 , 24.55, 44
> 0.06 <= 0.07 , 0.065 , 25.11, 27
> 0.07 <= 0.08 , 0.075 , 43.18, 869
> 0.08 <= 0.09 , 0.085 , 45.43, 108
> 0.09 <= 0.1 , 0.095 , 81.37, 1729
> 0.1 <= 0.12 , 0.11 , 95.70, 689
> 0.16 <= 0.18 , 0.17 , 96.01, 15
> 0.18 <= 0.2 , 0.19 , 97.46, 70
> 0.2 <= 0.25 , 0.225 , 98.21, 36
> 0.25 <= 0.3 , 0.275 , 98.92, 34
> 0.3 <= 0.35 , 0.325 , 99.27, 17
> 0.35 <= 0.4 , 0.375 , 99.38, 5
> 0.45 <= 0.5 , 0.475 , 99.48, 5
> 0.5 <= 0.6 , 0.55 , 99.65, 8
> 1 <= 2 , 1.5 , 99.67, 1
> 7.5 <= 8.89802 , 8.19901 , 100.00, 16  <==== NOTE THE ODDLY SPECIFIC 8 SECONDS
# target 50% 0.0912724
# target 75% 0.0982273
# target 90% 0.112046
# target 99% 0.311471
# target 99.9% 8.47774
Sockets used: 0 (for perfect keepalive, would be 8)
Code 200 : 4810 (100.0 %)
Response Header Sizes : count 4810 avg 0 +/- 0 min 0 max 0 sum 0
Response Body/Total Sizes : count 4810 avg 612 +/- 0 min 612 max 612 sum 2943720
All done 4810 calls (plus 8 warmup) 109.674 ms avg, 71.4 qps

```

I can replicate the same situation with other values of timeout_connect-- the larger it is, the larger the client responses are for the (presumed) inflight requests

Does anyone have an idea what's going on here?

**ingress controller daemon set:**
```
apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  labels:
    name: ingress-lb
  name: ingress-lb
  namespace: ops
spec:
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      run: haproxy-ingress
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: haproxy-ingress
    spec:
      containers:
      - image: jumanjiman/rsyslog
        imagePullPolicy: Always
        name: access-log
        ports:
        - containerPort: 514
          hostPort: 514
          name: udp
          protocol: UDP
        resources:
          limits:
            cpu: 50m
            memory: 50Mi
          requests:
            cpu: 50m
            memory: 50Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      - args:
        - --default-backend-service=$(POD_NAMESPACE)/default-http-backend
        - --allow-cross-namespace
        - --configmap=$(POD_NAMESPACE)/haproxy-ingress
        - --reload-strategy=reusesocket
        - --sort-backends
        - --v=3
        env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.name
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        image: quay.io/jcmoraisjr/haproxy-ingress:v0.7-beta.7
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /healthz
            port: 80
            scheme: HTTP
          initialDelaySeconds: 10
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        name: haproxy-ingress
        ports:
        - containerPort: 80
          hostPort: 80
          name: http
          protocol: TCP
        - containerPort: 443
          hostPort: 443
          name: https
          protocol: TCP
        - containerPort: 1936
          hostPort: 1936
          name: stat
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /healthz
            port: 80
            scheme: HTTP
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        resources:
          limits:
            cpu: 50m
            memory: 100Mi
          requests:
            cpu: 50m
            memory: 100Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      hostNetwork: true
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: nginx-ingress-serviceaccount
      serviceAccountName: nginx-ingress-serviceaccount
      terminationGracePeriodSeconds: 30
  templateGeneration: 55
  updateStrategy:
    rollingUpdate:
      maxUnavailable: 1
    type: RollingUpdate
status:
  currentNumberScheduled: 6
  desiredNumberScheduled: 6
  numberAvailable: 6
  numberMisscheduled: 0
  numberReady: 6
  observedGeneration: 55
  updatedNumberScheduled: 6

```
**configmap:**
```
apiVersion: v1
data:
  config-frontend: |
    capture request header X-Forwarded-For len 20
    capture request header Clx-Event-Id len 36
  dynamic-scaling: "true"
  forwardfor: ifmissing
  hsts: "true"
  http-log-format: ci=%ci,cp=%cp,b=%b,s=%s,H=%H,si=%si,sp=%sp,sslc=%sslc,HM=%HM,HU=%HU,Tw=%Tw,Tc=%Tc,TR=%TR,Tr=%Tr,Ta=%Ta,Th=%Th,Ti=%Ti,Tt=%Tt,B=%B,ST=%ST,ts=%ts,hr=%hr,CC=%CC,r=%r
  proxy-body-size: 200m
  ssl-redirect: "false"
  syslog-endpoint: localhost:514
  timeout-client: 50s
  timeout-connect: 8s
  timeout-http-request: 8s
  timeout-keep-alive: 1m
  timeout-queue: 5s
  timeout-server: 50s
  timeout-server-fin: 50s
  use-host-on-https: "true"
  use-proxy-protcol: "true"
kind: ConfigMap
```

**deployment:**
```
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: ingress-test
  labels:
    app: ingress-test
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 2        # how many pods we can add at a time
      maxUnavailable: 0  # maxUnavailable define how many pods can be unavailable    
  template:
    metadata:
      labels:
        app: ingress-test
    spec:
      serviceAccount: colinx
      containers:
        - name: ingress-test
          image: nginx:1.15.8
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 80
          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 11
            timeoutSeconds: 6
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 13
            timeoutSeconds: 6
          lifecycle:
            preStop:
              exec:
                command:
                  - "sh"
                  - "-c"
                  - >
                    sleep 20
                    /usr/sbin/nginx -s quit  
```
**ingress:**
```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ingress-test
  labels:
    app: ingress-test
  annotations:
    ingress.kubernetes.io/hsts: "true"
    ingress.kubernetes.io/ssl-redirect: "true"
    ingress.kubernetes.io/config-backend: |
       compression algo gzip
       compression type text/html text/plain text/css application/javascript
spec:
  tls:
    - secretName: cluster-cert
      hosts:
      - ingress-test.ecom.dev.colinx.com
  rules:
  - host: ingress-test.ecom.dev.colinx.com
    http:
      paths:
      - backend:
          serviceName: ingress-test
          servicePort: 80
        path: /
```

**Comment by dcowden** [comment]
For the benefit of those who come later: The ingress controller works just fine.

My problem was that this in fact does not work:

```
         lifecycle:
            preStop:
              exec:
                command:
                  - "sh"
                  - "-c"
                  - >
                    sleep 20
                    /usr/sbin/nginx -s quit
```

It silently fails and does not run the sleep command. Replacing it with this works as expected:

```
          lifecycle:
            preStop:
              exec:
                command: ["sh","-c","sleep 30"]   
```
