### ISSUE TITLE
Simultaneous work with two ports at the same backend

### ISSUE THREAD

**Issue by AlexProfi** [jcmoraisjr/haproxy-ingress#305]
Is it possible to work on the different ports on backend (nginx) with one ingress
Something like this
```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    ingress.kubernetes.io/ssl-passthrough: "true"
    kubernetes.io/ingress.class: "haproxy"
    ingress.kubernetes.io/maxconn-server: "65536"
  name: cpronginx-ingress
  namespace: default
spec:
  rules:
  - host: utm.com
    http:
      paths:
      - path: /
        backend:
          serviceName: cpronginx-svc
          servicePort: 443
      - path: /loaderio-321189fcfa8621a/
        backend:
          serviceName: cpronginx-svc
          servicePort: 80
```
If I use only nginx (for test with host network) Everything works fine
If haproxy is front and nginx is backend it doen't work
Is it possible?

**Comment by AlexProfi** [comment]
I get 302 redirect always even if I switch ssl-redirect: "false"

**Comment by AlexProfi** [comment]
It seems that it doesn't work in 0.7? but works in 0.6
In 0.6 I can connect through plain http
In 0.7 there is autoredirect to https

**Comment by jcmoraisjr** [comment]
Hi, v0.7 has [ingress.kubernetes.io/ssl-passthrough-http-port](https://github.com/jcmoraisjr/haproxy-ingress#ssl-passthrough) annotation which should be of some help.

Your ingress object should be something like this:

```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    ingress.kubernetes.io/ssl-passthrough: "true"
    ingress.kubernetes.io/ssl-passthrough-http-port: "80"
    kubernetes.io/ingress.class: "haproxy"
    ingress.kubernetes.io/maxconn-server: "65536"
  name: cpronginx-ingress
  namespace: default
spec:
  rules:
  - host: utm.com
    http:
      paths:
      - path: /
        backend:
          serviceName: cpronginx-svc
          servicePort: 443
```
