### ISSUE TITLE
get real client ip with host network option

### ISSUE THREAD

**Issue by AlexProfi** [jcmoraisjr/haproxy-ingress#310]
I saw this issue
https://github.com/jcmoraisjr/haproxy-ingress/issues/153
 I get same issue my x-forwarded-for is blank
that is my haproxy config

```
apiVersion: v1
kind: Namespace
metadata:
  name: ingress-controller
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ingress-controller
  namespace: ingress-controller
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: ingress-controller
rules:
  - apiGroups:
      - ""
    resources:
      - configmaps
      - endpoints
      - nodes
      - pods
      - secrets
    verbs:
      - list
      - watch
  - apiGroups:
      - ""
    resources:
      - nodes
    verbs:
      - get
  - apiGroups:
      - ""
    resources:
      - services
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - "extensions"
    resources:
      - ingresses
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - ""
    resources:
      - events
    verbs:
      - create
      - patch
  - apiGroups:
      - "extensions"
    resources:
      - ingresses/status
    verbs:
      - update
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: Role
metadata:
  name: ingress-controller
  namespace: ingress-controller
rules:
  - apiGroups:
      - ""
    resources:
      - configmaps
      - pods
      - secrets
      - namespaces
    verbs:
      - get
  - apiGroups:
      - ""
    resources:
      - configmaps
    verbs:
      - get
      - update
  - apiGroups:
      - ""
    resources:
      - configmaps
    verbs:
      - create
  - apiGroups:
      - ""
    resources:
      - endpoints
    verbs:
      - get
      - create
      - update
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: ingress-controller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: ingress-controller
subjects:
  - kind: ServiceAccount
    name: ingress-controller
    namespace: ingress-controller
  - apiGroup: rbac.authorization.k8s.io
    kind: User
    name: ingress-controller
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  name: ingress-controller
  namespace: ingress-controller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: ingress-controller
subjects:
  - kind: ServiceAccount
    name: ingress-controller
    namespace: ingress-controller
  - apiGroup: rbac.authorization.k8s.io
    kind: User
    name: ingress-controller
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    run: ingress-default-backend
  name: ingress-default-backend
  namespace: ingress-controller
spec:
  replicas: 2
  selector:
    matchLabels:
      run: ingress-default-backend
  template:
    metadata:
      labels:
        run: ingress-default-backend
    spec:
      containers:
      - name: ingress-default-backend
        image: gcr.io/google_containers/defaultbackend:1.0
        ports:
        - containerPort: 8080
        resources:
          limits:
            cpu: 100m
            memory: 200Mi
          requests:
            cpu: 100m
            memory: 200Mi
---
apiVersion: v1
kind: Service
metadata:
  name: ingress-default-backend
  namespace: ingress-controller
spec:
  ports:
  - port: 8080
  selector:
    run: ingress-default-backend
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: haproxy-ingress
  namespace: ingress-controller
data:
#Save real client IP
  forwardfor: "ifmissing"
  ssl-redirect: "false"
  syslog-endpoint: "localhost:514"
  proxy-body-size: "100m"
  timeout-connect: "30s"
  timeout-client: "300s"
  timeout-http-request: "300s"
  timeout-keep-alive: "2m"
  timeout-queue: "300s"
  timeout-stop: "300s"
  backend-check-interval: "30s"
  maxconn-server: "64000"
  balance-algorithm: roundrobin
  nbproc: "4"
  nbthread: "4"
  log-format: tcp-log-format

  config-frontend: |
    option dontlog-normal

---
apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  labels:
    run: haproxy-ingress
  name: haproxy-ingress
  namespace: ingress-controller
  annotations:
     configmap.reloader.stakater.com/reload: "haproxy-ingress"
spec:
  updateStrategy:
    type: RollingUpdate
  selector:
    matchLabels:
      run: haproxy-ingress
  template:
    metadata:
      labels:
        run: haproxy-ingress
    spec:
      hostNetwork: true
      nodeSelector:
        role: edge-router
      serviceAccountName: ingress-controller
      containers:
      - name: haproxy-ingress
        #image: quay.io/jcmoraisjr/haproxy-ingress:canary
        image: quay.io/jcmoraisjr/haproxy-ingress:v0.7-beta.7
        args:
        - --default-backend-service=$(POD_NAMESPACE)/ingress-default-backend
        - --default-ssl-certificate=default/tls-secret
        - --configmap=$(POD_NAMESPACE)/haproxy-ingress
        - --sort-backends
        ports:
        - name: http
          containerPort: 80
        - name: https
          containerPort: 443
        - name: stat
          containerPort: 1936
        env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
      - name: access-log
        image: appropriate/nc
        ports:
        - name: udp
          containerPort: 514
          protocol: UDP
        args: ["-ul","514"]
#        For send stats to prometheus
      - name: prometheus-exporter
        image: quay.io/prometheus/haproxy-exporter:v0.9.0
        args:
         - --haproxy.scrape-uri=http://127.0.0.1:1936/;csv
        ports:
          - name: prom-metrics
            containerPort: 9101


```
I use nginx as backends for haproxy
this is description of haproxy-ingress container 

 kubectl exec -it  haproxy-ingress-6cms4 -n ingress-controller --container haproxy-ingress -- ifconfig

```
flannel.1 Link encap:Ethernet  HWaddr AA:F4:8D:EF:5A:CD  
          inet addr:10.244.5.0  Bcast:0.0.0.0  Mask:255.255.255.255
          inet6 addr: fe80::a8f4:8dff:feef:5acd/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1450  Metric:1
          RX packets:2936 errors:0 dropped:0 overruns:0 frame:0
          TX packets:5220 errors:0 dropped:8 overruns:0 carrier:0
          collisions:0 txqueuelen:0 
          RX bytes:407273 (397.7 KiB)  TX bytes:461962 (451.1 KiB)
```
this is my ingress config

```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    ingress.kubernetes.io/ssl-passthrough: "true"
    kubernetes.io/ingress.class: "haproxy"
    ingress.kubernetes.io/maxconn-server: "65536"
    ingress.kubernetes.io/forwardfor: "ifmissing"
  name: cpronginx-ingress
  namespace: default
spec:
  rules:
  - host: test.ru
    http:
      paths:
      - path: /
        backend:
          serviceName: nginx-svc
          servicePort: 443

```
this is service config for connect to nginx

```
apiVersion: v1
kind: Service
metadata:
  name: cpronginx-svc
  namespace: default
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 80
      name: http
    - port: 443
      targetPort: 443
      protocol: TCP
      name: https
  selector:
    app: cpronginx
```

and this is my nginx conf ( part)
http{
 log_format haproxy_log 'ProxyIP: $remote_addr - ClientIP: $http_x_forwarded_for - $remote_user [$time_local] ' '"$request" $status $body_bytes_sent "$http_referer" ' '"$http_user_agent"'
server{
real_ip_header X-Forwarded-For;
          real_ip_recursive on;
 access_log /var/log/nginx/haproxy.log haproxy_log;

and in nginx log i get
ProxyIP: 10.244.5.0 - ClientIP: - - - [06/Mar/2019:12:46:43 +0000] "GET /access?size=blank HTTP/1.1" 200 130 "-" "curl/7.59.0"access_logoff
 clientIp is blank
how to fix this?

**Comment by jcmoraisjr** [comment]
Hi, when using `ssl-passthrough` haproxy uses tcp mode and cannot change any header of your request, including `X-Forwarded-For`. [proxy-protocol](https://github.com/jcmoraisjr/haproxy-ingress#proxy-protocol) annotation might help here. You'll need to configure nginx to accept the proxy protocol as well.

**Comment by AlexProfi** [comment]
Thanks. It works. I wrote this configs
```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    ingress.kubernetes.io/ssl-passthrough: "true"
    ingress.kubernetes.io/use-proxy-protocol: "true"
    ingress.kubernetes.io/proxy-protocol: "v2"
    kubernetes.io/ingress.class: "haproxy"
```
and in my nginx backends i add this lines to server
```
listen 443 ssl proxy_protocol;
           # HAproxy local IP in kubernetes
          set_real_ip_from 10.244.0.0/16;
          real_ip_header proxy_protocol;
          real_ip_recursive on;
```
