### ISSUE TITLE
ssl-redirect and basic auth order

### ISSUE THREAD

**Issue by m4rcu5** [jcmoraisjr/haproxy-ingress#340]
Hi,

If you use the basic auth annotation and the ssl-redirect one, it seems the authentication is applied on the HTTP (non-tls) endpoint before the redirect. Causing accidental transmission of cleartext login credentials.

It would be nice, if the HTTP endpoint would redirect only, and apply authentication in the TLS endpoint.

Example resource:
```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    ingress.kubernetes.io/auth-realm: Kubernetes Dashboard
    ingress.kubernetes.io/auth-secret: htpw-kubernetes-dashboard
    ingress.kubernetes.io/auth-type: basic
    ingress.kubernetes.io/ssl-redirect: "true"
  name: kubernetes-dashboard
  namespace: kube-system
spec:
  rules:
  - host: foo.bar
    http:
      paths:
      - backend:
          serviceName: kubernetes-dashboard
          servicePort: 443
        path: /
  tls:
  - hosts:
    - foo.bar
    secretName: foo.bar-tls
```
