### ISSUE TITLE
drain-support not working as expected

### ISSUE THREAD

**Issue by irizzant** [jcmoraisjr/haproxy-ingress#344]
Hello
I'm using Wildfly to deploy a web application in jsf and I'm trying to perform a rolling update to it.
I read you support `drain-support` option which allows existing sticky sessions to connect to a terminating pod.
Consequently I have the following ingress defined:
````yaml
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    ingress.kubernetes.io/session-cookie-name: JSESSIONID
    ingress.kubernetes.io/session-cookie-strategy: prefix
    ingress.kubernetes.io/ssl-redirect: "false"
    kubernetes.io/ingress.class: haproxy
    nginx.ingress.kubernetes.io/affinity: cookie
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
  labels:
    name: glf-ingress
  name: glf-ingress
  namespace: jboss
spec:
  rules:
  - host: glf.192.168.99.100.nip.io
    http:
      paths:
      - backend:
          serviceName: glf
          servicePort: web
        path: /

````
And the following `ConfigMap`:
````yaml
apiVersion: v1
data:
  drain-support: "true"
kind: ConfigMap
metadata:
  creationTimestamp: "2019-05-24T15:19:05Z"
  name: haproxy-ingress
  namespace: ingress-controller
  resourceVersion: "837558"
  selfLink: /api/v1/namespaces/ingress-controller/configmaps/haproxy-ingress
  uid: 44f6593a-7e37-11e9-a451-0800272a18ec
````
And I set my `preStop` hook to call an API deployed in Wildfly itself which starts a countdown to let the users finish their work before being kicked off to the new version of the app.
The `preStop` also `sleep`'s for a pre-defined amount of time.

What happens here is that even if I use the `drain-support` as soon as the pod gets in `Terminating` status its endpoint is removed and all the following requests do not reach the pod anymore.
Maybe I got it wrong, but I thought that traffic crossing the Ingress controller would have been able to reach the pods through their IP even though their endpoint is removed.
