### ISSUE TITLE
annotation not working config-frontend

### ISSUE THREAD

**Issue by abilashksv** [jcmoraisjr/haproxy-ingress#349]
hi i am trying to load balance between three different  apps based on header msg.
i tried to set in the following configmap but i got the below error

```
config-frontend: |
      acl is_backend-1 hdr(X-Message-Type) backend-1
      acl is_backend-2 hdr(X-Message-Type) backend-2
      acl is_backend-3 hdr(X-Message-Type) backend-3
      use_backend python-app1 if is_backend-1
      use_backend python-app2 if is_backend-2
      use_backend python-app3 if is_backend-3
```

> W0610 10:30:38.698471       6 controller.go:283] Error validating config file:
[WARNING] 160/103038 (29) : parsing [/etc/haproxy/haproxy.cfg:71] : a 'http-request' rule placed after a 'use_backend' rule will still be processed before.
[WARNING] 160/103038 (29) : parsing [/etc/haproxy/haproxy.cfg:72] : a 'http-request' rule placed after a 'use_backend' rule will still be processed before.
[WARNING] 160/103038 (29) : parsing [/etc/haproxy/haproxy.cfg:73] : a 'http-request' rule placed after a 'use_backend' rule will still be processed before.
[WARNING] 160/103038 (29) : parsing [/etc/haproxy/haproxy.cfg:74] : a 'http-request' rule placed after a 'use_backend' rule will still be processed before.
[WARNING] 160/103038 (29) : parsing [/etc/haproxy/haproxy.cfg:75] : a 'http-request' rule placed after a 'use_backend' rule will still be processed before.
[WARNING] 160/103038 (29) : parsing [/etc/haproxy/haproxy.cfg:76] : a 'http-request' rule placed after a 'use_backend' rule will still be processed before.
[WARNING] 160/103038 (29) : parsing [/etc/haproxy/haproxy.cfg:77] : a 'http-request' rule placed after a 'use_backend' rule will still be processed before.
[WARNING] 160/103038 (29) : parsing [/etc/haproxy/haproxy.cfg:78] : a 'http-request' rule placed after a 'use_backend' rule will still be processed before.
[WARNING] 160/103038 (29) : parsing [/etc/haproxy/haproxy.cfg:79] : a 'http-request' rule placed after a 'use_backend' rule will still be processed before.
[WARNING] 160/103038 (29) : parsing [/etc/haproxy/haproxy.cfg:100] : a 'http-request' rule placed after a 'use_backend' rule will still be processed before.
[WARNING] 160/103038 (29) : parsing [/etc/haproxy/haproxy.cfg:101] : a 'http-request' rule placed after a 'use_backend' rule will still be processed before.
[WARNING] 160/103038 (29) : parsing [/etc/haproxy/haproxy.cfg:102] : a 'http-request' rule placed after a 'use_backend' rule will still be processed before.
[WARNING] 160/103038 (29) : parsing [/etc/haproxy/haproxy.cfg:103] : a 'http-request' rule placed after a 'use_backend' rule will still be processed before.
[WARNING] 160/103038 (29) : parsing [/etc/haproxy/haproxy.cfg:104] : a 'http-request' rule placed after a 'use_backend' rule will still be processed before.
[ALERT] 160/103038 (29) : Proxy 'httpfront-shared-frontend': unable to find required use_backend: 'python-app1'.
[ALERT] 160/103038 (29) : Proxy 'httpfront-shared-frontend': unable to find required use_backend: 'python-app2'.
[ALERT] 160/103038 (29) : Proxy 'httpfront-shared-frontend': unable to find required use_backend: 'python-app3'.
[ALERT] 160/103038 (29) : Proxy 'httpfront-default-backend': unable to find required use_backend: 'python-app1'.
[ALERT] 160/103038 (29) : Proxy 'httpfront-default-backend': unable to find required use_backend: 'python-app2'.
[ALERT] 160/103038 (29) : Proxy 'httpfront-default-backend': unable to find required use_backend: 'python-app3'.
[ALERT] 160/103038 (29) : Fatal errors found in configuration.
E0610 10:30:38.698533       6 controller.go:337] unexpected failure restarting the backend:
exit status 1
W0610 10:30:38.698557       6 queue.go:113] requeuing sock-shop/user, err exit status 1
I0610 10:30:40.589190       6 controller.go:332] backend reload required
W0610 10:30:40.671672       6 controller.go:283] Error validating config file:

it will be great if we have option in annotations to set config-frontend as below.

```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: python-app-ingress
  annotations:
    kubernetes.io/ingress.class: "haproxy"
    ingress.kubernetes.io/config-frontend: |
      default_backend www_example_com
      acl is_backend-1 hdr(X-Message-Type) backend-1
      acl is_backend-2 hdr(X-Message-Type) backend-2
      acl is_backend-3 hdr(X-Message-Type) backend-3
      use_backend python-app1 if is_backend-1
      use_backend python-app2 if is_backend-2
      use_backend python-app3 if is_backend-3
spec:
   - host: "python-app.com"
    http:
      paths:
      - path: /user
        backend:
          serviceName: python-app1
          servicePort: 8080
        backend:
          serviceName: python-app2
          servicePort: 8080
        backend:
          serviceName: python-app3
          servicePort: 8080
```

Please let me know if there is any other way to achieve this.
