### ISSUE TITLE
[Question] How to routing based on path

### ISSUE THREAD

**Issue by xuanzhaopeng** [jcmoraisjr/haproxy-ingress#359]
Thanks a lot for providing this awesome ingress plugin.

Context:
I have ClusterIP service:  testService(in namespace test)
I have Pod testPod(in namespace test,  which exposed by testService)
I also have default backend of namespace ingress-controller

Question is:
I want to route */test(default host) to testService, and */other to other future service. 

May I ask how could we config this routing based on path? 

Thanks

**Comment by speedst3r** [comment]
This is more a Kubernetes question than HAproxy specifically.

https://kubernetes.io/docs/concepts/services-networking/ingress/

You want a "simple fanout" type, where different paths have different backends.

**Comment by xuanzhaopeng** [comment]
Hey @speedst3r , thanks a lot for your reply

let's say the topic you provided "simple fanout"

```
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: simple-fanout-example
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: foo.bar.com
    http:
      paths:
      - path: /foo
        backend:
          serviceName: service1
          servicePort: 4200
      - path: /bar
        backend:
          serviceName: service2
          servicePort: 8080
```
So if I don't have any host name, only an IP address, so I leave host as blank, then in Ingress, it shows the host as "*"

However in this case with Haproxy-ingress, I get 302  code by curl <ip address of the node which ingress-controller pod exposed> , I event cannot get 404 from default-backend. 

Do you have any idea?
