### ISSUE TITLE
redirection not working from  / to /index for an application when I am using haproxy ingress rules

### ISSUE THREAD

**Issue by NamrataKokate** [jcmoraisjr/haproxy-ingress#365]
I am using HAProxy Ingress Controller and have rules set for /index and /app.

I want any traffic on / to be redirected to /index.

I Have 4 deployments via haproxy, default-backend (on / gives 404 and /healthz gives 200), index and app.
Using below ingress rules, when I do curl on https://example.com/ it gives me error as **default backend - 404%**

Index-ingress.yaml:

```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: index-haproxy
  namespace: haproxy
  annotations:
    kubernetes.io/ingress.class: "haproxy"
    ingress.kubernetes.io/ssl-redirect: "true"
    ingress.kubernetes.io/session-cookie-name: "index"
    ingress.kubernetes.io/affinity: "cookie"
    ingress.kubernetes.io/app-root: /index
spec:
  rules:
  - host: example.com
    http:
      paths:
       - path: /index
         backend:
          serviceName: index-backened
          servicePort: 443 
```

-----------------------
app-ingress.yaml 
-----------------------
```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: app-haproxy
  namespace: haproxy
  annotations:
    kubernetes.io/ingress.class: "haproxy"
    ingress.kubernetes.io/secure-backends: "true"
    ingress.kubernetes.io/ssl-redirect: "true"

spec:
  rules:
  - host: example.com
    http:
      paths:       
        - path: /app/
          backend:
           serviceName: application
           servicePort: 443
```
