### ISSUE TITLE
Annotation ingress.kubernetes.io/ssl-redirect does not work per ingress

### ISSUE THREAD

**Issue by btnguyen2k** [jcmoraisjr/haproxy-ingress#379]
I have an ingress with `ingress.kubernetes.io/ssl-redirect: "true"` and global `ssl-redirect: "OFF"`
```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: foobar
  annotations:
    ingress.kubernetes.io/ssl-redirect: "true"
spec:
  tls:
    - hosts:
        - "foo.mydomain.com"
      secretName: foobar
  rules:
    - host: "foo.mydomai.com"
      http:
        paths:
          - path:
            backend:
              serviceName: foobar
              servicePort: foobar
```

Everything is working fine except that `ingress.kubernetes.io/ssl-redirect` does not work on my ingress.

Regards,
Thanh Nguyen
