### ISSUE TITLE
websocket support example?

### ISSUE THREAD

**Issue by cynial** [jcmoraisjr/haproxy-ingress#404]
Below is how nginx-ingress add websocket support

How can I implement it with haproxy-ingress ? 
 
```
# https://github.com/nginxinc/kubernetes-ingress/tree/master/examples/websocket

apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: cafe-ingress
  annotations:
    nginx.org/websocket-services: "ws-svc"
spec:
  rules:
  - host: cafe.example.com
    http:
      paths:
      - path: /tea
        backend:
          serviceName: tea-svc
          servicePort: 80
      - path: /coffee
        backend:
          serviceName: coffee-svc
          servicePort: 80
      - path: /ws
        backend:
          serviceName: ws-svc
          servicePort: 8008
```
