### ISSUE TITLE
Logs to stdout with v0.9-snapshot.1 version

### ISSUE THREAD

**Issue by dtrinf** [jcmoraisjr/haproxy-ingress#408]
Hi,

I'm trying to use the new v0.9-snapshot.1 version to show all the requests into stdout.
With the above configmap, I've been able to show some logs, but not the user requests.

```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: haproxy-ingress
  namespace: ingress
  labels:
    service: haproxy
data:
  syslog-endpoint: stdout
  max-connections: "16000"
  config-global: |
    log stdout format raw  local0  info
  config-defaults: |
    log     global
    mode    http
    option  httplog
  config-frontend: |
    log stdout format raw  local0  debug
```

Anyone know what I'm doing wrong, or if there is any special configuration to show the all requests to stdout?
