### ISSUE TITLE
Multiple non existent servers in backend

### ISSUE THREAD

**Issue by dtrinf** [jcmoraisjr/haproxy-ingress#409]
Hi,

I'm, using the version v0.9-snapshot.1, and I've realized that each backend has seven servers, even if there is only one alive.

```code
backend default_XXXXXX-web_8080
    mode http
    balance roundrobin
    http-request set-header X-Original-Forwarded-For %[hdr(x-forwarded-for)] if { hdr(x-forwarded-for) -m found }
    http-request del-header x-forwarded-for
    option forwardfor
    server srv001 10.2.3.24:8080 weight 1 check inter 2s
    server srv002 127.0.0.1:1023 disabled weight 0 check inter 2s
    server srv003 127.0.0.1:1023 disabled weight 0 check inter 2s
    server srv004 127.0.0.1:1023 disabled weight 0 check inter 2s
    server srv005 127.0.0.1:1023 disabled weight 0 check inter 2s
    server srv006 127.0.0.1:1023 disabled weight 0 check inter 2s
    server srv007 127.0.0.1:1023 disabled weight 0 check inter 2s
```

Is there any way to avoid this?

Thanks

**Comment by jcmoraisjr** [comment]
Hi, see dynamic scaling docs.

Em qua, 9 de out de 2019 10:56, David Trigo Chávez <notifications@github.com>
escreveu:

**Comment by dtrinf** [comment]
Hi Joao,

Thanks for your comment, I've been able to show the Statistics with no extra backends.
I Attach the config in case it will help anyone.

```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: haproxy-configmap
data:
  dynamic-scaling: "false"
  backend-server-slots-increment: "1"
  slots-min-free: "0"
```

Regards,
David
