### ISSUE TITLE
Annotations for different paths are being treated as the same

### ISSUE THREAD

**Issue by GMartinez-Sisti** [jcmoraisjr/haproxy-ingress#426]
Hi,

I'm trying to do the following (redacted) with vbeta4:

```yaml
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ingress-global
  annotations:
    ingress.kubernetes.io/limit-connections: "5"
    ingress.kubernetes.io/limit-rps: "15"
spec:
  rules:
    - host: site.com
      http:
        paths:
          - path: /
            backend:
              serviceName: http
              servicePort: http
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ingress-login
  annotations:
    ingress.kubernetes.io/limit-connections: "2"
    ingress.kubernetes.io/limit-rps: "2"
spec:
  rules:
    - host: site.com
      http:
        paths:
          - path: /login
            backend:
              serviceName: http
              servicePort: http
```

However haproxy complains that:

```sh
annotation 'ingress.kubernetes.io/limit-connections' from ingress 'default/ingress-global' overrides the same annotation with distinct value from [ingress 'default/ingress-login']
```

This type of configuration worked with v0.7, but the new way the configuration is created places both of the ingresses in the same backend. One way to go around this would be to create a new service with a different name than `http` that would create a new different backend in the haproxy config for the `/login` path, but I would like to avoid having to create a new service every time I need different annotations.

Any suggestions?

Thanks
