### ISSUE TITLE
Modsecurity variables not working for v0.8-beta.4

### ISSUE THREAD

**Issue by GMartinez-Sisti** [jcmoraisjr/haproxy-ingress#428]
Hi,

I think I found a bug with modsecurity options.

If I define the following configurations in globals:
```yaml
  modsecurity-endpoints: 127.0.0.1:12345
  modsecurity-timeout-hello: 100ms
  modsecurity-timeout-idle: 60s
  modsecurity-timeout-processing: 1s
```

The following in haproxy config is created:
```ini
# # # # # # # # # # # # # # # # # # #
# #
#     ModSecurity Agent
#
backend spoe-modsecurity
    mode tcp
    timeout connect 5s
    timeout server  5s
    server modsec-spoa0 127.0.0.1:12345
```

Looks like the modsecurity options are not being parsed correctly.

Thanks
