### ISSUE TITLE
cross-namespace secret not working in 0.8-beta.4

### ISSUE THREAD

**Issue by primeroz** [jcmoraisjr/haproxy-ingress#429]
Hi, i started testing 0.8 on my setup , running it alongside 0.7 so i can compare configs and using the same class so they are consuming exactly the same ingress-resources

0.8 is started with `--allow-cross-namespace=true` CLI option

When creating an ingress with cross namespace secret though it seems to fail and in the logs i can see

`ingress.go:267] using default certificate due to an error reading secret '<INGRES_NAMESPACE>/<SECRET_NAMESPACE>/<SECRET_NAME>': secret <INGRES_NAMESPACE>/<SECRET_NAMESPACE>/<SECRET_NAME> was not found`

The ingress has 
```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    ingress.kubernetes.io/auth-tls-secret: <SECRET_NAMESPACE>/<SECRET_NAME>
  name: INGRESS
  namespace: <INGRESS_NAMESPACE>
...
...
spec:
...
  tls:
  - hosts:
    - <TLS_HOST>
    secretName: <SECRET_NAMESPACE>/<SECRET_NAME>
```
Not sure which of the two secret is causing this yet, will do some more testing. 

but it does look to me that is using the value of the secret as secret name without splitting on `/` for namespace / secret-name

The secret **does exist** and work as expected on 0.7.3
