### ISSUE TITLE
Wrong handling of path

### ISSUE THREAD

**Issue by Scukerman** [jcmoraisjr/haproxy-ingress#45]
```yaml
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: echoheaders
  annotations:
    kubernetes.io/ingress.class: haproxy
spec:
  tls:
  - hosts:
    - domain.com
    secretName: tls-domain-com
  rules:
  - host: domain.com
    http:
      paths:
      - path: /ws
        backend:
          serviceName: echoheaders
          servicePort: 80
```

I expect to get exact `/ws` path but not anything else starting with `/ws`.
