### ISSUE TITLE
how haproxy-ingress handle headless service & endpoints 

### ISSUE THREAD

**Issue by ailenli** [jcmoraisjr/haproxy-ingress#489]
Hi ,
recently , I do some things about headless service and haproxy-ingress  in k8s
1. use headless service without selector and deployment apache

>vim  service-deployment.yaml
```
apiVersion: v1
kind: Service
metadata:
   labels:
      app: apached
   name: http-svc
   namespace: haproxy-controller
spec:
   clusterIP: None
   ports:
   - name: web
     port: 9000
     targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
   name: apache-deployment
   namespace: haproxy-controller
   labels:
      app: apached
spec:
   replicas: 2
   selector:
      matchLabels:
         app: apached
   template:
      metadata:
         labels:
            app: apached
      spec:
         containers:
         - image: apache:v1.0
           imagePullPolicy: Never
           name: apached
           ports:
           - containerPort: 80
```

> kubectl get po  -n haproxy-controller -owide
apache-deployment-7f66c97b9b-qrvdk         1/1     Running   0          5s     100.88.195.46

2. because of headless service without selector , when get endpoints ,there is a error

> kubectl get ep http-svc -n haproxy-controller
Error from server (NotFound): endpoints "http-svc" not found

3. so I add endpoints to headless service manually
```
apiVersion: v1
kind: Endpoints
metadata:
  name: http-svc
  namespace: haproxy-controller
subsets:
  - addresses:
      - ip: 100.88.195.46
    ports:
      - port: 80

```
> kubectl get ep http-svc -n haproxy-controller
NAME       ENDPOINTS          AGE
http-svc   100.88.195.46:80   73s

4. apply ingress.yaml
```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: app
  namespace: haproxy-controller
  annotations:
     kubernetes.io/ingress.class: "haproxy"
spec:
  rules:
  - host: foo.bar
    http:
      paths:
      - path: /
        backend:
          serviceName: http-svc
          servicePort: 9000
```

5. get ingress-controller ip:port

> kubectl get svc haproxy-ingress -n haproxy-controller -oyaml
====
 ports:
  - name: port-1
    nodePort: 30234
    port: 80
    protocol: TCP
    targetPort: 80
  - name: port-2
====

now problem occured , 10.129.97.75 is hostIP
> curl -iL 10.129.97.75:30234 -H 'Host: foo.bar'
HTTP/1.0 503 Service Unavailable

6. enter ingress-controller pod , check haproxy.cfg, I dont find service endpoints ip port there
backend haproxy-controller_http-svc_80
```
    mode http
    balance roundrobin
    acl https-request ssl_fc
    http-request set-header X-Original-Forwarded-For %[hdr(x-forwarded-for)] if { hdr(x-forwarded-for) -m found }
    http-request del-header x-forwarded-for
    option forwardfor
    http-response set-header Strict-Transport-Security "max-age=15768000"
    server srv001 127.0.0.1:1023 disabled weight 1 check inter 2s
    server srv002 127.0.0.1:1023 disabled weight 1 check inter 2s
    server srv003 127.0.0.1:1023 disabled weight 1 check inter 2s
    server srv004 127.0.0.1:1023 disabled weight 1 check inter 2s
    server srv005 127.0.0.1:1023 disabled weight 1 check inter 2s
    server srv006 127.0.0.1:1023 disabled weight 1 check inter 2s
```

so I wonder why these scenarios fail 

best regards
