### ISSUE TITLE
Annotation support: rewrite-target

### ISSUE THREAD

**Issue by ausmith** [jcmoraisjr/haproxy-ingress#55]
[Kubernetes ingress controllers](https://github.com/kubernetes/ingress) supports the annotation [`ingress.kubernetes.io/rewrite-target`](https://github.com/kubernetes/ingress/blob/master/controllers/nginx/configuration.md#rewrite). This is a valuable annotation to support in microservice architectures. 

Example: I have 2 services, an API and a telemetry service, both on myapi.domain.com. The `path` setup in the kubernetes ingress definition for the API is `/api`, while `/telemetry` is used for the telemetry service. We then might re-use that same telemetry service with a different domain but for some reason the path has to be `/stats` instead of `/telemetry`. As such, the telemetry service has been coded to expect inbound traffic on the path `/` and the `rewrite-target` is used to overwrite `/telemetry` and `/stats` to `/`.

We believe (and are testing) that the resulting haproxy configuration should likely be something like:
```
reqrep ^([^\ :]*)\ /telemetry/(.*)     \1\ /\2  if { path_beg /telemetry }
use_backend out-telemetry-80 if { path_beg /telemetry }
```

We have already eliminated `regsub` from the running for this config as it does not seem to support capture groups (does not allow closing parentheses in the regex). Thoughts?

**Comment by ausmith** [comment]
The following rewrite target options are available in master as of #57 getting merged.

|rewrite target|ingress path|request path|output|
|-------------|-------------|-------------|------|
|/|/abc|/abc|/|
|/|/abc|/abc/|/|
|/|/abc|/abc/x|/x|
|/y|/abc|/abc|/y|
|/y|/abc|/abc/|/y/|
|/y|/abc|/abc/x|/y/x|
|/|/abc/|/abc|**404**|
|/|/abc/|/abc/|/|
|/|/abc/|/abc/x|/x|

That meets my business needs for this annotation as described in the original issue. @jcmoraisjr should we leave this issue open for handling annotations with a trailing slash or open a separate issue for that?

**Comment by jcmoraisjr** [comment]
No need to create a new one, this very issue is enough.

**Comment by elideveloper** [comment]
There is a problem if a requested path contains some repeated value. Rewrite target "/" just cuts it down double time. 
For instance: 
request is  "/person/person/find"
we need to leave "/person/find" but get just "/find"
the same with "/p/person/find" -> "/erson/find".
So, is it a valid behaviour and how to deal with it?
our config:
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: haproxy
  annotations:
    ingress.kubernetes.io/rewrite-target: "/"
    kubernetes.io/ingress.class: "haproxy"
spec:
  rules:
  - host: "domain"
    http:
      paths:
      - path: /person
        backend:
          serviceName: person
          servicePort: 9016

**Comment by ausmith** [comment]
@elideveloper interesting results, clearly not on the above matrix of test cases we verified. At present it does 2 `reqrep`s to appropriately handle cases with and without content following the path defined by the ingress config. https://github.com/jcmoraisjr/haproxy-ingress/blob/master/rootfs/etc/haproxy/template/haproxy.tmpl#L309-L310

So if you have an ingress path defined as `/person` and a request comes in for `/person` then the second `reqrep` triggers.

If you have an ingress path defined as `/person` and a request comes in for `/person/find` then the first `reqrep` triggers.

As such, I don't consider your scenario expected (either of them) so we probably need to test for those going forward. Up to @jcmoraisjr if that should be a separate bug issue or stay here?

**Comment by jcmoraisjr** [comment]
There is a pending improvement detailed on #57 which wasn't implemented yet, below is a ctrl+V. I've already a proposal to this and perhaps could fix this behavior. No need to create a new issue, I'll notify here as soon as the changes are pushed to master.

---

... [an] approach (not tested, just the idea):

`... {{ $location.Path }}(.*$)  \1\ {{ $rewriteTarget }}{{ if and (ne $rewriteTarget "/") (endsWith $location.Path "/")}}/{{ end }}\2  if...`

in order to:

* use only one `reqrep` (per frontend)
* change from _"unsupported trailing slash"_ to _"use the same pattern used in ingress path"_ - both ingress path and rewrite should, or should not, have the trailing slash

`endsWith` would be a new func to be implemented (template.go)

**Comment by jcmoraisjr** [comment]
@elideveloper Changed the approach on 7a86ac9 and perhaps fixed this issue.

@ausmith Let me know if I broke something.

Updating `snapshot` tag with this change within the next two days.

**Comment by elideveloper** [comment]
@jcmoraisjr, ok, thanks for fixing!

**Comment by ausmith** [comment]
@jcmoraisjr I'm sorry but I do not have the bandwidth to test this in the cluster I manage at work right now. I have managed to get prioritized some time this quarter to work on the ingress improvements discussed here and in #58, but I don't see that happening in November sadly. I will mention here when I get time to do that work.

**Comment by jcmoraisjr** [comment]
No problem, take your time. Please close this issue when you get the time to verify if everything is still working on your environment.

**Comment by jcmoraisjr** [comment]
Closing. Feel free to post here any issue regarding the rewrite annotation.

**Comment by NickMRamirez** [comment]
This is not working for me using the latest version. My ingress-controller is set up as follows:

```
---
  apiVersion: v1
  kind: Namespace
  metadata:
    name: ingress
---
  apiVersion: v1
  kind: ServiceAccount
  metadata:
    name: ingress-controller
    namespace: ingress
---
apiVersion: apps/v1
kind: Deployment 
metadata:
  name: ingress-default-backend-deployment 
  namespace: ingress
  labels:
    app: defaultserver
spec: 
  replicas: 1 
  selector: 
    matchLabels:
      app: defaultserver
  template: 
    metadata:
      labels:
        app: defaultserver
      namespace: ingress
    spec: 
      containers:
        - name: ingress-default-backend-pod 
          image: gcr.io/google_containers/defaultbackend:1.0 
          ports:
            - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: ingress-default-backend-service
  namespace: ingress
  labels:
    app: defaultserver
spec:
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
  selector:
    app: defaultserver

          

---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: haproxy-ingress
  name: haproxy-ingress
  namespace: ingress
spec:
  replicas: 1
  selector:
    matchLabels:
      run: haproxy-ingress
  template:
    metadata:
      labels:
        run: haproxy-ingress
      name: haproxy-ingress-pod
      namespace: ingress
    spec:
      serviceAccountName: ingress-controller
      containers:
      - name: haproxy-ingress
        image: quay.io/jcmoraisjr/haproxy-ingress
        args:
        - --default-backend-service=$(POD_NAMESPACE)/ingress-default-backend-service
        - --default-ssl-certificate=$(POD_NAMESPACE)/tls-secret
        - --configmap=$(POD_NAMESPACE)/haproxy-ingress
        ports:
        - name: http
          containerPort: 80
        - name: https
          containerPort: 443
        - name: stat
          containerPort: 1936
        env:
          - name: POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: POD_NAMESPACE
            value: ingress
---
  apiVersion: v1
  kind: Service
  metadata:
    name: haproxy-ingress-service
    namespace: ingress
    labels:
      run: haproxy-ingress
  spec:
    ports:
    - port: 80
      protocol: TCP
    type: NodePort
    selector:
      run: haproxy-ingress

---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: ingress-controller
rules:
  - apiGroups:
      - ""
    resources:
      - configmaps
      - endpoints
      - nodes
      - pods
      - secrets
    verbs:
      - list
      - watch
  - apiGroups:
      - ""
    resources:
      - nodes
    verbs:
      - get
  - apiGroups:
      - ""
    resources:
      - services
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - "extensions"
    resources:
      - ingresses
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - ""
    resources:
      - events
    verbs:
      - create
      - patch
  - apiGroups:
      - "extensions"
    resources:
      - ingresses/status
    verbs:
      - update
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: Role
metadata:
  name: ingress-controller
  namespace: ingress
rules:
  - apiGroups:
      - ""
    resources:
      - configmaps
      - pods
      - secrets
      - namespaces
    verbs:
      - get
  - apiGroups:
      - ""
    resources:
      - configmaps
    verbs:
      - get
      - update
  - apiGroups:
      - ""
    resources:
      - configmaps
    verbs:
      - create
  - apiGroups:
      - ""
    resources:
      - endpoints
    verbs:
      - get
      - create
      - update
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: ingress-controller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: ingress-controller
subjects:
  - kind: ServiceAccount
    name: ingress-controller
    namespace: ingress
  - apiGroup: rbac.authorization.k8s.io
    kind: User
    name: ingress-controller
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  name: ingress-controller
  namespace: ingress
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: ingress-controller
subjects:
  - kind: ServiceAccount
    name: ingress-controller
    namespace: ingress
  - apiGroup: rbac.authorization.k8s.io
    kind: User
    name: ingress-controller
```

I have a service:

```
---
apiVersion: apps/v1beta2
kind: Deployment 
metadata:
  name: nginx-deployment 
  namespace: ingress
  labels:
    app: nginx 
spec: 
  replicas: 1 
  selector: 
    matchLabels:
      app: nginx
  template: 
    metadata:
      labels:
        app: nginx
      namespace: ingress
    spec: 
      containers:
        - name: nginx 
          image: nginx:latest 
          ports:
            - containerPort: 80 
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  namespace: ingress
  labels:
    app: nginx
spec:
  ports:
  - port: 80
    protocol: TCP
  selector:
    app: nginx

```
And the ingress rule is as follows:

```
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: nginx-ingress
  namespace: ingress
  annotations:
    ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - http:
        paths:
          - path: /app
            backend:
              serviceName: nginx-service
              servicePort: 80
```

This always directs to the default service. If I use a path of `/` instead of `/app` for the ingress-rule, then it works.
