### ISSUE TITLE
Separate HA config for separate rules/backends

### ISSUE THREAD

**Issue by tleish** [jcmoraisjr/haproxy-ingress#594]
When haproxy-ingress contains multiple spec rules, can you configure different rules for each rule (backend)?

For example: 

```yaml
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: app
spec:
  rules:
    - host: foo.com
      http:
        paths:
          - path: /app
            backend:
              serviceName: http-svc
              servicePort: 8080
          - path: /
            backend:
              serviceName: ingress-default-backend
              servicePort: 8080
```

In the example configuration, how would you configure `maxconn-server` for `/app` (http-svc), but not for `/` (ingress-default-backend)?

**Comment by Unichron** [comment]
Maxconn-server has "backend" scope, you can configure it on the service resource. More specifically:

> Scope Backend: Defines configuration keys that binds to the service object, which is converted to a HAProxy backend after the configuration parsing. Configuration keys of the backend scope can be declared in the ConfigMap as a default value, in an ingress object, or in a service object. A conflict warning will be logged if the same backend configuration key with distinct values are declared in distict ingress objects but to the same service or HAProxy backend. A backend configuration key declared in a service object overwrites the same configuration in an ingress object without conflicting.

**Comment by tleish** [comment]
@Unichron - thank you for the response.  I've read through the HAProxy Ingress documentation, but I still do not understand how to assign a "backend" scope to a service resource.  And, would this be assigned to the service resource for the server or the service resource for the haproxy controller?

Are there any examples or tutorials for how to configure backend scope for something like this?

FYI: I'm fairly new to kubernetes and HAProxy, but I've configured an environment with multiple servers, so I have some knowledge.

**Comment by Unichron** [comment]
@tleish TLDR: put "ingress.kubernetes.io/maxconn-server" = "<value>" annotation on the service resource of http-svc

So there are 3 scopes. Global scope options you can configure in the configmap of haproxy-controller. Host scope options can be configured on the ingress resource of a service that haproxy-controller supposed to handle. Backend scope options can be configured on the service resource of a service that haproxy-controller supposed to handle. Optionally, you can give default values to host and backend scope options in the configmap of haproxy-controller. This is more like a convenience 
 to not repeat yourself in case you want the same options everywhere and you can still overwrite them one by one in the ingress and service resources.

**Comment by tleish** [comment]
@Unichron - Thank you for the help.

So implement `ingress.kubernetes.io/maxconn-server` with something like?

```yaml
apiVersion: v1
kind: Service
metadata:
  name: http-svc
  labels:
    run: http-svc
   annotations:
    ingress.kubernetes.io/maxconn-server: "6"
spec:
  ports:
  - port: 8080
    protocol: TCP
  selector:
    run: http-svc

---

apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: app
spec:
  rules:
    - host: foo.com
      http:
        paths:
          - path: /app
            backend:
              serviceName: http-svc
              servicePort: 8080
          - path: /
            backend:
              serviceName: ingress-default-backend
              servicePort: 8080
```

**Comment by jcmoraisjr** [comment]
> So implement ingress.kubernetes.io/maxconn-server with something like?

yup, that's it.

Note that, as another option, you can also break the configuration into two ingress objects: one of them configures `path: /` and the other `/app`, both using the same `host: foo.com`. This will allow you to use distinct annotations, haproxy ingress will merge all of them.

**Comment by tleish** [comment]
Thanks for the help.  I finally got this working.  Now, the last item I need to figure out is how to get this to play nicely with an AWS load balancer.  Reading through some of the other tickets, it sounds like this may or may not be supported at the moment.

**Comment by mrrandrade** [comment]
> Reading through some of the other tickets, it sounds like this may or may not be supported at the moment.

Hey there!

We have an operational AWS cluster with this project as its only Ingress.

Are you facing an specific problem or just want basic guidelines to run it on AWS?

---

In case its just basic guidelines, I'll drop the stuff that works for me to save time.

* Running this deployment: https://github.com/jcmoraisjr/haproxy-ingress/blob/master/examples/deployment/haproxy-ingress.yaml, but with following changes to arguments. I'm guessing the only relevant parts for this specific deployment is publish-service and update-status:

```
      - args:
        - --v=2
        - --acme-server
        - --acme-track-tls-annotation
        - --buckets-response-time=0.005,0.01,0.02
        - --configmap=ingress-controller/ingress-controller
        - --default-ssl-certificate=ingress-controller/ingress-default-tls
        - --default-backend-service=ingress-controller/ingress-default-backend
        - --rate-limit-update=0.25
        - --publish-service=ingress-controller/haproxy-ingress-controller
        - --update-status=true
```

* This is the service of type LoadBalancer. Relevant considerations:
  * I specify a nlb as loadbalancer for the cluster;
  * I also use externaldns to create my Ingress entries automatically on Route53;

```
apiVersion: v1
kind: Service
metadata:
  annotations:
    external-dns.alpha.kubernetes.io/hostname: 'www.a01.devsres.com'
    service.beta.kubernetes.io/aws-load-balancer-additional-resource-tags: devsres.com/cluster=tfes-a01,devsres.com/scid=10316,devsres.com.io/author=terraform,devsres.com/project=aws-eks
    service.beta.kubernetes.io/aws-load-balancer-type: nlb
  name: haproxy-ingress-controller
  namespace: ingress-controller
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: http
  - name: https
    port: 443
    protocol: TCP
    targetPort: https
  selector:
    run: ingress-controller
  type: LoadBalancer
```

So how do I use it?

Well, other than creating the service above and customizing the deployment, I did nothing else.

I picked the ecsdemo from https://www.eksworkshop.com/beginner/050_deploy/applications/ and fixed it for our domain:

```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ecsdemo-frontend
  namespace: default
spec:
  rules:
  - host: ecsdemo.a01.devsres.com
    http:
      paths:
      - backend:
          serviceName: ecsdemo-frontend
          servicePort: 80

```

External DNS eventually will create the Route 53 entry, and the Ingress Controller eventually will update that Ingress object with this status:

```
status:
  loadBalancer:
    ingress:
    - hostname: verylongawselbname-anotherverylongstring.elb.us-east-1.amazonaws.com

```

And that's it.

**Comment by tleish** [comment]
@mrrandrade - I'm looking for basic guidelines to run it on AWS, this was great information.  The above makes sense except for external-dns, I'll look into it some more.  Thank you for the info.

**Comment by tleish** [comment]
@mrrandrade - I finally have some time to get around to testing this.  I feel like I'm so close, but I'm missing something and it's not quite working with an AWS NLB.

Here's what I'm doing:

```bash
kubectl create -f https://haproxy-ingress.github.io/resources/haproxy-ingress.yaml
# Get Nodes
kubectl get node
# NAME                                              STATUS   ROLES    AGE   VERSION
# ip-<000-000-000-00.us-region-2>.compute.internal  Ready    <none>   64d   v1.15.11-eks-af3caf
# ip-<000-000-000-01.us-region-2>.compute.internal  Ready    <none>   64d   v1.15.11-eks-af3caf

kubectl label node ip-<000-000-000-00.us-region-2>.compute.internal role=ingress-controller
kubectl label node ip-<000-000-000-01.us-region-2>.compute.internal role=ingress-controller
```
Perhaps I do not need to label both nodes?

Then I run `kubectl appy -f` with the following config.

```yaml
# Ingress
apiVersion: v1
kind: Service
metadata:
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: tcp
    service.beta.kubernetes.io/aws-load-balancer-connection-idle-timeout: '60'
    service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: 'true'
    service.beta.kubernetes.io/aws-load-balancer-type: nlb
  name: ingress-haproxy-controller
  namespace: ingress-controller
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: http
    - name: https
      port: 443
      protocol: TCP
      targetPort: https
  selector:
    run: ingress-controller
  type: LoadBalancer

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: nginx:1.14.2
          ports:
            - containerPort: 80

---

apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: haproxy
spec:
  rules:
    - host: <my.domain.com>
      http:
        paths:
          - backend:
              serviceName: nginx
              servicePort: 80
            path: /
```

I can see the NLB is created.

```bash
kubectl get svc -n ingress-controller
# NAME                         TYPE           CLUSTER-IP     EXTERNAL-IP                                                            PORT(S)                      AGE
# ingress-haproxy-controller   LoadBalancer   10.100.50.94   verylongawselbname-anotherverylongstring.elb.us-west-2.amazonaws.com   80:30086/TCP,443:31992/TCP   50m
```
I then manually assign <my.domain.com> to the new NLB in Route53.

If I ping <my.domain.com> it now resolves to an IP (and does not if I remove the config), but the request times out and of course the page is not pulling up.

Any suggestions for troubleshooting?
