### ISSUE TITLE
grafana dashboard emtrics sample without add it on UI?

### ISSUE THREAD

**Issue by remoe** [jcmoraisjr/haproxy-ingress#599]
I've tried to integrate the newest metrics dashboard. Is it possible to create a sample without adding it by hand with ui? One find a integration sample here:

https://github.com/poseidon/typhoon/blob/master/addons/grafana/dashboards-nginx-ingress.yaml

They don't use any "__inputs" or "__requires". And one can add this as default:

```yaml
      "templating": {
        "list": [
          {
            "current": {
              "text": "default",
              "value": "default"
            },
            "hide": 0,
            "label": null,
            "name": "datasource",
            "options": [
            ],
            "query": "prometheus",
            "refresh": 1,
            "regex": "",
            "type": "datasource"
          },
```

And a sample with all needed exporter/ingress configs?
