### ISSUE TITLE
Hi， I have a doubt about loadbalance

### ISSUE THREAD

**Issue by wangjianghuan** [jcmoraisjr/haproxy-ingress#6]
Hi @jcmoraisjr  After successful haproxy - ingress deployment，Access to the back-end  is still nodeport ways，for example ： 
![image](https://cloud.githubusercontent.com/assets/16407843/23941966/b13149d2-09a5-11e7-85cc-e60a77e5e68f.png)

What is the difference between direct access the nodeport service

**Comment by jcmoraisjr** [comment]
There are two options here:

1) use `hostNetwork` as below:

```
spec:
  template:
    metadata:
      labels:
        ...
    spec:
      hostNetwork: true
      containers:
      ...
```

When use `hostNetwork`? You need to know the client's IP and you can expose all ports that HAProxy will bind (currently 80, 443, 1936)

2) use `hostPort` as below:

```
        ports:
        - name: http
          hostPort: 80
          containerPort: 80
        - name: https
          hostPort: 443
          containerPort: 443
        - name: stat
          hostPort: 1936
          containerPort: 1936
```

When use `hostPort`? You need to choose what ports to bind and you don't need to know the client's IP. `hostPort` and `NodePort` use a proxy while `hostNetwork` makes HAProxy itself listen the ports.

**Comment by d123456temp** [comment]
Hi, my issue might be somehow related to this... Please kindly look at my misery...

I'm new to K8s... After finishing your tutorial (thanks!), I'm able to connect to my app hidden behind Haproxy ingress via "public" IP, but only using NodePort port value:

curl http://172.42.42.11:32338  (I'm using your unmodified haproxy-ingress.yaml)
but
curl http://172.42.42.11 returns "port 80: Connection refused"

What I would like to do is to be able to connect to port 80 instead of 32338 or another random port
Any attempt to do this using your suggestions above or example from other issue reports doesn't help.
The only way I can even achieve connection is by using line from your tutorial:
kubectl --namespace=ingress-controller expose deploy/haproxy-ingress --type=NodePort

Any attempt to include this service object in haproxy-ingress.yaml ends in ingress not available even on nodeport port.

How should I create service object yml to be able to access ingress on port 80?

So far I ended with this at the top of haproxy-ingress.yam and it doesn't work:

apiVersion: v1
kind: Service
metadata:
  name: haproxy-ingress
  labels:
    app: haproxy-ingress
spec:
  type: NodePort
  ports:
    - name: http
      port: 80
      targetPort: 80
    - name: https
      port: 443
      targetPort: 443
    - name: stat
      port: 1936
      targetPort: 1936
  selector:
    name: haproxy-ingress
---

How to fix this?

**Comment by jcmoraisjr** [comment]
Hi, the two approaches above (hostNetwork or hostPort) should be configured in the deployment resource. You don't need a service if using one of them. Please send a ctrl+v of your deployment and also how your k8s environment was created.

**Comment by d123456temp** [comment]
Hi, thank you for your reply.

I'm running a "bare metal" style cluster of Virtualboxes with weave-net:

```
vagrant@k8s1:~$ kubectl get pod -o wide --namespace=kube-system
NAME                           READY     STATUS    RESTARTS   AGE       IP             NODE
etcd-k8s1                      1/1       Running   4          4d        172.42.42.11   k8s1
kube-apiserver-k8s1            1/1       Running   4          4d        172.42.42.11   k8s1
kube-controller-manager-k8s1   1/1       Running   4          4d        172.42.42.11   k8s1
kube-dns-6f4fd4bdf-6cdpr       3/3       Running   12         4d        10.32.0.6      k8s1
kube-proxy-5dklw               1/1       Running   4          4d        172.42.42.13   k8s3
kube-proxy-5v5tp               1/1       Running   4          4d        172.42.42.16   k8s6
kube-proxy-9d8dw               1/1       Running   4          4d        172.42.42.14   k8s4
kube-proxy-h2t8k               1/1       Running   4          4d        172.42.42.12   k8s2
kube-proxy-hhjm5               1/1       Running   4          4d        172.42.42.19   k8s9
kube-proxy-p9ktb               1/1       Running   4          4d        172.42.42.18   k8s8
kube-proxy-stbhm               1/1       Running   4          4d        172.42.42.15   k8s5
kube-proxy-thkx8               1/1       Running   4          4d        172.42.42.11   k8s1
kube-proxy-wl6kj               1/1       Running   4          4d        172.42.42.17   k8s7
kube-scheduler-k8s1            1/1       Running   4          4d        172.42.42.11   k8s1
weave-net-5q62h                2/2       Running   13         4d        172.42.42.14   k8s4
weave-net-8h84v                2/2       Running   13         4d        172.42.42.11   k8s1
weave-net-bzpgc                2/2       Running   12         4d        172.42.42.19   k8s9
weave-net-ghcv4                2/2       Running   12         4d        172.42.42.12   k8s2
weave-net-hhdvd                2/2       Running   11         4d        172.42.42.13   k8s3
weave-net-jh8qp                2/2       Running   11         4d        172.42.42.18   k8s8
weave-net-pswbz                2/2       Running   13         4d        172.42.42.15   k8s5
weave-net-tlsfp                2/2       Running   13         4d        172.42.42.17   k8s7
weave-net-vc7qf                2/2       Running   11         4d        172.42.42.16   k8s6
```

haproxy-ingress.yaml I'm using:

```
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  labels:
    run: haproxy-ingress
  name: haproxy-ingress
spec:
  selector:
    matchLabels:
      run: haproxy-ingress
  template:
    metadata:
      labels:
        run: haproxy-ingress
    spec:
      #hostNetwork: true
      serviceAccountName: ingress-controller
      containers:
      - name: haproxy-ingress
        image: quay.io/jcmoraisjr/haproxy-ingress
        args:
        - --default-backend-service=$(POD_NAMESPACE)/ingress-default-backend
        - --default-ssl-certificate=$(POD_NAMESPACE)/tls-secret
        - --configmap=$(POD_NAMESPACE)/haproxy-ingress
        ports:
        - name: http
          hostPort: 80
          containerPort: 80
        - name: https
          hostPort: 443
          containerPort: 443
        - name: stat
          hostPort: 1936
          containerPort: 1936
        env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
```

This "somehow" works, when I do:

kubectl --namespace=ingress-controller expose deploy/haproxy-ingress --type=NodePort

But that way I cannot use port 80 on public/external IP:

```
vagrant@k8s1:~$ curl http://172.42.42.11
curl: (7) Failed to connect to 172.42.42.11 port 80: Connection refused
```
Only the NodePort-assigned high port:

```
vagrant@k8s1:~$ curl http://172.42.42.11:31495
default backend - 404
```

What I want to have is to have HAProxy/Ingress running nicely on port 80. I thought the service shown in my first comment above will help me to accomplish that, but it's not.

How can I achieve this?
