### ISSUE TITLE
Help exposing haproxy-ingress / resolving DNS

### ISSUE THREAD

**Issue by Bajix** [jcmoraisjr/haproxy-ingress#60]
I'm struggling to get this to expose properly. Currently I'm using external-dns + annotations to setup the DNS A-Type records via the `external-dns.alpha.kubernetes.io/hostname` annotation on the haproxy-ingress service, however this seems to not actually be exposed and instead uses the internal IP. What's the proper way of making haproxy-ingress public-facing? Sorry if this is obvious... all this is a lot to wrap one's mind around.

```
kind: Service
apiVersion: v1
metadata:
  name: haproxy-ingress
  namespace: production
  labels:
    app: haproxy-ingress
  annotations:
    external-dns.alpha.kubernetes.io/hostname: api.levelstothegame.com
spec:
  ports:
    - port: 80
      targetPort: 80
    - port: 443
      targetPort: 443
    - port: 1936
      targetPort: 1936
```
---
```
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: haproxy-ingress
  namespace: production
  labels:
    app: haproxy-ingress
spec:
  selector:
    matchLabels:
      app: haproxy-ingress
  template:
    metadata:
      labels:
        app: haproxy-ingress
    spec:
      hostNetwork: true
      containers:
      - name: haproxy-ingress
        image: quay.io/jcmoraisjr/haproxy-ingress
        args:
        - --default-backend-service=$(POD_NAMESPACE)/node-api
        - --default-ssl-certificate=$(POD_NAMESPACE)/haproxy-tls
        - --configmap=$(POD_NAMESPACE)/haproxy-ingress
        ports:
        - name: http
          containerPort: 80
        - name: https
          containerPort: 443
        - name: stat
          containerPort: 1936
        env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
```
---
```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: haproxy-ingress
  namespace: production
  labels:
    app: haproxy-ingress
  annotations:
    kubernetes.io/ingress.class: "haproxy"
spec:
  tls:
  - hosts:
    - api.levelstothegame.com
    secretName: haproxy-tls
  rules:
  - host: api.levelstothegame.com
    http:
      paths:
      - path: /
        backend:
          serviceName: node-api
          servicePort: 3000
```
---
```
kind: Service
apiVersion: v1
metadata:
  name: node-api
  namespace: production
  labels:
    app: node-api
    tier: backend
spec:
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  selector:
    app: node-api
    tier: backend
```
---
```
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: external-dns
  namespace: production
spec:
  template:
    metadata:
      labels:
        app: external-dns
    annotations:
      scheduler.alpha.kubernetes.io/critical-pod: ''
      iam.amazonaws.com/role: "external-dns"
    spec:
      containers:
      - name: external-dns
        image: registry.opensource.zalan.do/teapot/external-dns:v0.4.5
        args:
        - --source=service
        - --source=ingress
        - --domain-filter=levelstothegame.com
        - --provider=aws
        - --policy=upsert-only
        - --registry=txt
        - --txt-owner-id=external-dns
        - --aws-zone-type=public
```
