### ISSUE TITLE
Can't get a certificate from acme

### ISSUE THREAD

**Issue by rellax-net** [jcmoraisjr/haproxy-ingress#600]
Hi,
I have created the following Ingress and I am trying to get a certificate from acme:
```yaml
apiVersion: extensions/v1beta1
 kind: Ingress
 metadata:
   name: [name]
   namespace: [namespace]
   annotations:
     ingress.kubernetes.io/acme-emails: [valid-email-here]
     ingress.kubernetes.io/acme-endpoint: 'v02-staging'
     ingress.kubernetes.io/acme-terms-agreed: 'true'
     kubernetes.io/tls-acme: "true"
 spec:
   tls:
   - hosts:
     - [domain.tld]
     secretName: admin-ssl
   rules:
   - host: [domain.tld]
     http:
       paths:
       - backend:
           serviceName: [svc]
           servicePort: 443
         path: /
```
I have use the command-line argument below to run haproxy-ingress
```yaml
--configmap=ingress-controller/haproxy-ingress
--acme-server=true
--acme-track-tls-annotation=true
```
And I modified the clusterrole to permit the ingress-controller to create and update secret
```yaml
[...]
rules:
  - verbs:
      - create
      - update
    apiGroups:
      - ''
    resources:
      - secrets
[...]
```
I must be missing something here because when I create the ingress, haproxy-controller complains about 

> using default certificate due to an error reading secret 'admin-ssl' on ingress '[namespace]/[ingress_name]': secret [namespace]/admin-ssl was not found

What could I be missing?
