### ISSUE TITLE
TCP on port 443

### ISSUE THREAD

**Issue by bartversluijs** [jcmoraisjr/haproxy-ingress#602]
Hi all,

I'm currently converting an open-source project called [openbalena](https://github.com/balena-io/open-balena). It's built with docker, and has some HTTP(S) containers, but also a VPN running on port 443. They've created an [HAProxy config](https://github.com/balena-io/open-balena/blob/master/src/haproxy/haproxy.cfg) to handle this in the `frontend ssl-in`.

I've tried to replicate this via the HAProxy Ingress and set the following TCP:
```yaml
tcp:
  - 443: "openbalena/vpn:443:PROXY-V2:PROXY-V2"
```

This seems to work, but it looks like it's load balancing between 443 TCP and 443 HTTPS, instead of checking if it's an TCP request with TLS or not, like they did in the HAProxy config.

Is there any way to accomplish this? I'm out of ideas at the moment...

**Comment by jcmoraisjr** [comment]
Hi, haproxy allows reusing the same port number between processes and frontends and the kernel will load balance between all the listening sockets. The problem here is that you cannot disable the http sockets so about half of the requests will be received there. You can however change the listening http port to another one you're not using, doc [here](https://haproxy-ingress.github.io/docs/configuration/keys/#bind).

**Comment by bartversluijs** [comment]
Thanks for your answer!
The problem is, I'm also using port 443 for some HTTPS requests to other pods. So I'm using both of them. That's the problem...

If I understand the haproxy.conf correctly of openBalena, this fixes the problem there:
```
frontend ssl-in
  mode tcp
  bind *:443
  tcp-request inspect-delay 2s
  tcp-request content accept if { req.ssl_hello_type 1 }

  acl is_ssl req.ssl_ver 2:3.4
  use_backend redirect-to-https-in if is_ssl
  use_backend vpn-devices if !is_ssl
```

Is there any way to implement this in the Ingress, via a config-snippet or something?

**Comment by jcmoraisjr** [comment]
So you cannot use tcp-service here. Have a look at [ssl-passthrough](https://haproxy-ingress.github.io/docs/configuration/keys/#ssl-passthrough) (use the backend tls cert) or [secure-backend](https://haproxy-ingress.github.io/docs/configuration/keys/#secure-backend) (use haproxy tls cert)

**Comment by bartversluijs** [comment]
I'll take a look at that.
Just FYI, this is my ingress.yml:
```
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: ingress-nginx
  namespace: openbalena
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: 500m
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    kubernetes.io/ingress.class: "haproxy"
spec:
  tls:
  - hosts:
    - api.${OPENBALENA_HOST_NAME}
    - registry.${OPENBALENA_HOST_NAME}
    - vpn.${OPENBALENA_HOST_NAME}
    - s3.${OPENBALENA_HOST_NAME}
    secretName: echo-tls
  rules:
  - host: api.${OPENBALENA_HOST_NAME}
    http:
      paths:
      - path: /
        backend:
          serviceName: api
          servicePort: 80
  - host: registry.${OPENBALENA_HOST_NAME}
    http:
      paths:
      - path: /
        backend:
          serviceName: registry
          servicePort: 80
```

So every pod used port 80, so they probably use SSL offloading. Only one pod (vpn pod) has to have default TCP.
