### ISSUE TITLE
Daemonset deployment with additional tcp port

### ISSUE THREAD

**Issue by muconsulting** [jcmoraisjr/haproxy-ingress#606]
Hi,

I'm trying to deploy haproxy-ingress (via helm chart) behind an AWS NLB  and expose additional tcp port (for mqtt) - but I don't seem to find the right configuration to inject in the values. 

i.e. 

```
 kind: DaemonSet
  tcp:
    1883: "ingest/hivemq:1883"
  daemonset:
    useHostPort: true
    hostPorts:
      http: 80
      https: 443
      tcp:
        - 1883
```
but I keep on getting  templating errors ..
```
executing "haproxy-ingress/templates/controller-daemonset.yaml" at <eq $key $p>: error calling eq: incompatible types for comparison
```
Am I missing something ?
