### ISSUE TITLE
Wrong time in ingress container and in logs

### ISSUE THREAD

**Issue by zbebeto** [jcmoraisjr/haproxy-ingress#608]
Hi,
The right timezone / time  in my containers are set by mounting the file /etc/localtime(ubuntu based images) from the host.
BUT in haproxy ingress I realized that the container does not have this file.
How Can I configure the ingress containers timezone/time?

**Comment by zbebeto** [comment]
The time in the http log is following the time presented in the container ,,, being wrong too...

**Comment by zbebeto** [comment]
The other way I know to configure timezone/time in containers is done by setting the environment variable TZ .

**Comment by zbebeto** [comment]
It is causing problems in my production environment ... the time is wrong in my ELKG reports....

**Comment by zbebeto** [comment]
I tested mounting /etc/locatime even with the file being originally missing and worked .
Closing the issue.

**Comment by timdeluxe** [comment]
This does not work anymore in the current release.

This worked for me and maybe it is helpful for others as well:

- Run an alpine:latest container with a volume mount to store the zoneinfo file locally
- Install tzdata package (apk add tzdata)
- Copy the the zoneinfo of whatever timezone you need (f.e. /usr/share/zoneinfo/Europe/Berlin) to the volume mount
- Take care that file is mounted on the same location of your haproxy ingress controller deployment *
Done. I worked with timezone set in /etc/timezone, but it may also work with timezone set via environment i don't know.
(Found this out by analysing the "date" call with strace) 


\* If  you use  the helm chart, you can achive it like this:
Be aware that this example is with timezone Berlin - adapt it to your needs!
base64 encode the zoneinfo file.
Create a configmap where you paste the base64 code:
```
kind: ConfigMap
apiVersion: v1
metadata:
  name: haproxy-zoneinfo-configmap
binaryData:
  Berlin: <base64 code here>
```
Use the helm chart with these values.yaml:
```
  extraEnvs:
  - name: TZ
    value: Europe/Berlin
  extraVolumeMounts:
  - mountPath: /usr/share/zoneinfo/Europe/Berlin
    name: zoneinfo
    subPath: Berlin
  extraVolumes:
  - configMap:
      name: haproxy-zoneinfo-configmap
    name: zoneinfo
```
The first timestamp of the access-logs container is then still wrong, but the second timestamp is correct (also the timestamp in the logs from haproxy itself). I raised https://github.com/haproxy-ingress/charts/pull/22 to get it also working for the access-logs container.
