### ISSUE TITLE
Cross-namespace ingress access without secrets

### ISSUE THREAD

**Issue by damomurf** [jcmoraisjr/haproxy-ingress#621]
We have a setup that is quite restricted from a security perspective and it is generally frowned-upon to run anything that requires cluster-level access to Kubernetes secrets.

Our use case really requires that an ingress object could be consumed from any namespace, but the TLS secrets for that ingress would only be reachable from one specific namespace: the namespace the controller itself and its service account reside? Am I missing some existing combination of options that would achieve that already? For example: you would be able to have an ingress defined in the `product1` namespace, but any TLS certificates required for that Ingress could only be retrieved from an `ingress` namespace.

Ideally I was hoping that --allow-cross-namespace would do what I want, but I've just tested it and it fails to provision any ingress in this case where the ingress namespace and secret namespace differ, which is what the docs suggest - even if the secrets are coming from the ingress controller's own namespace.

**Comment by jcmoraisjr** [comment]
Hi, any secret name from annotations or the secretName attribute has the `[<namespace>/]<name>` syntax, which means the namespace is always optional. If not provided, the ingress namespace is used.

The role of the `--allow-cross-namespace` here is to ensure that, if declared, any namespace can be used, otherwise a provided namespace should match the ingress one.

That said please describe a bit more with a config sample and the error messages.

**Comment by damomurf** [comment]
@jcmoraisjr Thanks so much for your prompt reply.

So fundamentally, my issue is that I can't allow the ingress controller to have cluster-level watch permission on secrets or configmaps (because watch implies get). List access is not a problem for either object. The intention was to allow the controller only to read secrets from the namespace in which it resides, which is covered by the (non-cluster) role configured that allows list/watch on secrets and configmaps only in that namespace.

With the `--allow-cross-namespace=true` option present, the controller still attempts to create a (presumably cluster-level) watch on both ConfigMaps and Secrets and fails:

```
E0722 00:53:09.503874       6 reflector.go:280] pkg/mod/k8s.io/client-go@v0.0.0-20191114101535-6c5935290e33/tools/cache/reflector.go:96: Failed to watch *v1.ConfigMap: unknown (get configmaps)
E0722 00:53:09.655626       6 reflector.go:280] pkg/mod/k8s.io/client-go@v0.0.0-20191114101535-6c5935290e33/tools/cache/reflector.go:96: Failed to watch *v1.Secret: unknown (get secrets)
```

This is with stable v0.9 and the following arguments:
```
      --configmap=ingress/cluster-ingress-controller
      --ingress-class=cluster-haproxy
      --sort-backends  
      --default-backend-service=ingress/cluster-ingress-default-backend
      --allow-cross-namespace=true
```

The controller ConfigMap is: 

```
  backend-server-slots-increment: "1"
  dynamic-scaling: "true"
  healthz-port: "10253"
  http-port: "8080"
  https-port: "8443"
  slots-min-free: "0"
  stats-port: "1936"
  syslog-endpoint: localhost:1514
```

And an example ingress that exists in an "infra" namespace, with its TLS secret located in the ingress namespace:
```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    ingress.kubernetes.io/health-check-interval: 5s
    ingress.kubernetes.io/health-check-uri: /-/ready
    kubernetes.io/ingress.class: cluster-haproxy
  name: prometheus-infra-prometheus
  namespace: infra
spec:
  rules:
  - host: dev-prometheus.env.domain
    http:
      paths:
      - backend:
          serviceName: prometheus-infra-prometheus
          servicePort: http
        path: /
  tls:
  - hosts:
    - dev-prometheus.env.domain
    secretName: ingress/tls-private-prometheus-server
```

I hope that extra information helps.

**Comment by damomurf** [comment]
Adding more information on the clusterrole/role: if I remove any access at the cluster role level to configmaps or secrets, the following spams the log:
```
E0722 01:06:46.081975       6 reflector.go:123] pkg/mod/k8s.io/client-go@v0.0.0-20191114101535-6c5935290e33/tools/cache/reflector.go:96: Failed to list *v1.ConfigMap: configmaps is forbidden: User "system:serviceaccount:ingress:cluster-ingress" cannot list resource "configmaps" in API group "" at the cluster scope
E0722 01:06:46.082749       6 reflector.go:123] pkg/mod/k8s.io/client-go@v0.0.0-20191114101535-6c5935290e33/tools/cache/reflector.go:96: Failed to list *v1.Secret: secrets is forbidden: User "system:serviceaccount:ingress:cluster-ingress" cannot list resource "secrets" in API group "" at the cluster scope
```

If I then allow list access only to configmaps/secrets at the cluster-level, I get: 
```
E0722 01:09:00.823025       6 reflector.go:280] pkg/mod/k8s.io/client-go@v0.0.0-20191114101535-6c5935290e33/tools/cache/reflector.go:96: Failed to watch *v1.ConfigMap: unknown (get configmaps)
```
and the container terminates.

ClusterRole:
```
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cluster-ingress
rules:
- apiGroups:
  - ""
  resources:
  - endpoints
  - nodes
  - pods
  verbs:
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - configmaps
  - secrets
  verbs:
  - list
- apiGroups:
  - ""
  resources:
  - nodes
  verbs:
  - get
- apiGroups:
  - ""
  resources:
  - services
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - extensions
  resources:
  - ingresses
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
- apiGroups:
  - extensions
  resources:
  - ingresses/status
  verbs:
  - update
```

Role in the ingress namespace:
```
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: cluster-ingress
  namespace: ingress
rules:
- apiGroups:
  - ""
  resources:
  - pods
  - secrets
  - namespaces
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - configmaps
  - endpoints
  verbs:
  - get
  - create
  - update
  - list
  - watch
- apiGroups:
  - extensions
  resourceNames:
  - cluster-ingress
  resources:
  - podsecuritypolicies
  verbs:
  - use
```
