### ISSUE TITLE
Redirect in haproxy ingress

### ISSUE THREAD

**Issue by zbebeto** [jcmoraisjr/haproxy-ingress#628]
Hi
I need to know a very basic thing . How a redirect from URL X to URL Y is treated in ingress haproxy?
Is it an annotation in the ingress object ?

**Comment by jcmoraisjr** [comment]
Hi, there isn't an annotation to do this but you can use a config snippet, haproxy ingress doc [here](https://haproxy-ingress.github.io/docs/configuration/keys/#configuration-snippet) and haproxy doc [here](https://cbonte.github.io/haproxy-dconv/2.0/configuration.html#4.2-http-request%20redirect) and [here](https://cbonte.github.io/haproxy-dconv/2.0/configuration.html#redirect).

```yaml
    annotations:
      ingress.kubernetes.io/config-backend: |
        http-request redirect location http://site.localdomain/ if your-acl
```
