### ISSUE TITLE
Trying ssl-passthrough with grpc: somehow finally it gets to the ingress.local cert

### ISSUE THREAD

**Issue by attila123** [jcmoraisjr/haproxy-ingress#649]
Environment:
- latest minikube (v1.12.3) with none driver (installed to a VM according to https://www.linuxtechi.com/install-kubernetes-k8s-minikube-centos-8/)
- `minikube ip` returns 192.168.0.6, so I used it in the nip.io adresses
- haproxy-ingress set up according to https://haproxy-ingress.github.io/docs/getting-started/, the nginx example worked (`curl nginx.192.168.0.6.nip.io` returned the nginx start page html)

Hi, I am new to haproxy-ingress and trying to implement an ssl-passthrough to a service with the following ingress:

```
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    ingress.kubernetes.io/ssl-passthrough: "true"
    ingress.kubernetes.io/strict-host: "false"
  name: vpn-manager
  namespace: edge-vpn
spec:
  rules:
  - host: vpnmanager.192.168.0.6.nip.io
    http:
      paths:
      - backend:
          serviceName: vpn-manager
          servicePort: 50100
```
(the strict-host was just a fix attempt, but then I realized/learned that it should not matter for SSL-passthrough as traffic is encrypted)

So the client and server applications implements grpc over TLS and I tested it, and they work together perfectly (client can call server via grpc over TLS) if the client and server app is connected directly, but I have trouble make it work via this ingress.  
(My client application is written in python and I could not get much debug information out of it (even after enabling tracing with some env variables, other then cert verification failed basically, so I tried to debug with grpcurl).)

The self-signed cert is valid for 'vpnmanager', so this is expected:
```
$ grpcurl vpnmanager.192.168.0.6.nip.io:443 whatever/whatever
Failed to dial target host "vpnmanager.192.168.0.6.nip.io:443": x509: certificate is valid for vpnmanager, not vpnmanager.192.168.0.6.nip.io
```
But when I try to set the servername, it says that the cert is valid for ingress.local, why?
```
grpcurl -servername vpnmanager vpnmanager.192.168.0.6.nip.io:443 whatever/whatever
Failed to dial target host "vpnmanager.192.168.0.6.nip.io:443": x509: certificate is valid for ingress.local, not vpnmanager
```
I suspect that that in this case the traffic is not always terminated at the application. Why, and how to fix it?

**Comment by jcmoraisjr** [comment]
Hi, haproxy ingress uses the sni extension to define if the request is a ssl-passthrough one and it should create a tcp tunnel, or if it should itself ssl-offload the request and handle it as an http one. I suspect that `-servername` defines the sni extension to `vpnmanager` just like `openssl connect` does, so haproxy is trying to ssl-offload - hence the ingress.local dn - just to give you a nice default http response.

**Comment by attila123** [comment]
Thanks for your support. The cert was created with
```
openssl req -x509 -newkey rsa:4096 -days 365000 -nodes -keyout ca-key.pem -out ca-cert.pem -subj "/CN=vpnmanager"
```
(this was not about security, but to make it work somehow first...)

My idea was that by providing the servername as fixed 'vpnmanager' this way the cert can be used regardless of what actual hostname the client is connecting to (which is different in various clusters in our case, I know the cert should be generated individually...).

Indeed I could reproduce the problem also with openssl:

```
# without giving servername, returns the correct (self-signed) cert I created, so the application serves the request
openssl s_client -connect vpnmanager.192.168.0.6.nip.io:443

# with servername, unfortunately returns the Kubernetes Ingress Controller Fake Certificate
openssl s_client -servername vpnmanager -connect vpnmanager.192.168.0.6.nip.io:443
```
For the servername the `grpcurl -help` says: `Override server name when validating TLS certificate. <...>`

`openssl s_client --help` says: `-servername val            Set TLS extension servername (SNI) in ClientHello (default)`

So is there a way to somehow configure things (preferably in Ingress level) so that SSL passthrough would work even if the SNI extension is in use? (to turn off the ssl-offload?)

**Comment by attila123** [comment]
Ooops, I realized I just need to change the host in my ingress to 'vpnmanager' (used by the grpc client), so
```
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    ingress.kubernetes.io/ssl-passthrough: "true"
  name: vpn-manager
  namespace: edge-vpn
spec:
  rules:
  - host: vpnmanager
    http:
      paths:
      - backend:
          serviceName: vpn-manager
          servicePort: 50100
```
Quck verification with openssl:
```
# This now returns the correct (application) cert
openssl s_client -servername vpnmanager -connect vpnmanager.192.168.0.6.nip.io:443
```
Thanks for your support, closing the issue now.
