### ISSUE TITLE
Allow to not have a default backend

### ISSUE THREAD

**Issue by jvanbruegge** [jcmoraisjr/haproxy-ingress#657]
I can't get a wildcard certificate, so at the moment I have to serve the ingress-default-backend via HTTP. But what I really want is that the server does not even allow a connection like when I try to hit https://foo.google.com .

**Comment by jcmoraisjr** [comment]
This works this way on `foo.google.com` because this domain doesn't exist:

```
$ curl -v https://foo.google.com
* Could not resolve host: foo.google.com
* Closing connection 0
curl: (6) Could not resolve host: foo.google.com
```

You can simulate such behavior closing the tcp connection in the default backend. You'll need a dummy service as a placeholder of the configuration, scaling to zero replicas is fine:

```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    ingress.kubernetes.io/config-backend: |
      tcp-request content reject
  name: default
  namespace: default
spec:
  backend:
    serviceName: dummy-svc
    servicePort: 8080
```
