### ISSUE TITLE
Host-scope configuration question/feature request

### ISSUE THREAD

**Issue by Unichron** [jcmoraisjr/haproxy-ingress#669]
Hi,

I have a bit of a niche problem. We need to manage tls configuration dynamically, because our service supports custom domains, meaning that when a new tenant is created we need to make haproxy aware of the new certificate/private key. For this currently there is a service that creates a new ingress. Now this creates a lot of redundancy, because that ingress resource needs to contain the same backend configuration over and over again. The backend config is of course static, but may sometimes change, making the it difficult to maintain, because the service component needs to be updated, and also already created resources need to be patched.

Ideally what I would like to be able to do, is configure the backend rules once (without host restriction), and have per host configuration like tls secret and host annotations somewhere else.

I know that the kubernetes api is a bit restrictive in this regard, because an ingress without a backend rule is not valid. After some trial and error I found out that the api allows for and ingress object like this:

```yaml
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: test
spec:
  rules:
    - host: ""
  tls:
    - hosts:
        - example.com
      secretName: ingress-tls-example.com
```

The problem is that haproxy ingress skips over it, because it doesn't contain the `http` part under the rule. Also I'm not sure that this road would lead to something that is not considered obscure and hackish.

An alternative solution that I thought about is if we could also define host-scope config in a configmap. In this case, the ingress would remain perfectly normal. We would have 1 ingress total. The tls config can be managed by appending/removing entries in this, and managing other host-scope config would be in separate configmap(s?).

What's your take on this?

**Comment by jcmoraisjr** [comment]
Hi, we have a somewhat similar problem here and our ingress is configured like this:

```yaml
spec:
  rules:
  - host: domain.local
  tls:
  - hosts:
    - domain.local
    secretName: domain-crt
```

Is this syntax also useful for your usecase? Didn't test myself with two or more domains but this should work as well.
