### ISSUE TITLE
Assigned cert isn't used if default cert CN or SAN match the hostname

### ISSUE THREAD

**Issue by leptonyu** [jcmoraisjr/haproxy-ingress#687]
**Description of the problem**

I config --default-ssl-certificate=cert-manager/cert-tls and

```yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: somename
spec:
  tls:
  - hosts:
    - example.com
    secretName: blog-cert-tls
```

both `cert-manager/cert-tls`  and  `blog-cert-tls` signed with CN `example.com`.

It should be use cert from `blog-cert-tls`, but turns out to be always `cert-manager/cert-tls`. This behavior is not right.

```cfg
/ # cat /etc/haproxy/maps/_front001_bind_crt.list
# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #
# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #
# #
# #   HAProxy Ingress Controller
# #   --------------------------
# #   This file is automatically updated, do not edit
# #
#
/ingress-controller/ssl/cert-manager_cert-tls.pem
/ingress-controller/ssl/default_blog-cert-tls.pem example.com
```

Using haproxy-ingress v0.10.1
