### ISSUE TITLE
Failed to get the sockets from the old process

### ISSUE THREAD

**Issue by frogluo** [jcmoraisjr/haproxy-ingress#696]
**Description of the problem**

My haproxy-ingress had run a long time, but this day 
haproxy-ingress logs deploy on k8s showed:
```
W1111 02:08:41.422283       6 instance.go:457] output from haproxy:
[WARNING] 315/020841 (78) : We didn't get the expected number of sockets (expecting 253 got 0)
[NOTICE] 315/020841 (78) : haproxy version is 2.2.4-de45672
[ALERT] 315/020841 (78) : Failed to get the sockets from the old process!
E1111 02:08:41.422330       6 instance.go:301] error reloading server:
exit status 1
```
and then , the service ( update k8s deployment image only )on k8s can't access and return http status code:502
it's nomal for no update service(deployment/pod).

**but if  --reload-strategy=native，no problem。**
so i think maybe something wrong with reusesocket?

**Environment information**

k8s 1.15.7
HAProxy Ingress version: `v0.12.1`
v0.9 has the problem so i upgrade to v0.12.1, and  As well 

it's R&D environment ，pod change very frequently。

Command-line options:

```
 - name: haproxy-ingress
        image: xxx/k8s/haproxy-ingress:v0.12.1
        args:
        - --default-backend-service=kube-system/ingress-default-backend
        - --configmap=kube-system/haproxy-ingress
        - --sort-backends
        - --rate-limit-update=0.05
        - --tcp-services-configmap=kube-system/tcp-services
```

Global options:

```
apiVersion: v1
kind: ConfigMap
metadata:
  name: haproxy-ingress
  namespace: kube-system
data:
  forwardfor: "ifmissing"
  max-connections: "65535"
  timeout-stop: "1800s"
  timeout-client: "1800s"
  timeout-server: "1800s"
  # nbthread: "4"
  use-haproxy-user: "true"
  slots-min-free: "1"
```
