### ISSUE TITLE
H2-SSL Backend Protocol 0HTTP/1.1 404 Not Found

### ISSUE THREAD

**Issue by aliridha1510** [jcmoraisjr/haproxy-ingress#698]
**Description of the problem**

IMAGE : DONET GRPC
HAPROXY V:latest 
kubectl apply -f https://raw.githubusercontent.com/haproxytech/kubernetes-ingress/master/deploy/haproxy-ingress.yaml

I used "h2" as well as h2-ssl, but unfortunately it always didn't work
This is proof that the backend supports HTTP / 2

 when i try http port 80 
```
 curl -I -H 'Host: foo.bar' 'http://195.30.20.200:31254'
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0    21    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0HTTP/1.1 404 Not Found
date: Mon, 16 Nov 2020 12:39:12 GMT
content-length: 21
content-type: text/plain; charset=utf-8
```
, when i try https port 443

```
curl -vk -I -H 'Host: foo.bar' 'https://:195.30.20.20030051'
* Rebuilt URL to: https://195.30.20.200:30051/
*   Trying 195.30.20.200...
* TCP_NODELAY set
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0* Connected to 195.30.20.200 (195.30.20.200) port 30051 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* Cipher selection: ALL:!EXPORT:!EXPORT40:!EXPORT56:!aNULL:!LOW:!RC4:@STRENGTH
* successfully set certificate verify locations:
*   CAfile: C:/Program Files/Git/mingw64/ssl/certs/ca-bundle.crt
  CApath: none
* TLSv1.2 (OUT), TLS header, Certificate Status (22):
} [5 bytes data]
* TLSv1.2 (OUT), TLS handshake, Client hello (1):
} [512 bytes data]
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0* TLSv1.2 (IN), TLS handshake, Ser                                                                                                                             ver hello (2):
{ [98 bytes data]
* TLSv1.2 (IN), TLS handshake, Certificate (11):
{ [773 bytes data]
* TLSv1.2 (IN), TLS handshake, Server key exchange (12):
{ [333 bytes data]
* TLSv1.2 (IN), TLS handshake, Server finished (14):
{ [4 bytes data]
* TLSv1.2 (OUT), TLS handshake, Client key exchange (16):
} [70 bytes data]
* TLSv1.2 (OUT), TLS change cipher, Change cipher spec (1):
} [1 bytes data]
* TLSv1.2 (OUT), TLS handshake, Finished (20):
} [16 bytes data]
* TLSv1.2 (IN), TLS change cipher, Change cipher spec (1):
{ [1 bytes data]
* TLSv1.2 (IN), TLS handshake, Finished (20):
{ [16 bytes data]
* SSL connection using TLSv1.2 / AA-RSA-AAASD-SSD-ASD4
* ALPN, server accepted to use h2
* Server certificate:
*  subject: CN=foo.bar
*  start date: Nov 12 20:36:48 2020 GMT
*  expire date: Nov 12 20:36:48 2021 GMT
*  issuer: CN=foo.bar
*  SSL certificate verify result: self signed certificate (18), continuing anyway.
* Using HTTP2, server supports multi-use
* Connection state changed (HTTP/2 confirmed)
* Copying HTTP/2 data in stream buffer to connection buffer after upgrade: len=0
} [5 bytes data]
* Using Stream ID: 1 (easy handle 0x658910)
} [5 bytes data]
> HEAD / HTTP/2
> Host: foobar
> User-Agent: curl/7.61.1
> Accept: */*
>
{ [5 bytes data]
* Connection state changed (MAX_CONCURRENT_STREAMS == 100)!
} [5 bytes data]
< HTTP/2 404
< date: Mon, 16 Nov 2020 11:57:19 GMT
< content-length: 21
< content-type: text/plain; charset=utf-8
<
  0    21    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0HTTP/2 404
date: Mon, 16 Nov 2020 11:57:19 GMT
content-length: 21
content-type: text/plain; charset=utf-8


* Connection #0 to host 172.18.20.150 left intact
```

**Expected behavior**

HAPROXY-INGRESS LOG
when i try to delete ingress and then apply is 
Ingress 'haproxy-ingress' not registered with controller, cannot delete !

```
 2020/11/16 11:26:38 WARNING utils/utils.go:82 check - [enabled] is DEPRECATED, use "true" or "false"
2020/11/16 11:26:38 WARNING utils/utils.go:82 check - [enabled] is DEPRECATED, use "true" or "false"
2020/11/16 11:26:38 WARNING utils/utils.go:82 check - [enabled] is DEPRECATED, use "true" or "false"
2020/11/16 11:26:38 INFO    controller.go:218 HAProxy reloaded
2020/11/16 11:29:53 INFO    controller.go:218 HAProxy reloaded
2020/11/16 11:33:00 WARNING events.go:209 Ingress 'haproxy-ingress' not registered with controller, cannot delete !
2020/11/16 11:35:21 WARNING events.go:209 Ingress 'haproxy-ingress' not registered with controller, cannot delete !
2020/11/16 11:44:52 WARNING events.go:209 Ingress 'haproxy-ingress' not registered with controller, cannot delete !
2020/11/16 11:46:20 WARNING events.go:209 Ingress 'haproxy-ingress' not registered with controller, cannot delete !
2020/11/16 11:46:33 WARNING utils/utils.go:82 forwarded-for - [enabled] is DEPRECATED, use "true" or "false" 
```

Global options:

```
apiVersion: v1
kind: ConfigMap
metadata:
  name: haproxy
  namespace: haproxy-controller
data:
  servers-increment: "42"
  #ssl-redirect: "false"
  #ssl-passthrough: "true"
  #ssl-certificate: "haproxy-controller/foobar"
  use-htx: "true"
  #backend-protocol: h2
  #ssl-redirect-code: "301"
  #dontlognull: "true"
  #server-ssl: "true"
```

Ingress objects:

```
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
   name: haproxy-ingress
   namespace: haproxy-controller
   annotations:
    kubernetes.io/ingress.class: "haproxy"
    ingress.kubernetes.io/ssl-redirect: "true"
    ingress.kubernetes.io/use-htx: "true"
    ingress.kubernetes.io/backend-protocol: h2-ssl
spec:
  rules:
  - host: foo.bar
    http:
      paths:
      - path: /
        backend:
          serviceName: foobargrpc
          servicePort: 9090
  tls:
  - secretName: foobar
    hosts:
      - foo.bar
```

Any help would be very much appreciated.
