### ISSUE TITLE
ssl-redirect not working

### ISSUE THREAD

**Issue by dimm0** [jcmoraisjr/haproxy-ingress#725]
**Description of the problem**

Can't get ssl-redirect working properly. Tried sticking it in all places, including the configmap and ingress. (also it should be default behavior?)
TLS itself works fine.

**Expected behavior**
When querying http endpoint, be redirected to https

**Steps to reproduce the problem**
Follow the instructions to install.

**Environment information**

HAProxy Ingress version: `v0.11.1`

Command-line options:

```
    - --configmap=haproxy/haproxy-ingress
    - --ingress-class=haproxy
    - --sort-backends
    - --default-ssl-certificate=haproxy/ssl-key
```

Global options:

```
  healthz-port: "10253"
  ssl-redirect: "true"
  stats-port: "1936"

```

Ingress objects:

```
metadata:
  annotations:
    ingress.kubernetes.io/secure-backends: "true"
    ingress.kubernetes.io/ssl-redirect: "true"
    kubernetes.io/ingress.class: haproxy
    traefik.ingress.kubernetes.io/router.tls: ""
```
