### ISSUE TITLE
Missing frontend when upgrading from v0.11.1 to v011.2

### ISSUE THREAD

**Issue by mhyllander** [jcmoraisjr/haproxy-ingress#733]
When I upgraded from v0.11.1 to v0.11.2, I got a strange problem where I'm missing a frontend map entry for one of my ingresses.

For the ingress+service, a frontend+backend should be defined (as before).

Not sure if I can give exact steps, since I don't know what is wrong. I have haproxy-ingress installed in the core namespace, and it is picking up on Ingress resources in several other namespaces. But for one Ingress in the monitoring namespace, when I upgrade to v0.11.2, I only see the backend in /etc/haproxy/haproxy.cfg, but no entries for the host in the /etc/haproxy/maps/\_front\_* files. The backend has configured the correct IP:port to the pod.

If I downgrade to v0.11.1 the Ingress works again and I can access the service.

I should also mention that I am using cert-manager to generate a LetsEncrypt certificate. That seems to be working, because the certificate gets generated and haproxy-ingress has picked up on it and added it to /etc/haproxy/maps/\_front_bind\_crt.list.

**Environment information**

HAProxy Ingress version: `v0.11.2`

Command-line options:

```
--configmap=core/internal-ingress-haproxy --ingress-class=internal --sort-backends --default-backend-service=core/internal-ingress-haproxy-default-backend --default-ssl-certificate=core/hivestreaming.com-tls --reload-strategy=reusesocket
```

Global options:

```
  backend-server-slots-increment: "100"
  config-frontend: |
    #-------------------------------------------------------------
    capture request header Host len 40
    capture request header User-Agent len 100
    capture request header X-Forwarded-For len 100
    #-------------------------------------------------------------
  dns-hold-obsolete: 30s
  dns-hold-valid: 30s
  dns-resolvers: kubernetes=10.128.0.10
  dynamic-scaling: "true"
  forwardfor: update
  healthz-port: "10253"
  http-log-format: '%ci:%cp\ [%t]\ %ft\ %b/%s\ %sslv\ %sslc\ %Tq/%Tw/%Tc/%Tr/%Tt\
    %ST\ %B\ %U\ %CC\ %CS\ %tsc\ %ac/%fc/%bc/%sc/%rc\ %sq/%bq\ %hr\ %hs\ %{+Q}r'
  max-connections: "500000"
  prometheus-port: "9101"
  ssl-ciphers: ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384
  ssl-dh-param: core/dh-param
  ssl-options: no-sslv3 no-tlsv10 no-tlsv11 no-tls-tickets
  stats-port: "1936"
  syslog-endpoint: localhost:514
  tcp-log-format: '%ci:%cp\ [%t]\ %ft\ %b/%s\ %sslv\ %sslc\ %Tw/%Tc/%Tt\ %B\ %U\ %ts\
    %ac/%fc/%bc/%sc/%rc\ %sq/%bq'
  timeout-stop: 1h
```

Ingress objects:

```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/cluster-issuer: internal-letsencrypt-prod
    kubernetes.io/ingress.class: internal
    meta.helm.sh/release-name: monitoring
    meta.helm.sh/release-namespace: monitoring
  labels:
    app.kubernetes.io/instance: monitoring
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: grafana
    app.kubernetes.io/version: 7.3.7
    helm.sh/chart: grafana-6.1.17
  name: monitoring-grafana
  namespace: monitoring
spec:
  rules:
  - host: grafana.dev.hivestreaming.net
    http:
      paths:
      - backend:
          serviceName: monitoring-grafana
          servicePort: 80
        path: /
        pathType: ImplementationSpecific
  tls:
  - hosts:
    - grafana.dev.hivestreaming.net
    secretName: grafana.dev.hivestreaming.net
```

**Comment by jcmoraisjr** [comment]
Hi, can you provide a list of hostnames (no problem if obfuscated, provided that the same sources generates the same targets), paths (needs the real ones) and pathType of your cluster? If you have a big amount of them, provide at least all paths and path types of a hostname where the config is right and another one that the config isn't right.

**Comment by mhyllander** [comment]
Hi, I assume you mean hostnames, paths and pathTypes used in Ingress resources? While I was collecting this information, I noticed that some ingresses have pathType `Prefix` and some have `ImplementationSpecific`, so I experimented a little.

When I set the pathType of the monitoring-grafana ingress above to `Prefix`, it is picked up correctly and configured by the controller. Change back and it's removed again.

On the other hand, there are two other Ingresses in the same namespace, one with pathType `ImplementationSpecific` and one with `Prefix`, and those are working:

```yaml
  - host: monitoring.dev.hivestreaming.net
    http:
      paths:
      - backend:
          serviceName: monitoring-kube-prometheus-alertmanager
          servicePort: 9093
        path: /prometheus-alert-manager
        pathType: ImplementationSpecific
```

```yaml
  - host: monitoring.dev.hivestreaming.net
    http:
      paths:
      - backend:
          serviceName: monitoring-prometheus-thanos-querier
          servicePort: 9090
        path: /prometheus
        pathType: Prefix
```

On a whim, I tested to change the pathType of the second one to `ImplementationSpecific` to see what would happen, expecting the monitoring.dev.hivestreaming.net frontend to disappear. And it did, but at the same time, the grafana.dev.hivestreaming.net frontend was added (still ImplementationSpecific)!.

To summarize:

With the original configuration I have pasted above,
* grafana.dev.hivestreaming.net/ is missing
* monitoring.dev.hivestreaming.net/prometheus-alert-manager is added to _front_https_host__begin_01.map
* monitoring.dev.hivestreaming.net/prometheus is added to _front_https_host__prefix.map

When I set the pathType of monitoring.dev.hivestreaming.net/prometheus and monitoring.dev.hivestreaming.net/prometheus-alert-manager to `ImplementationSpecific`,
* grafana.dev.hivestreaming.net/ is added to _front_https_host__begin.map
* monitoring.dev.hivestreaming.net/prometheus-alert-manager is missing
* monitoring.dev.hivestreaming.net/prometheus is missing

When I set the pathType of monitoring.dev.hivestreaming.net/prometheus and monitoring.dev.hivestreaming.net/prometheus-alert-manager to `Prefix`,
* grafana.dev.hivestreaming.net/ is missing
* monitoring.dev.hivestreaming.net/prometheus-alert-manager is added to _front_https_host__prefix.map
* monitoring.dev.hivestreaming.net/prometheus is added to _front_https_host__prefix.map

When I set the pathType to `Prefix` on all three ingresses,
* grafana.dev.hivestreaming.net/ is added to _front_https_host__prefix.map
* monitoring.dev.hivestreaming.net/prometheus-alert-manager is added to _front_https_host__prefix.map
* monitoring.dev.hivestreaming.net/prometheus is added to _front_https_host__prefix.map
