### ISSUE TITLE
LUA socket.http module missing in external haproxy side-car

### ISSUE THREAD

**Issue by mhyllander** [jcmoraisjr/haproxy-ingress#738]
I attempted to enable oauth2_proxy support while using an "external" haproxy (running in a side-car container). I set `external-has-lua: "true"`. When I deploy this configuration, haproxy in the side-car crashes.

haproxy outputs the following logs:

```
[NOTICE] 052/155633 (1) : haproxy version is 2.2.9-a947cc2
[ALERT] 052/155633 (1) : parsing [/etc/haproxy/haproxy.cfg:19] : Lua runtime error: /etc/haproxy/lua/auth-request.lua:29: module 'socket.http' not found:
        no field package.preload['socket.http']
        no file '/usr/local/share/lua/5.3/socket/http.lua'
        no file '/usr/local/share/lua/5.3/socket/http/init.lua'
        no file '/usr/local/lib/lua/5.3/socket/http.lua'
        no file '/usr/local/lib/lua/5.3/socket/http/init.lua'
        no file '/usr/share/lua/5.3/socket/http.lua'
        no file '/usr/share/lua/5.3/socket/http/init.lua'
        no file '/usr/lib/lua/5.3/socket/http.lua'
        no file '/usr/lib/lua/5.3/socket/http/init.lua'
        no file '/usr/share/lua/common/socket/http.lua'
        no file '/usr/share/lua/common/socket/http/init.lua'
        no file './socket/http.lua'
        no file './socket/http/init.lua'
        no file '/usr/local/lib/lua/5.3/socket/http.so'
        no file '/usr/local/lib/lua/5.3/loadall.so'
        no file '/usr/lib/lua/5.3/socket/http.so'
        no file '/usr/lib/lua/5.3/loadall.so'
        no file './socket/http.so'
        no file '/usr/local/lib/lua/5.3/socket.so'
        no file '/usr/local/lib/lua/5.3/loadall.so'
        no file '/usr/lib/lua/5.3/socket.so'
        no file '/usr/lib/lua/5.3/loadall.so'
        no file './socket.so'

[ALERT] 052/155633 (1) : parsing [/etc/haproxy/haproxy.cfg:69]: 'http-request' expects , 'wait-for-handshake', 'use-service', 'sc-inc-gpc0(*)', 'sc-inc-gpc1(*)', 'sc-set-gpt0(*)', 'send-spoe-group', 'set-priority-class', 'set-priority-offset', 'do-resolve(*)', 'add-acl(*)', 'add-header', 'allow', 'auth', 'capture', 'del-acl(*)', 'del-header', 'del-map(*)', 'deny', 'disable-l7-retry', 'early-hint', 'redirect', 'reject', 'replace-header', 'replace-path', 'replace-pathq', 'replace-uri', 'replace-value', 'return', 'set-header', 'set-log-level', 'set-map(*)', 'set-method', 'set-mark', 'set-nice', 'set-path', 'set-pathq', 'set-query', 'set-tos', 'set-uri', 'strict-mode', 'tarpit', 'track-sc(*)', 'cache-use', 'silent-drop', 'set-src', 'set-src-port', 'set-dst', 'set-dst-port', 'set-var(*)', 'unset-var(*)', but got 'lua.auth-request'.
[ALERT] 052/155633 (1) : Error(s) found in configuration file : /etc/haproxy/haproxy.cfg
```

**Expected behavior**

haproxy should be able to load the `socket.http` module, but that does not appear to be installed in the standard haproxy image.

**Steps to reproduce the problem**

1. Configure haproxy-ingress using a side-car haproxy. 
2. Configure oauth2_proxy on an ingress.
3. Set `external-has-lua: "true"`.
4. Deploy.

**Environment information**

HAProxy Ingress version: `v0.12`

Command-line options:

```yaml
  - args:
    - --configmap=core/internal-ingress-haproxy
    - --ingress-class=internal
    - --master-socket=/var/run/haproxy/master.sock
    - --sort-backends
    - --default-backend-service=core/internal-ingress-haproxy-default-backend
    - --default-ssl-certificate=core/internal-ingress-cert
    - --reload-strategy=reusesocket
    - --watch-ingress-without-class=true
```

Global options:

```yaml
  backend-server-slots-increment: "100"
  config-frontend: |
    #-------------------------------------------------------------
    capture request header Host len 40
    capture request header User-Agent len 100
    capture request header X-Forwarded-For len 100
    #-------------------------------------------------------------
  dns-hold-obsolete: 30s
  dns-hold-valid: 30s
  dns-resolvers: kubernetes=10.128.0.10
  dynamic-scaling: "true"
  external-has-lua: "true"
  forwardfor: update
  healthz-port: "10253"
  http-log-format: '%ci:%cp\ [%t]\ %ft\ %b/%s\ %sslv\ %sslc\ %Tq/%Tw/%Tc/%Tr/%Tt\
    %ST\ %B\ %U\ %CC\ %CS\ %tsc\ %ac/%fc/%bc/%sc/%rc\ %sq/%bq\ %hr\ %hs\ %{+Q}r'
  max-connections: "500000"
  prometheus-port: "9101"
  ssl-ciphers: ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384
  ssl-dh-param: core/internal-ingress-secrets
  ssl-options: no-sslv3 no-tlsv10 no-tlsv11 no-tls-tickets
  stats-port: "1936"
  syslog-endpoint: stdout
  syslog-format: raw
  tcp-log-format: '%ci:%cp\ [%t]\ %ft\ %b/%s\ %sslv\ %sslc\ %Tw/%Tc/%Tt\ %B\ %U\ %ts\
    %ac/%fc/%bc/%sc/%rc\ %sq/%bq'
  timeout-stop: 1h
```

Ingress objects:

```yaml
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/cluster-issuer: internal-letsencrypt-prod
    ingress.kubernetes.io/oauth: oauth2_proxy
    kubernetes.io/ingress.class: internal
    meta.helm.sh/release-name: intserv
    meta.helm.sh/release-namespace: core
  labels:
    app: intserv
    app.kubernetes.io/managed-by: Helm
    chart: intserv-0.1.0
    component: hbase-euw
    heritage: Helm
    release: intserv
  name: hbase-euw
  namespace: core
spec:
  rules:
  - host: hbase.euw.test.hivestreaming.net
    http:
      paths:
      - backend:
          serviceName: hbase-euw
          servicePort: 60010
        path: /
        pathType: Prefix
  tls:
  - hosts:
    - hbase.euw.test.hivestreaming.net
    secretName: hbase.euw.test.hivestreaming.net
```
