### ISSUE TITLE
Multiple reloads of haproxy config without any apparent changes

### ISSUE THREAD

**Issue by mhyllander** [jcmoraisjr/haproxy-ingress#745]
After recently migrating from haproxy-ingress 0.7.6 to 0.12.1 (!), I saw a change in behavior when rolling out a new version of a service deployment. haproxy reloaded it's configuration multiple times during the rollout, apparently without any changes to the configuration.

We have a service with very long-lived websocket connections. Therefore we have configured haproxy-ingress to avoid restarting and dropping those connections as much as possible. We are using reusesockets, dynamic scaling and DNS resolvers. We also set `timeout-stop` to 24h so that existing connections are kept alive, so that most clients have time to re-connect during the next 24h. (If we didn't do this we would get a burst of clients re-connecting at the same time.)

What happened is that our service with 30 pods was rolled out with 6 pods at a time. At each rollout step, haproxy forked another instance, so the haproxy-ingress pod memory usage grew in steps, and of course the count of current connections restarted from zero each time.

Note also that I am running an "external" haproxy in a side-car.

**Expected behavior**

Since backend server discovery is done through DNS lookups, haproxy.cfg does not change, so there should not be a need to restart haproxy. (Even if we didn't use DNS lookups, dynamic scaling should have allowed updates without restarting haproxy.) This is the way it used to work in 0.7.6.

**Steps to reproduce the problem**

 

**Environment information**

HAProxy Ingress version: `v0.12.1`

Command-line options:

```
  - args:
    - --configmap=core/re-ingress-haproxy
    - --ingress-class=re
    - --master-socket=/var/run/haproxy/master.sock
    - --sort-backends
    - --default-backend-service=core/re-ingress-haproxy-default-backend
    - --default-ssl-certificate=core/re-ingress-cert
    - --reload-strategy=reusesocket
    - --watch-ingress-without-class=true
```

Global options:

```
data:
  backend-server-slots-increment: "100"
  config-frontend: |
    #-------------------------------------------------------------
    capture request header Host len 40
    capture request header User-Agent len 100
    capture request header X-Forwarded-For len 100
    #-------------------------------------------------------------
  dns-hold-obsolete: 30s
  dns-hold-valid: 30s
  dns-resolvers: kubernetes=10.128.0.10
  dynamic-scaling: "true"
  forwardfor: update
  healthz-port: "10253"
  http-log-format: '%ci:%cp\ [%t]\ %ft\ %b/%s\ %sslv\ %sslc\ %Tq/%Tw/%Tc/%Tr/%Tt\
    %ST\ %B\ %U\ %CC\ %CS\ %tsc\ %ac/%fc/%bc/%sc/%rc\ %sq/%bq\ %hr\ %hs\ %{+Q}r'
  max-connections: "500000"
  prometheus-port: "9101"
  ssl-ciphers: ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384
  ssl-dh-param: core/re-ingress-secrets
  ssl-options: no-sslv3 no-tlsv10 no-tlsv11 no-tls-tickets
  stats-port: "1936"
  syslog-endpoint: stdout
  syslog-format: raw
  tcp-log-format: '%ci:%cp\ [%t]\ %ft\ %b/%s\ %sslv\ %sslc\ %Tw/%Tc/%Tt\ %B\ %U\ %ts\
    %ac/%fc/%bc/%sc/%rc\ %sq/%bq'
  timeout-client: 2m
  timeout-stop: 24h
```

Ingress objects:

```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    ingress.kubernetes.io/use-resolver: kubernetes
    kubernetes.io/ingress.class: re
    meta.helm.sh/release-name: re-worker-service
    meta.helm.sh/release-namespace: platform
  labels:
    app: re-worker-service
    app.kubernetes.io/managed-by: Helm
    appType: finagle
    chart: re-worker-service-0.1.0
    heritage: Helm
    release: re-worker-service
  name: re-worker-service
  namespace: platform
spec:
  rules:
  - host: api-groot-prod.hivestreaming.com
    http:
      paths:
      - backend:
          serviceName: re-worker-service
          servicePort: http
        path: /v1/selftest
        pathType: Prefix
      - backend:
          serviceName: re-worker-service
          servicePort: admin
        path: /admin/ping
        pathType: Prefix
  - host: peers.hivestreaming.com
    http:
      paths:
      - backend:
          serviceName: re-worker-service
          servicePort: http
        path: /v1/selftest
        pathType: Prefix
      - backend:
          serviceName: re-worker-service
          servicePort: admin
        path: /admin/ping
        pathType: Prefix
  tls:
  - hosts:
    - api-groot-prod.hivestreaming.com
    - peers.hivestreaming.com
    secretName: re-worker-service-cert
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    ingress.kubernetes.io/agent-check-port: "9991"
    ingress.kubernetes.io/initial-weight: "100"
    ingress.kubernetes.io/timeout-tunnel: 60s
    ingress.kubernetes.io/use-resolver: kubernetes
    kubernetes.io/ingress.class: re
    meta.helm.sh/release-name: re-worker-service
    meta.helm.sh/release-namespace: platform
  labels:
    app: re-worker-service
    app.kubernetes.io/managed-by: Helm
    appType: finagle
    chart: re-worker-service-0.1.0
    heritage: Helm
    release: re-worker-service
  name: re-worker-service-websocket
  namespace: platform
spec:
  rules:
  - host: api-groot-prod.hivestreaming.com
    http:
      paths:
      - backend:
          serviceName: re-worker-service-websocket
          servicePort: websocket
        path: /v1/peer
        pathType: Prefix
  - host: peers.hivestreaming.com
    http:
      paths:
      - backend:
          serviceName: re-worker-service-websocket
          servicePort: websocket
        path: /v1/peer
        pathType: Prefix
  tls:
  - hosts:
    - api-groot-prod.hivestreaming.com
    - peers.hivestreaming.com
    secretName: re-worker-service-cert
```

This results in the following backend configurations:

```
backend platform_re-worker-service-websocket_8001
    mode http
    balance roundrobin
    timeout tunnel 60s
    acl https-request ssl_fc
    http-request redirect scheme https if !https-request
    option forwardfor
    http-response set-header Strict-Transport-Security "max-age=15768000"
    server-template srv 100 re-worker-service-websocket.platform.svc.cluster.local:8001 resolvers kubernetes resolve-prefer ipv4 init-addr none weight 100 check inter 2s agent-check agent-port 9991
backend platform_re-worker-service_admin
    mode http
    balance roundrobin
    acl https-request ssl_fc
    http-request redirect scheme https if !https-request
    option forwardfor
    http-response set-header Strict-Transport-Security "max-age=15768000"
    server-template srv 100 _admin._tcp.re-worker-service.platform.svc.cluster.local resolvers kubernetes resolve-prefer ipv4 init-addr none weight 1 check inter 2s
backend platform_re-worker-service_http
    mode http
    balance roundrobin
    acl https-request ssl_fc
    http-request redirect scheme https if !https-request
    option forwardfor
    http-response set-header Strict-Transport-Security "max-age=15768000"
    server-template srv 100 _http._tcp.re-worker-service.platform.svc.cluster.local resolvers kubernetes resolve-prefer ipv4 init-addr none weight 1 check inter 2s
```

In an haproxy container, it looked like this after the rollout:

```
$ kprod -n core exec re-ingress-haproxy-2zrcx -c haproxy -it -- sh
/ # ps -f
PID   USER     TIME  COMMAND
    1 root      0:01 haproxy -sf 120 117 103 100 97 94 91 88 37 34 31 28 25 22 19 16 13 10 7 -x /var/run/haproxy/admin.sock -W -db -W -S /var/run/haproxy/master.sock,mode,600 -f /etc/haproxy
    7 root      6:44 haproxy -W -db -W -S /var/run/haproxy/master.sock,mode,600 -f /etc/haproxy
   10 root      0:42 haproxy -sf 7 -x /var/run/haproxy/admin.sock -W -db -W -S /var/run/haproxy/master.sock,mode,600 -f /etc/haproxy
   13 root      0:37 haproxy -sf 10 7 -x /var/run/haproxy/admin.sock -W -db -W -S /var/run/haproxy/master.sock,mode,600 -f /etc/haproxy
   16 root      0:35 haproxy -sf 13 10 7 -x /var/run/haproxy/admin.sock -W -db -W -S /var/run/haproxy/master.sock,mode,600 -f /etc/haproxy
   19 root      0:34 haproxy -sf 16 13 10 7 -x /var/run/haproxy/admin.sock -W -db -W -S /var/run/haproxy/master.sock,mode,600 -f /etc/haproxy
   22 root      0:34 haproxy -sf 19 16 13 10 7 -x /var/run/haproxy/admin.sock -W -db -W -S /var/run/haproxy/master.sock,mode,600 -f /etc/haproxy
   25 root      0:33 haproxy -sf 22 19 16 13 10 7 -x /var/run/haproxy/admin.sock -W -db -W -S /var/run/haproxy/master.sock,mode,600 -f /etc/haproxy
   28 root      0:33 haproxy -sf 25 22 19 16 13 10 7 -x /var/run/haproxy/admin.sock -W -db -W -S /var/run/haproxy/master.sock,mode,600 -f /etc/haproxy
   31 root      0:35 haproxy -sf 28 25 22 19 16 13 10 7 -x /var/run/haproxy/admin.sock -W -db -W -S /var/run/haproxy/master.sock,mode,600 -f /etc/haproxy
   34 root      0:29 haproxy -sf 31 28 25 22 19 16 13 10 7 -x /var/run/haproxy/admin.sock -W -db -W -S /var/run/haproxy/master.sock,mode,600 -f /etc/haproxy
   37 root      6:53 haproxy -sf 34 31 28 25 22 19 16 13 10 7 -x /var/run/haproxy/admin.sock -W -db -W -S /var/run/haproxy/master.sock,mode,600 -f /etc/haproxy
   88 root      0:19 haproxy -sf 37 34 31 28 25 22 19 16 13 10 7 -x /var/run/haproxy/admin.sock -W -db -W -S /var/run/haproxy/master.sock,mode,600 -f /etc/haproxy
   91 root      0:17 haproxy -sf 88 37 34 31 28 25 22 19 16 13 10 7 -x /var/run/haproxy/admin.sock -W -db -W -S /var/run/haproxy/master.sock,mode,600 -f /etc/haproxy
   94 root      2:31 haproxy -sf 91 88 37 34 31 28 25 22 19 16 13 10 7 -x /var/run/haproxy/admin.sock -W -db -W -S /var/run/haproxy/master.sock,mode,600 -f /etc/haproxy
   97 root      0:11 haproxy -sf 94 91 88 37 34 31 28 25 22 19 16 13 10 7 -x /var/run/haproxy/admin.sock -W -db -W -S /var/run/haproxy/master.sock,mode,600 -f /etc/haproxy
  100 root      0:11 haproxy -sf 97 94 91 88 37 34 31 28 25 22 19 16 13 10 7 -x /var/run/haproxy/admin.sock -W -db -W -S /var/run/haproxy/master.sock,mode,600 -f /etc/haproxy
  103 root      2:10 haproxy -sf 100 97 94 91 88 37 34 31 28 25 22 19 16 13 10 7 -x /var/run/haproxy/admin.sock -W -db -W -S /var/run/haproxy/master.sock,mode,600 -f /etc/haproxy
  117 root      0:04 haproxy -sf 103 100 97 94 91 88 37 34 31 28 25 22 19 16 13 10 7 -x /var/run/haproxy/admin.sock -W -db -W -S /var/run/haproxy/master.sock,mode,600 -f /etc/haproxy
  120 root      0:05 haproxy -sf 117 103 100 97 94 91 88 37 34 31 28 25 22 19 16 13 10 7 -x /var/run/haproxy/admin.sock -W -db -W -S /var/run/haproxy/master.sock,mode,600 -f /etc/haproxy
  123 root      1:13 haproxy -sf 120 117 103 100 97 94 91 88 37 34 31 28 25 22 19 16 13 10 7 -x /var/run/haproxy/admin.sock -W -db -W -S /var/run/haproxy/master.sock,mode,600 -f /etc/haproxy
```

Here's a snapshot of the number of connections during the rollout (there were some problems with the service initially). You can see how haproxy forks a new instance in all haproxy-ingress pods with each new step of the deployment rollout. (But note also that there seem to be many more haproxy instances running in the example above than just four or five.):

![image](https://user-images.githubusercontent.com/3501939/109531976-dfaa8e80-7ab8-11eb-8a74-0c0b73eb89a2.png)
