### ISSUE TITLE
Request path that contains a hostname results in wrong routing

### ISSUE THREAD

**Issue by chitoku-k** [jcmoraisjr/haproxy-ingress#753]
**Description of the problem**

Let's say we have the ingress in the last section of this issue. This ingress only specifies that it should route traffic by its hostname; however, when the request path contains a subdomain, it routes to a wrong one as in the following:

OK: example.com goes to nginx-alice
```
$ curl example.com
nginx-alice-7f9b8cd46d-8rll5
```

OK: subdomain.example.com goes to nginx-bob
```
$ curl subdomain.example.com
nginx-bob-848d7b78d9-sv4cv
```

WRONG: subdomain.example.com/example.com goes to **nginx-alice**
```
$ curl subdomain.example.com/example.com
nginx-alice-7f9b8cd46d-8rll5
```

**Expected behavior**

example.com goes to nginx-alice
```
$ curl example.com
nginx-alice-7f9b8cd46d-8rll5
```

subdomain.example.com goes to nginx-bob
```
$ curl subdomain.example.com
nginx-bob-848d7b78d9-sv4cv
```

subdomain.example.com/example.com goes to **nginx-bob**
```
$ curl subdomain.example.com/example.ocm
nginx-bob-848d7b78d9-sv4cv
```

**Steps to reproduce the problem**

1. Deploy the following manifest to a Kubernetes cluster:
    (It contains two nginx Pods that print each Pod name respectively whatever path it is given)
    ```yaml
    ---
    apiVersion: v1
    kind: ConfigMap
    metadata:
      name: nginx-conf
      namespace: default
    data:
      default.conf.template: |
        server {
          listen 80 default;
          listen [::]:80 default;
          server_name _;
          keepalive_timeout 0;
    
          location / {
            add_header Content-Type text/plain;
            return 200 "$BODY\n";
          }
        }
    ---
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: nginx-alice
      namespace: default
    spec:
      replicas: 1
      selector:
        matchLabels:
          app: nginx-alice
      template:
        metadata:
          labels:
            app: nginx-alice
        spec:
          containers:
            - name: web
              image: nginx:1.19.7-alpine
              env:
                - name: BODY
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.name
              volumeMounts:
                - name: nginx-conf
                  mountPath: /etc/nginx/templates
              ports:
                - name: http
                  containerPort: 80
          volumes:
            - name: nginx-conf
              configMap:
                name: nginx-conf
    ---
    apiVersion: v1
    kind: Service
    metadata:
      name: nginx-alice
      namespace: default
    spec:
      ports:
        - name: http
          protocol: TCP
          port: 80
          targetPort: 80
      selector:
        app: nginx-alice
    ---
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: nginx-bob
      namespace: default
    spec:
      replicas: 1
      selector:
        matchLabels:
          app: nginx-bob
      template:
        metadata:
          labels:
            app: nginx-bob
        spec:
          containers:
            - name: web
              image: nginx:1.19.7-alpine
              env:
                - name: BODY
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.name
              volumeMounts:
                - name: nginx-conf
                  mountPath: /etc/nginx/templates
              ports:
                - name: http
                  containerPort: 80
          volumes:
            - name: nginx-conf
              configMap:
                name: nginx-conf
    ---
    apiVersion: v1
    kind: Service
    metadata:
      name: nginx-bob
      namespace: default
    spec:
      ports:
        - name: http
          protocol: TCP
          port: 80
          targetPort: 80
      selector:
        app: nginx-bob
    ```
2. Deploy the ingress in the previous section
3. `curl` to HAProxy

**Environment information**

HAProxy Ingress version: `v0.11` and `v0.12` (**NOT reproducible in `v0.10`**)

Command-line options:

```
--configmap=ingress-controller/haproxy-ingress
```

Global options:

```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: haproxy-ingress
  namespace: ingress-controller
data:
  bind-http: ':80,:::80'
```

Ingress objects:

```yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress
  namespace: default
spec:
  rules:
    - host: example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: nginx-alice
                port:
                  number: 80
    - host: subdomain.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: nginx-bob
                port:
                  number: 80
```
