### ISSUE TITLE
error reading IngressClass 'haproxy': ingressclass.networking.k8s.io "haproxy" not found

### ISSUE THREAD

**Issue by gauravmeena83** [jcmoraisjr/haproxy-ingress#765]
**Description of the problem**

haproxy-ingress-65575455f5-6j4g4 haproxy-ingress W0417 05:55:56.444132       6 cache.go:585] error reading IngressClass 'haproxy': ingressclass.networking.k8s.io "haproxy" not found
haproxy-ingress-65575455f5-6j4g4 haproxy-ingress W0417 05:55:56.444149       6 cache.go:585] error reading IngressClass 'nginx': ingressclass.networking.k8s.io "nginx" not found

**Expected behavior**

HAproxy should be able to identify the ingreses and ingressclass

**Steps to reproduce the problem**

1. install haproxy as per the helm chart given here
2. create a loadbalancer service for the ingress controller with statis IP assigned, so that kuve-vip can pick and loadbalanc the service
3. logs of the controller stern -n haproxy-ingress haproxy-ingress

**Environment information**

HAProxy Ingress version: `v0.12.3`

Command-line options:

```
            - --configmap=haproxy-ingress/haproxy-ingress
            - --ingress-class=haproxy
            - --sort-backends
```

Global options:

```
      dnsPolicy: ClusterFirst
      hostNetwork: false
```

Ingress objects:

```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: echoserver
  namespace: default
  annotations:
    # # kubernetes.io/ingress.class: haproxy
    # # service.beta.kubernetes.io/external-traffic: OnlyLocal
spec:
  ingressClassName: "haproxy"
  rules:
  - host: echoserver.cluster.local
    http:
      paths:
      - backend:
            service:
              name: echoserver
              port:
                number: 80
        path: /
        pathType: Prefix
```

**Comment by jcmoraisjr** [comment]
Do you have an ingressClass resource named haproxy? See k8s ref doc: https://kubernetes.io/docs/concepts/services-networking/ingress/#ingress-class and also HAProxy Ingress one: https://haproxy-ingress.github.io/docs/configuration/command-line/#ingress-class

**Comment by gauravmeena83** [comment]
> Do you have an ingressClass resource named haproxy? See k8s ref doc: https://kubernetes.io/docs/concepts/services-networking/ingress/#ingress-class and also HAProxy Ingress one: https://haproxy-ingress.github.io/docs/configuration/command-line/#ingress-class

No there is no ingressclass resource in the cluster. (k get ingressclass -A) .... I hoped it to be created automatically. Anyway I have added the ingressclass as 
```
apiVersion: networking.k8s.io/v1
kind: IngressClass
metadata:
  name: haproxy
spec:
  controller: haproxy-ingress.github.io/controller
```
I am still on "no route to host" .... the class error has stopped since than however. Lemme know if it correct.

I am new to kubernetes, the nginx controller just worked, but I am attracted to Haproxy for its efficiency, but unable to get it worked. I am yet to see the "page not found" of haproxy. so even ingress resource is not improtant here. I am still not getting packet inside the pod/controller.

STEPS:
I created a new single master 1.20.2 cluster, and deployed metallb and haproxy in their default setting. kube-proxy was set to IPVS, StrictARP before. I can see the network entry for loadbalancer IP in kube-ipvs0, ping goes through, curl doesn't.
