### ISSUE TITLE
TCP services not added when secret not found

### ISSUE THREAD

**Issue by bartversluijs** [jcmoraisjr/haproxy-ingress#768]
**Before looking into this issue**. 
I've tried it a second time and it worked without restarting HAProxy on K8s version 1.19.6. I'll try it a couple of times more, just to be sure!

**Description of the problem**

I've added a TCP service with SSL to the HAProxy config like this:
```
3129: "default/openbalena-vpn:3128:::default/openbalena-http-tunnel-tls"
```

So the `default/openbalena-http-tunnel-tls` is the secret for the TLS.  
However, this secret is created by the Ingress and the ACME challenge is completed by HAProxy. It probably doesn't exist at the time that the HAProxy controller booted, so it won't add it. But in other cases, like a normal Ingress host, it uses a default certificate and reloads if the secret is updated.

**Expected behavior**

Add the TCP service with a default certificate and reload when the secret is available and / or updated.

**Steps to reproduce the problem**

1. Add a TCP service with TLS;
2. Create the secret after the TCP is added;
3. The TCP service is not added to HAProxy and will not be available until a reboot took place.

**Environment information**

HAProxy Ingress version: `v0.13.0-s2-r1`

Command-line options:

```
--configmap=default/openbalena-haproxy
--ingress-class=openbalena-haproxy
--sort-backends
--tcp-services-configmap=default/openbalena-haproxy-tcp
```

Global options:

```

```

Ingress objects:

```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: openbalena-ingress-tunnel
  labels:
    app: openbalena
    component: ingress
  annotations:
    kubernetes.io/ingress.class: "openbalena-haproxy"
    cert-manager.io/cluster-issuer: "openbalena-cluster-issuer"

    ingress.kubernetes.io/ssl-passthrough: "true"
    ingress.kubernetes.io/server-alias: "tunnel.{{ index .Values "hostname" }}"
spec:
  tls:
  - hosts:
    - tunnel.{{ index .Values "hostname" }}
    secretName: openbalena-http-tunnel-tls
  rules:
  - host: tunnel.{{ index .Values "hostname" }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: openbalena-haproxy
            port:
              number: 3129
```
