### ISSUE TITLE
Sudden RST spikes

### ISSUE THREAD

**Issue by zapman449** [jcmoraisjr/haproxy-ingress#77]
Periodically[1] we see spikes of HaProxy generated RST packets to active connections.  Only one node in the cluster does this at any given time.  That host only sends RST packets to all[2] connections from a single client IP.  Other client IP's connections are unharmed.  Further, all the RST packets are sent at the same millisecond.

I can see this behavior in the AWS CloudWatch graphs, and I've been able to see them with tcpdump as well.

Things I've tried:
1. The logs have not been helpful.  The logs from `haproxy-ingress-lb` container do not show any events at that time.  We've setup an rsyslog server side-car for this daemonset, and the logs from there are curiously blank at the second this occurs.
2. There are no relevant kubernetes events which match in time.
3. No backend pods which ingress is interested in are failing at these times.

I would love some help with triage.  At this time, I can't tell if this is an Ingress-controller issue, a config issue or an haproxy issue.

Other details:
1. haproxy-ingress is running as a daemonset on all worker nodes
2. The only difference in haproxy config between the two clusters is the list of allowed TLS Ciphers.
3. Here's the config map (minus the ciphers):

```
data:
  http-log-format: |
    {\"type\":\"haproxy-ingress\",\"protocol\":\"http\",\"timestamp\":\"%t\",\"client_ip\":%{+Q}ci,\"client_port\":%{+Q}cp,\"frontend_name\":%{+Q}ft,\"backend_name\":%{+Q}b,\"backend_ip\":%{+Q}s,\"time_handshake\":%{+Q}Th,\"time_idle_before_request\":%{+Q}Ti,\"time_receive_full_request\":%{+Q}TR,\"time_wait_send_backend\":%{+Q}Tw,\"time_backend_ack\":%{+Q}Tc,\"time_backend_processing\":%{+Q}Tr,\"time_delay_send_to_client\":%{+Q}Td,\"waittime_on_client\":%{+Q}Tq,\"active_request_time\":%{+Q}Ta,\"total_request_time\":%{+Q}Tt,\"http_status_code\":%{+Q}ST,\"client_bytes_uploaded\":%{+Q}U,\"bytes_sent\":%{+Q}B,\"termination_status\":\"%tsc\",\"active_conns\":%{+Q}ac,\"frontend_conns\":%{+Q}fc,\"backend_conns\":%{+Q}bc,\"server_conns\":%{+Q}sc,\"retry_conns\":%{+Q}rc,\"server_queue\":%{+Q}sq,\"backend_queue\":%{+Q}bq,\"request\":%{+Q,+E}r}
  max-connections: "4096"
  ssl-options: force-tlsv12 no-tlsv10 no-tlsv11 no-sslv3
  syslog-endpoint: 127.0.0.1:514
  timeout-http-request: 30s
  use-proxy-protocol: "false"
```

[1] Periodically: In one cluster we see this behavior approximately every 10 minutes.  In a different cluster with a different workload pattern we see it approximately every 2 hours.
[2] All: I have not proved that all connections from a single IP are reset.  I certainly see between 2 and 20 connections from the same client IP.  When this happens, multiple connections from a single client IP are killed.
