### ISSUE TITLE
Using "Exact" pathType and "Prefix" pathType for the same path ignores one of them

### ISSUE THREAD

**Issue by mahcinek** [jcmoraisjr/haproxy-ingress#770]
**Description of the problem**

I'm trying to point to two backend resources using the ingress controller. One of them should be accessible on the root path and the other should be accessible on any other path. Unfortunately the ingress controller seems to ignore one of the path configurations (I believe it's always the later one in the ingress) which use the standard Kubernetes notation ("Exact" and "Prefix").

**Expected behavior**

Ingress controller points to the be-1 service on the root path and to be-2 on any other path.

**Steps to reproduce the problem**

1.  Create two different pods
2.  Create two services that expose them
3.  Use an ingress configuration similar to the one provided here

**Environment information**

HAProxy Ingress version: `v0.13`

Command-line options: default

Global options: default

Ingress objects:

```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: haproxy
  name: example-ingress
  namespace: default
spec:
  rules:
  - http:
      paths:
      - pathType: Exact
        path: /
        backend:
          service:
            name: be-1
            port: 
              number: 80
      - pathType: Prefix
        path: /
        backend:
          service:
            name: be-2
            port: 
              number: 80
```
