### ISSUE TITLE
mTLS support without using sni

### ISSUE THREAD

**Issue by ndbemmanuel** [jcmoraisjr/haproxy-ingress#786]
Is it possible to add support to have mutual TLS authentication without having SNI support.  We have deployed devices that need to have mutual TLS authentication and doesn’t support SNI.  We did get a somewhat working solution by having the following config :
```
bind-https: ":443 ssl crt /var/lib/haproxy/crt/sw0081-dev_sw0081-srv.pem.pem ca-file /var/lib/haproxy/cacerts/ca_sw0081-dev_sw0081-ca.pem.pem verify optional"

config-frontend
        http-request set-var(req.hostbackend) var(req.base),map_dir(/etc/haproxy/maps/_front_https_sni__prefix.map) if !{ var(req.hostbackend) -m found }
        acl tls-has-invalid-crt ssl_c_ca_err gt 0
        acl tls-has-invalid-crt ssl_c_err gt 0
        acl tls-need-crt hdr(host) -i -m str -f /etc/haproxy/maps/_front_tls_needcrt__exact.list
        acl tls-check-crt hdr(host)  -i -m str -f /etc/haproxy/maps/_front_tls_auth__exact.list
        http-request set-var(req.tls_invalidcrt_redir) str(_internal) if tls-has-invalid-crt tls-check-crt
```
In sort, it’s a copy the SNI config but applied to the host header field

But that solution has some problems:
- The container will crash before the required ingress rules are created with a file not found
- Modification of the ingress rules like adding a path prefix rule will break the fronted
- It is applied both to HTTP and HTTPS front end
- Depends of the internal working of the load balancer

Our suggestion:
- Have an option to ingress annotation would tell that the endpoint needs to be accessible using only the host header field.
  - Set the HTTPS binding to have verify optional
  - Configure the front end to validate both with and without the SNI
  - Configure the front end to find the correct back end with and without SNI

**Comment by jcmoraisjr** [comment]
Iirc the details of this functionality, the SNI extension has three roles:

- choose a proper server certificate to the client;
- defines if mTLS should be used and use a proper CA bundle;
- if a client certificate is provided, guarantee that the client was properly authenticated before forward the request.

The first two options is a matter of configuring mTLS in the default backend, but HAProxy Ingress currently doesn't do this and I'll take care. The third and last option compares SNI and Host header if a certificate was provided, this behavior can be changed on behalf of a less secure deployment, which isn't a problem at all if all of your clients use the same CA bundle.

Is this approach useful in your use case?

**Comment by ndbemmanuel** [comment]
Yes, that would be useful.  
We only have one host name that requires to support non-sni configuration  It is also currently the only host name that currently require mTLS. It would cover actual use cases and allow to set the configuration without knowing the internal working of the haproxy.cfg configuration.

**So, It will cover these required use cases:**

- Client not supporting SNI connecting to the host requiring mTLS
  - Connect and be authenticated with default front-end config
  - Host name should be validated to be allowed to use non-SNI configuration (that one would be an improvement from my workaround and would need an annotation to ingress)

- Client not supporting SNI without TLS
  - Access must be granted to host not requiring mTLS 
  - Access must be denied to host requiring mTLS

- Client with SNI (with or without mTLS)
  - Continue to work as it is currently
  - Client using SNI with hostname allowed non SNI mTLS must work (Would allow upgraded devices that now support SNI to continue to work)

**Non required use case but may be useful for someone else and is not covered by the solution:**
- Client not supporting SNI connecting to host requiring mTLS
  - Using a consolidated CA bundle and validating ssl_c_i_dn to allow only the correct host bundle
    - It may have side effects in the case of clients having client certificates for multiple host when the browser try to choose the correct one.  But modern browser should support SNI
    - Useful only for devices where the configuration is explicitly set.

**Comment by mogoman** [comment]
hi jcmoraisjr 

I am working on certifying my cluster with a large provider and it seems they don't support SNI - it was difficult to debug that until I finally did `curl https://<ip address>` and got the same error in my logs vs the query from the vendor:

```
2024-09-23T17:42:51.159898544Z 2024-09-23T17:42:51+00:00 127.0.0.1 1 2024-09-23T17:42:51.159750+00:00 - ingress 4697 - - 10.42.6.110:44780 [23/Sep/2024:17:42:51.124] _front_https/1: SSL handshake failure
```

mTLS with the fqdn works fine in my tests, but it seems the remote server at the vendor doesn't support this; they are resolving and then using the IP.

I'm happy to create a dedicated ingress controller or even cluster, if this is possible?

Thanks

**Comment by mstavrev** [comment]
Hi @jcmoraisjr, 

I am having the same issue - devices with outdated SSL support, not providing the SNI extension upon connection, but authenticating using client certificate.

I'd like to migrate from Nginx ingress where this has been setup and works fine.

Is there any way to achieve it with either 0.15 or the 0.16 beta version?

Best Regards

**Comment by jcmoraisjr** [comment]
Thanks for bringing this one to our attention (again).

It works by changing SNI matching to Host header matching instead, just like in OP description? You configure it per host or is it a global configuration instead? Anything more you'd add from the description?

**Comment by mstavrev** [comment]
> Thanks for bringing this one to our attention (again).
> 
> It works by changing SNI matching to Host header matching instead, just like in OP description? You configure it per host or is it a global configuration instead? Anything more you'd add from the description?

I am trying to do everything through the helm chart deployment.

1. I've setup the default TLS certificate (it is covering the host used to access the controller's TLS port), being wildcard certificate. For the example, let's say *.test.net
2. Since the devices connecting are with outdated SSL implementation, to let them pass the TLS handshake, I had added these

```
controller:
  config:
    ssl-options: "ssl-min-ver TLSv1.0 ssl-max-ver TLSv1.2"
    # Cipher list for TLS ≤ 1.2
    ssl-ciphers: "ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-AES256-GCM-SHA384:DHE-RSA-AES128-GCM-SHA256:DHE-DSS-AES128-GCM-SHA256:kEDH+AESGCM:ECDHE-RSA-AES128-SHA256:ECDHE-ECDSA-AES128-SHA256:ECDHE-RSA-AES128-SHA:ECDHE-ECDSA-AES128-SHA:ECDHE-RSA-AES256-SHA384:ECDHE-ECDSA-AES256-SHA384:ECDHE-RSA-AES256-SHA:ECDHE-ECDSA-AES256-SHA:DHE-RSA-AES128-SHA256:DHE-RSA-AES128-SHA:DHE-DSS-AES128-SHA256:DHE-RSA-AES256-SHA256:DHE-DSS-AES256-SHA:DHE-RSA-AES256-SHA:AES128-GCM-SHA256:AES256-GCM-SHA384:AES128-SHA256:AES256-SHA256:AES128-SHA:AES256-SHA:AES:CAMELLIA:DES-CBC3-SHA:!aNULL:!eNULL:!EXPORT:!DES:!RC4:!MD5:!PSK:!aECDH:!EDH-DSS-DES-CBC3-SHA:!EDH-RSA-DES-CBC3-SHA:!KRB5-DES-CBC3-SHA:@SECLEVEL=0"
```

3. I have an ingress resource (redacted for brevity and privacy):

```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    haproxy-ingress.github.io/auth-tls-cert-header: "true"
    haproxy-ingress.github.io/auth-tls-pass-certificate-to-upstream: "true"
    haproxy-ingress.github.io/auth-tls-secret: xxx/auth-ca-chain-secret
    haproxy-ingress.github.io/auth-tls-verify-client: optional
  name: xxx
  namespace: xxx
spec:
  ingressClassName: haproxy
  rules:
  - host: host1.test.net
    http:
      paths:
      - backend:
          service:
            name: xxx
            port:
              number: 80
        path: /
        pathType: ImplementationSpecific
  tls:
  - hosts:
    - host1.test.net
    secretName: default-tls-secret
```

When a client with modern SSL implementation and TLS support makes a request to host1.test.net with client certificate valid in terms of xxx/auth-ca-chain-secret, I can see the proper values under x-ssl-client-* headers reaching my back-end service.

When an outdated client, makes request to host1.test.net, the handshake passes, HAProxy controller properly routes the request to my back-end service, but the x-ssl-client-* headers are all empty (still present on the request if that matters).

I've also tried setting up the ingress resource, omitting the host under the rules and tls section, relying on connection being terminated with the default TLS certificate (same as default-tls-secret anyway), the handshake is successful again for both old and modern SSL client, but in both cases the x-ssl-client-* headers are all empty.

I've tried to understand the OP's approach, but I am very new to HAProxy, so pardon me for not trying it (if possible to be setup via the helm chart deployment). He also mentions of several problems, which may or may not be affecting my setup.

Best Regards
