### ISSUE TITLE
cert not issuing after ingress update to v.0.12

### ISSUE THREAD

**Issue by pbabilas** [jcmoraisjr/haproxy-ingress#787]
After upgrade to v0.12 from v0.10 my ingress stops issuing existing certs. Problem is when tls has more than one hosts in tls configuration:

```  
- hosts:
    - ua.tutumi.pl
    - www.ua.tutumi.pl
    secretName: ua-tutumi-tls
  - hosts:
    - lazienka-rea.bg
    secretName: lazienka-bg-tls
```
First one is not working, ingress is not issuing new cert, but second one works fine. My configuration is same as was before on 0.10 and there it was working.
