### ISSUE TITLE
HAProxy backend is marked as DOWN even though cfg has working Pods listed as servers

### ISSUE THREAD

**Issue by mkubaczyk** [jcmoraisjr/haproxy-ingress#807]
**Description of the problem**

HAProxy is reporting specific backend to be DOWN even though two servers are listed in the configuration file for that backend. I confirmed these two servers were pointing at existing, working Pods of a service.

Having a chance while this happened for us, I quickly run stats on port 1936 and found out that:

<img width="1670" alt="Screenshot 2021-06-23 at 11 38 22" src="https://user-images.githubusercontent.com/12384536/123092451-c4c6a600-d42a-11eb-92a7-d368f8f73f27.png">

even though at the same time HAProxy had a configuration of:

```/etc/haproxy # cat haproxy5-backend324.cfg 
  # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #
# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #
# #
# #   HAProxy Ingress Controller
# #   --------------------------
# #   This file is automatically updated, do not edit
# #
#
backend connect_audit-report_6280
    mode http
    balance leastconn
    timeout queue 10s
    timeout server 300s
    http-request set-header X-Original-Forwarded-For %[hdr(x-forwarded-for)] if { hdr(x-forwarded-for) -m found }
    http-request del-header x-forwarded-for
    option forwardfor
    server srv007 10.147.65.36:6280 weight 1 check inter 2s
    server srv008 10.147.65.94:6280 weight 1 check inter 2s
    server srv003 127.0.0.1:1023 disabled weight 1 check inter 2s
    server srv004 127.0.0.1:1023 disabled weight 1 check inter 2s
    server srv006 127.0.0.1:1023 disabled weight 1 check inter 2s
    server srv005 127.0.0.1:1023 disabled weight 1 check inter 2s
    server srv002 127.0.0.1:1023 disabled weight 1 check inter 2s
    server srv001 127.0.0.1:1023 disabled weight 1 check inter 2s
```
This means srv007 and srv008 is pointing at working Pods but HAProxy does not see them according to stats output above.

It actually lasted for some time according to prometheus metric:

![Untitled](https://user-images.githubusercontent.com/12384536/123093437-fbe98700-d42b-11eb-945b-e2962f4b091b.png)

and only after manual forced restart of one Pod of our service it caused HAProxy to change its location in config to srv003 and hence treat it like UP:

<img width="1670" alt="Screenshot 2021-06-23 at 11 47 10" src="https://user-images.githubusercontent.com/12384536/123093501-13287480-d42c-11eb-81c0-c2829aa1a373.png">

**Expected behavior**

An expected behaviour is for the HAproxy to always represent the state of the cfg file for a backend.

**Steps to reproduce the problem**

I cannot propose anything to reproduce this. We've encountered this few times before but this was the only case we had it ongoing so I had a chance to take some screenshots etc.

**Environment information**

HAProxy Ingress version: `v0.12.2`

Command-line options:

```
    Args:
      --configmap=core/haproxy-ingress-stack-controller-internal
      --ingress-class=haproxy-internal
      --controller-class=internal
      --backend-shards=1000
      –-sort-endpoints-by=endpoint
      --default-backend-service=core/haproxy-ingress-stack-default-backend
      --wait-before-shutdown=310
```

Global options:

```
data:
  config-defaults: |
    option clitcpka
  config-global: |
    tune.ssl.cachesize 1000000
  drain-support: "true"
  healthz-port: "10253"
  hsts: "false"
  max-connections: "10000"
  prometheus-port: "9101"
  ssl-options: ssl-min-ver TLSv1.2
  ssl-redirect: "false"
  stats-port: "1936"
  syslog-endpoint: 127.0.0.1:514
  timeout-client: 20000s
  timeout-client-fin: 1s
  timeout-connect: 5s
  timeout-http-request: 5s
  timeout-keep-alive: 5s
  timeout-queue: 5s
  timeout-server: 30s
  timeout-server-fin: 1s
  timeout-tunnel: 1m
  use-proxy-protocol: "false"
```

Ingress objects:

```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    ingress.kubernetes.io/balance-algorithm: leastconn
    ingress.kubernetes.io/proxy-body-size: unlimited
    ingress.kubernetes.io/timeout-client: 300s
    ingress.kubernetes.io/timeout-queue: 10s
    ingress.kubernetes.io/timeout-server: 300s
  labels:
    [...]
  name: audit-report
spec:
  ingressClassName: haproxy-internal
  rules:
  - host: <some domain>
    http:
      paths:
      - backend:
          service:
            name: audit-report
            port:
              number: 80
        path: /
        pathType: ImplementationSpecific
```
