### ISSUE TITLE
0.12.5 default ingress class keeps reporting error

### ISSUE THREAD

**Issue by alan-marcinkowski** [jcmoraisjr/haproxy-ingress#813]
**Description of the problem**

With an IngressClass that has the annotation ingressclass.kubernetes.io/is-default-class set to "true", the controller keeps reporting an error:

E0705 13:02:45.166196       6 leaderelection.go:325] error retrieving resource lock clu-cluster/haproxy-ingress-ei-map[annotations:map[ingressclass.kubernetes.io/is-default-class:true]]: invalid resource name "haproxy-ingress-ei-map[annotations:map[ingressclass.kubernetes.io/is-default-class:true]]": [may not contain '/']

**Expected behavior**

No error reported

**Steps to reproduce the problem**
Create an ingress class like:
```
apiVersion: networking.k8s.io/v1
kind: IngressClass
metadata:
  annotations:
    ingressclass.kubernetes.io/is-default-class: "true"
  labels:
    app.kubernetes.io/instance: haproxy-ingress
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: haproxy-ingress
    helm.sh/chart: clu-deploy-chart-haproxyingress-1.0.0-SNAPSHOT
  name: haproxy
spec:
  controller: haproxy-ingress.github.io/controller
```
**Environment information**

HAProxy Ingress version: `v0.12.5`

Command-line options:

```
      - args:
        - --default-backend-service=clu-cluster/haproxy-ingress-db
        - --configmap=clu-cluster/haproxy-ingress
        - --election-id=haproxy-ingress-ei
        - --reload-strategy=reusesocket
        - --sort-backends
        - --watch-ingress-without-class
        - --ingress-class=map[annotations:map[ingressclass.kubernetes.io/is-default-class:true]]
        - --publish-service=clu-cluster/haproxy-ingress
        - --alsologtostderr
        - --v=2

```

Global options:

```
  # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #
# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #
# #
# #   HAProxy Ingress Controller
# #   --------------------------
# #   This file is automatically updated, do not edit
# #
#
global
    daemon
    unix-bind mode 0600
    nbthread 2
    cpu-map auto:1/1-2 0-1
    stats socket /var/run/haproxy/admin.sock level admin expose-fd listeners mode 600
    maxconn 2000
    hard-stop-after 10m
    log haproxy-ingress-syslog:514 len 2048 format rfc5424 local0
    log-tag ingress
    lua-load /etc/haproxy/lua/auth-request.lua
    lua-load /etc/haproxy/lua/services.lua
    tune.ssl.default-dh-param 2048
    ssl-default-bind-ciphers ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY13    ssl-default-bind-ciphersuites TLS_AES_128_GCM_SHA256:TLS_AES_256_GCM_SHA384:TLS_CHACHA20_POLY1305_SHA256
    ssl-default-bind-options no-sslv3 no-tlsv10 no-tlsv11 no-tls-tickets
    ssl-default-server-ciphers ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY    ssl-default-server-ciphersuites TLS_AES_128_GCM_SHA256:TLS_AES_256_GCM_SHA384:TLS_CHACHA20_POLY1305_SHA256
```

Ingress objects:

```
None required
```
