### ISSUE TITLE
After deploy ingress with certificates from cert-manager haproxy use default certificates.

### ISSUE THREAD

**Issue by Dryymoon** [jcmoraisjr/haproxy-ingress#822]
**Description of the problem**

When creating new ingress resource with tls certificates haproxy-ingress expects secret with certificate already created and filled with correct data.
When use cert-manager as certificate issuer - secret with certificate will be created after deploy of ingress resource and filled with correct data even later.

When haproxy-ingress see misconfigured secret with certificate - haproxy use default certificate and makes no attempt to check new certificate in secret.

Haproxy-ingress some logs:
using default certificate due to an error reading secret 'ms-some-service-cert' on ingress 'default/ms-some-service': secret "ms-some-service-cert" not found

Now it can be fixed by reload haproxy.

**Expected behavior**

Haproxy-ingress periodicaly or in another way check secret with certificate and reload own configuration when secret changed.

**Environment information**
HAProxy Ingress version: v0.13.0-beta.2

Ingress objects:

```
ingress:
  ...
  annotations:
    kubernetes.io/ingress.class: haproxy
    ingress.kubernetes.io/hsts: "false"
    cert-manager.io/issuer: "letsencrypt-staging"  
  tls:
    - secretName: ms-some-service-cert
      hosts:
        - service.domain.com
```
