### ISSUE TITLE
haproxy-ingress causes external-dns to trigger without any reason

### ISSUE THREAD

**Issue by michalschott** [jcmoraisjr/haproxy-ingress#852]
**Description of the problem**

While doing an upgrade from 0.10.10 to 0.10.11 we've observed that external-dns is causing dns records to be updated.

Logs:
```
I0910 09:04:16.716830       7 launch.go:196]
Name:       HAProxy
Release:    v0.10.11
Build:      git-c711ca0
Repository: https://github.com/jcmoraisjr/haproxy-ingress
I0910 09:04:16.716940       7 launch.go:199] Watching for ingress class: haproxy
I0910 09:04:16.717293       7 launch.go:454] Creating API client for https://172.20.0.1:443
I0910 09:04:17.742404       7 launch.go:466] Running in Kubernetes Cluster version v1.19+ (v1.19.13-eks-8df270) - git (clean) commit 8df2700a72a2598fa3a67c05126fa158fd839620 - platform linux/amd64
I0910 09:04:17.745760       7 launch.go:217] watching for global config options from configmap 'external-ingress/external-ingress-haproxy-ingress' - --configmap was defined
I0910 09:04:17.748705       7 launch.go:233] validated external-ingress/http-handler as the default backend
I0910 09:04:17.751488       7 launch.go:255] service external-ingress/external-ingress-haproxy-ingress validated as source of Ingress status
I0910 09:04:17.823613       7 event.go:274] Event(v1.ObjectReference{Kind:"Ingress", Namespace:"XXX", Name:"XXX", UID:"8f0cfbf5-abbf-42f9-b0f2-91c20e0dbcbb", APIVersion:"extensions/v1beta1", ResourceVersion:"483077391", FieldPath:""}): type: 'Normal' reason: 'CREATE' Ingress XXX/XXX
I0910 09:04:17.825468       7 event.go:274] Event(v1.ObjectReference{Kind:"Ingress", Namespace:"XXX", Name:"xxx", UID:"5b691809-47b4-4d47-b3a5-43cad3376a0c", APIVersion:"extensions/v1beta1", ResourceVersion:"483077308", FieldPath:""}): type: 'Normal' reason: 'CREATE' Ingress XXX/XXX
...
```

With `get events` we could also observe ingresses being CREATED/UPDATED.

This also happens when update is rollbacked.

**Expected behavior**

Ingresses should not be affected, external-dns should not be triggered.

**Steps to reproduce the problem**

1. Deploy 0.10.10
2. Create few ingresses
3. Upgrade to 0.10.11
4. Downgrade to 0.10.10?

**Environment information**

HAProxy Ingress version: `v0.10.10`, `v0.10.11`

Helm chart (v.0.12.8) values:
```
controller:
  affinity: {}
  autoscaling:
    customMetrics: []
    enabled: false
  config:
    config-frontend: |
      capture request header X-Forwarded-User len 50
      capture request header True-Client-IP len 50
      capture request header Host len 255
      capture request header Cf-Ray len 50
      acl is_robots_txt path /robots.txt
      use_backend _default_backend if is_robots_txt
    forwardfor: ifmissing
    http-log-format: '%[capture.req.hdr(3)]\ %[capture.req.hdr(1)]\ %ci:%cp\ [%t]\
      %ft\ %b/%s\ %Tq/%Tw/%Tc/%Tr/%Tt\ %ST\ %B\ %CC\ \ %CS\ %tsc\ %ac/%fc/%bc/%sc/%rc\
      %sq/%bq\ %hr\ %hs\ %HM\ %[capture.req.hdr(2)]%HU\ %HV'
    use-htx: "true"
  daemonset:
    hostPorts:
      http: 80
      https: 443
      tcp: []
    useHostPort: false
  defaultBackendService: external-ingress/http-handler
  dnsPolicy: ClusterFirst
  enableStaticPorts: true
  extraArgs:
    default-ssl-certificate: external-ingress/cloudflare-origin-cert
    publish-service: external-ingress/external-ingress-haproxy-ingress
    reload-strategy: reusesocket
  extraContainers: []
  extraEnvs: []
  extraVolumeMounts: []
  extraVolumes: []
  haproxy:
    enabled: false
    extraArgs: {}
    image:
      pullPolicy: IfNotPresent
      repository: haproxy
      tag: 2.2.16-alpine
    resources: {}
  healthzPort: 10253
  hostNetwork: false
  image:
    pullPolicy: IfNotPresent
    repository: quay.io/jcmoraisjr/haproxy-ingress
    tag: v0.10.11
  imagePullSecrets: []
  ingressClass: haproxy
  initContainers: []
  kind: Deployment
  lifecycle: {}
  livenessProbe:
    failureThreshold: 3
    initialDelaySeconds: 10
    path: /healthz
    periodSeconds: 10
    port: 10253
    successThreshold: 1
    timeoutSeconds: 1
  logs:
    enabled: true
    extraVolumeMounts: []
    image:
      pullPolicy: IfNotPresent
      repository: whereisaaron/kube-syslog-sidecar
      tag: latest
    resources: {}
  metrics:
    controllerPort: 10254
    embedded: true
    enabled: true
    extraArgs: {}
    image:
      pullPolicy: IfNotPresent
      repository: quay.io/prometheus/haproxy-exporter
      tag: v0.11.0
    port: 9101
    resources: {}
    service:
      annotations: {}
      clusterIP: ""
      externalIPs: []
      loadBalancerIP: ""
      loadBalancerSourceRanges: []
      serviceControllerPort: 10254
      servicePort: 9101
      type: ClusterIP
  minAvailable: 1
  minReadySeconds: 0
  nodeSelector: {}
  podAffinity: {}
  podAnnotations: {}
  podLabels: {}
  priorityClassName: ""
  readinessProbe:
    failureThreshold: 3
    initialDelaySeconds: 10
    path: /healthz
    periodSeconds: 10
    port: 10253
    successThreshold: 1
    timeoutSeconds: 1
  replicaCount: 3
  resources:
    limits:
      memory: 512Mi
    requests:
      cpu: 10m
      memory: 256Mi
  securityContext: {}
  service:
    annotations:
      service.beta.kubernetes.io/aws-load-balancer-healthcheck-healthy-threshold: "5"
      service.beta.kubernetes.io/aws-load-balancer-healthcheck-interval: "10"
      service.beta.kubernetes.io/aws-load-balancer-healthcheck-timeout: "5"
      service.beta.kubernetes.io/aws-load-balancer-healthcheck-unhealthy-threshold: "2"
      service.beta.kubernetes.io/aws-load-balancer-type: nlb
    clusterIP: ""
    clusterIPs: []
    externalIPs: []
    externalTrafficPolicy: Local
    extraPorts: []
    healthCheckNodePort: 0
    httpPorts:
    - port: 80
      targetPort: http
    httpsPorts:
    - port: 443
      targetPort: https
    labels: {}
    loadBalancerIP: ""
    loadBalancerSourceRanges: []
    type: LoadBalancer
  serviceMonitor:
    annotations: {}
    enabled: true
    honorLabels: true
    interval: 30s
    labels: {}
  stats:
    enabled: true
    port: 1936
    service:
      annotations: {}
      clusterIP: ""
      externalIPs: []
      loadBalancerIP: ""
      loadBalancerSourceRanges: []
      servicePort: 1936
      type: ClusterIP
  tcp: {}
  template: ""
  terminationGracePeriodSeconds: 60
  tolerations: []
  updateStrategy:
    rollingUpdate:
      maxUnavailable: 1
    type: RollingUpdate
defaultBackend:
  affinity: {}
  enabled: false
  image:
    pullPolicy: IfNotPresent
    repository: gcr.io/google_containers/defaultbackend
    tag: "1.4"
  minAvailable: 1
  name: default-backend
  nodeSelector: {}
  podAnnotations: {}
  podLabels: {}
  replicaCount: 1
  resources:
    limits:
      cpu: 10m
      memory: 20Mi
    requests:
      cpu: 10m
      memory: 20Mi
  securityContext: {}
  service:
    annotations: {}
    clusterIP: ""
    externalIPs: []
    loadBalancerIP: ""
    loadBalancerSourceRanges: []
    name: ingress-default-backend
    servicePort: 8080
    type: ClusterIP
  tolerations: []
fullnameOverride: ""
nameOverride: ""
rbac:
  create: true
  secret:
    write: false
  security:
    enable: false
serviceAccount:
  create: true
  name: null
```
