### ISSUE TITLE
rabbitmq amqp port use ingress not work, because the req.ssl_sin has no value from amqp client request

### ISSUE THREAD

**Issue by huangjiasingle** [jcmoraisjr/haproxy-ingress#858]
**Description of the problem**
rabbitmq amqp port use ingress not work, because the req.ssl_sin has no value from amqp client request

haproxy.conf:
```
backend default_rabbitmq-sample_5672                                                                                                                              
    mode tcp                                                                                                                                                      
    balance roundrobin                                                                                                                                            
    server srv001 127.0.0.1:1023 disabled weight 1 check inter 2s                                                                                                 
    server srv002 192.168.122.155:5672 weight 1 check inter 2s                                                                                                    
    server srv003 127.0.0.1:1023 disabled weight 1 check inter 2s                                                                                                 
    server srv004 127.0.0.1:1023 disabled weight 1 check inter 2s                                                                                                 
    server srv005 127.0.0.1:1023 disabled weight 1 check inter 2s                                                                                                 
    server srv006 127.0.0.1:1023 disabled weight 1 check inter 2s                                                                                                 
    server srv007 127.0.0.1:1023 disabled weight 1 check inter 2s                                                                                                 
    server srv008 127.0.0.1:1023 disabled weight 1 check inter 2s 

frontend _front_tcp_5672                                                                                                                                          
    bind :5672                                                                                                                                                    
    mode tcp                                                                                                                                                      
    tcp-request inspect-delay 5s                                                                                                                                  
    tcp-request content set-var(req.tcpback) req.ssl_sni,lower,map_str(/etc/haproxy/maps/_tcp_sni_5672__exact.map)                                                
    tcp-request content accept if { req.ssl_hello_type 1 }                                                                                                        
    use_backend %[var(req.tcpback)] if { var(req.tcpback) -m found }  
```
/etc/haproxy/maps/_tcp_sni_5672__exact.map   contenxt:

```
# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #
# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #
# #
# #   HAProxy Ingress Controller
# #   --------------------------
# #   This file is automatically updated, do not edit
# #
#
rabbitmq-sample.default.mq.nioint.com default_rabbitmq-sample_5672
```
**Expected behavior**

**Steps to reproduce the problem**

1.  deploy rabbitmq deploy  : https://github.com/rabbitmq/diy-kubernetes-examples/tree/master/minikube
2.  create ingress of amqp
3.  use go client go connet rabbitmq by amqp

**Environment information**

HAProxy Ingress version: `v0.xx`
v0.13.0

Command-line options:
- --configmap=ingress-controller/haproxy-ingress
- --ingress-class=haproxy
- --sort-backends
```
(paste command-line options here)
```

Global options:

```
apiVersion: v1
data:
  healthz-port: "10253"
  stats-port: "1936"
kind: ConfigMap
metadata:
  annotations:
    meta.helm.sh/release-name: haproxy-ingress
    meta.helm.sh/release-namespace: ingress-controller
  labels:
    app.kubernetes.io/instance: haproxy-ingress
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: haproxy-ingress
    app.kubernetes.io/version: v0.13.0
    helm.sh/chart: haproxy-ingress-0.13.0
  name: haproxy-ingress
  namespace: ingress-controller
```

Ingress objects:
```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    ingress.kubernetes.io/cors-enable: "true"
    ingress.kubernetes.io/rewrite-target: /
    ingress.kubernetes.io/tcp-service-port: "5672"
    kubernetes.io/ingress.class: haproxy
  name: rabbitmq-sample
  namespace: default
spec:
  rules:
  - host: rabbitmq-sample.default.mq.nioint.com
    http:
      paths:
      - backend:
          service:
            name: rabbitmq-sample
            port:
              number: 5672
        pathType: ImplementationSpecific
```
because req.ssl_sni has no value, so the use_backend no macth,   because replace `use_backend %[var(req.tcpback)] if { var(req.tcpback) -m found }  `  as `use_backend default_rabbitmq-sample_5672 if { var(req.tcpback) -m found }`  not work,  if replace as `use_backend default_rabbitmq-sample_5672`   work fine.

**Comment by jcmoraisjr** [comment]
Hi, please try to remove the hostname from the host attribute. HAProxy ingress will only use sni if host is declared, so you can use distinct services behind the same port. If host is missing the sni won't be used to match the request. Btw thanks for reporting, this seems to be a common source of mistake and I'll improve this part of the doc.

**Comment by huangjiasingle** [comment]
@jcmoraisjr tkx you reply. do as you say, work fine.  but when l use one ingress to define to backend like this, only 5672 work, the mq ui manager 15672 doesn't work.  because when set the annotaion `ingress.kubernetes.io/tcp-service-port: "5672"`, the http front: 
```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    ingress.kubernetes.io/cors-enable: "true"
    ingress.kubernetes.io/rewrite-target: /
    kubernetes.io/ingress.class: haproxy
    ingress.kubernetes.io/tcp-service-port: "5672"
  labels:
    middleware.com/type: RabbitMQ
    rabbitmq.middleware.com/instance: rabbitmq-sample
  name: rabbitmq-sample
  namespace: default
spec:
  rules:
  - http:
      paths:
      - backend:
          serviceName: rabbitmq-sample
          servicePort: 15672
        path: /
        pathType: ImplementationSpecific
    host: rabbitmq-sample.default.nioint.com
  - http:
      paths:
      - backend:
          serviceName: rabbitmq-sample
          servicePort: 5672
        path: /
        pathType: ImplementationSpecific
status:
  loadBalancer: {}
```
```
frontend _front_http
    mode http
    bind :80
    http-request set-var(req.path) path
    http-request set-var(req.host) hdr(host),field(1,:),lower
    http-request set-var(req.base) var(req.host),concat(\#,req.path)
    http-request set-header X-Forwarded-Proto http
    http-request del-header X-SSL-Client-CN
    http-request del-header X-SSL-Client-DN
    http-request del-header X-SSL-Client-SHA1
    http-request del-header X-SSL-Client-Cert
    http-request set-var(req.backend) var(req.base),map_dir(/etc/haproxy/maps/_front_http_host__prefix.map)
    http-request set-var(req.backend) var(req.base),lower,map_beg(/etc/haproxy/maps/_front_http_host__begin.map) if !{ var(req.backend) -m found }
    http-request set-var(req.defaultbackend) var(req.path),map_dir(/etc/haproxy/maps/_front_defaulthost__prefix.map) if !{ var(req.backend) -m found }
    use_backend %[var(req.backend)] if { var(req.backend) -m found }
    use_backend %[var(req.defaultbackend)]
    default_backend ingress-controller_default-http-backend_8080
```

/etc/haproxy/maps/_front_http_host__prefix.map /etc/haproxy/maps/_front_http_host__begin.map /etc/haproxy/maps/_front_defaulthost__prefix.map   doesn't contains `rabbitmq-sample.default.mq.nioint.com` colum.

mybe the generate host map file logic do all backend in ingress as define tcp-service-port annotations
