### ISSUE TITLE
ssl-mode-async: openssl library does not support async mode

### ISSUE THREAD

**Issue by itleets** [jcmoraisjr/haproxy-ingress#862]
**Description of the problem**
When i set `ssl-mode-async: "true"` then I'm getting error in logs: `openssl library does not support async mode`
Here my config file:
```
apiVersion: v1
data:
  balance-algorithm: leastconn
  max-connections: "20000"
  ssl-engine: "qat"
  ssl-mode-async: "true"
kind: ConfigMap
metadata:
  name: haproxy-ingress
  namespace: ingress-controller
```

**Expected behavior**
These two flags should work fine:
  ssl-engine: "qat"
  ssl-mode-async: "true"

**Steps to reproduce the problem**

Deploy `hpaproxy-ingress` with following configmap file:
```
apiVersion: v1
data:
  balance-algorithm: leastconn
  max-connections: "20000"
  ssl-engine: "qat"
  ssl-mode-async: "true"
kind: ConfigMap
metadata:
  name: haproxy-ingress
  namespace: ingress-controller
```

**Environment information**

HAProxy Ingress version: `v0.13.4`

I'm testing it on basic intel droplet of digitaloccean.
