### ISSUE TITLE
Does this allow for multiple HAproxy ingress-controllers by specifying election/class?

### ISSUE THREAD

**Issue by mikejk8s** [jcmoraisjr/haproxy-ingress#87]
Hi,

I'm trying to get this working but need multiple ingress controllers (in the event one goes down I'd lose every connection, so I pin them to their deployment). In the nginx-ingress which I've been using in the past this is accomplished by setting 

``` - --ingress-class=nginx-ingress-1, 2, 3 etc```

The nginx-ingress then writes to a configmap that isn't shared between the other ingress controllers by assigning a role. I'm trying to figure out if the haproxy-ingress works the same or if it doesn't need this backend configmap or if it doesn't work at all. Here's an example of the role for one nginx-ingress to lock it to its controller configmap;

```
rules:
  - apiGroups:
      - ""
    resources:
      - configmaps
      - pods
      - secrets
      - namespaces
    verbs:
      - get
  - apiGroups:
      - ""
    resources:
      - configmaps
    resourceNames:
      # Defaults to "<election-id>-<ingress-class>"
      # Here: "<ingress-controller-leader>-<nginx>"
      # This has to be adapted if you change either parameter
      # when launching the nginx-ingress-controller.
    #  - "ingress-controller-leader-{{.Values.client_socket_ingress_name}}"
      - "nginx-1" (and another role for nginx-2, etc)
    verbs:
      - get
      - update
  - apiGroups:
      - ""
    resources:
      - configmaps
    verbs:
      - create
  - apiGroups:
      - ""
    resources:
      - endpoints
    verbs:
      - get
      - create
      - update
```
