### ISSUE TITLE
curl -k https://echoserver.local return 404

### ISSUE THREAD

**Issue by usernameisnull** [jcmoraisjr/haproxy-ingress#871]
**Description of the problem**
I deployed it according to the example on your official website
https://haproxy-ingress.github.io/docs/getting-started/#deploy-and-expose

When I visit this URL：https://echoserver.local, it returns 404
```
curl -k https://echoserver.local
<html><body><h1>404 Not Found</h1>
The requested URL was not found.
</body></html>
```

**Expected behavior**
it should return 200

**Steps to reproduce the problem**

1. helm install haproxy-ingress haproxy-ingress-0.13.3.tgz  --create-namespace --namespace ingress-controller  -f haproxy-ingress-values.yaml, the content of **haproxy-ingress-values.yaml**:
 ```yaml
controller:
  haproxy:
    image:
      repository: mypriviaterepositoy/library/haproxy-ingress
      tag: v0.13.3
  hostNetwork: true
  dnsPolicy: ClusterFirstWithHostNet
  kind: DaemonSet
  nodeSelector: 
    haproxy-ingress-controller: "true"
 ```
2. execute the example:
```yaml
kubectl --namespace default create deployment echoserver --image registry.cn-hangzhou.aliyuncs.com/xxx/echoserver:1.3

kubectl --namespace default expose deployment echoserver --port=8080

kubectl --namespace default create ingress echoserver\
  --annotation kubernetes.io/ingress.class=haproxy\
  --rule="echoserver.local/*=echoserver:8080"
```
3. I write **echoserver.local** to my **/etc/hosts**, and I can ping this:
```shell
ping echoserver.local
PING echoserver.local (172.16.55.27) 56(84) bytes of data.
64 bytes from www.mabing123.com (172.16.55.27): icmp_seq=1 ttl=63 time=0.282 ms
64 bytes from www.mabing123.com (172.16.55.27): icmp_seq=2 ttl=63 time=0.302 ms
^C
--- echoserver.local ping statistics ---
2 packets transmitted, 2 received, 0% packet loss, time 1005ms
rtt min/avg/max/mdev = 0.282/0.292/0.302/0.010 ms
```
4. The ing in default namespace:
```yaml
kubectl get ing -n default
NAME         CLASS    HOSTS              ADDRESS   PORTS   AGE
echoserver   <none>   echoserver.local             80      10m
```
5. The object in ingress-controller namespace
```yaml
# kubectl get all -n ingress-controller
NAME                        READY   STATUS    RESTARTS   AGE
pod/haproxy-ingress-9rwcb   1/1     Running   0          2m11s
pod/haproxy-ingress-m29rh   1/1     Running   0          2m11s

NAME                      TYPE           CLUSTER-IP      EXTERNAL-IP   PORT(S)                      AGE
service/haproxy-ingress   LoadBalancer   10.110.247.23   <pending>     80:30254/TCP,443:32187/TCP   2m12s

NAME                             DESIRED   CURRENT   READY   UP-TO-DATE   AVAILABLE   NODE SELECTOR                     AGE
daemonset.apps/haproxy-ingress   2         2         2       2            2           haproxy-ingress-controller=true   2m12s
```
**Environment information**

HAProxy Ingress version: `0.13.3`

Command-line options:
```
helm install haproxy-ingress haproxy-ingress-0.13.3.tgz  --create-namespace --namespace ingress-controller  -f haproxy-ingress-values.yaml
```

Global options:

```
(paste global configmap options here)
```

Ingress objects:

```yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: echoserver
  namespace: default
  uid: 6752084c-0fb8-4e0e-983e-15bda10a2128
  resourceVersion: '20499891'
  generation: 1
  creationTimestamp: '2021-12-11T15:05:13Z'
  annotations:
    kubernetes.io/ingress.class: haproxy
  managedFields:
    - manager: kubectl-create
      operation: Update
      apiVersion: networking.k8s.io/v1
      time: '2021-12-11T15:05:13Z'
      fieldsType: FieldsV1
      fieldsV1:
        'f:metadata':
          'f:annotations':
            .: {}
            'f:kubernetes.io/ingress.class': {}
        'f:spec':
          'f:rules': {}
    - manager: haproxy-ingress-controller
      operation: Update
      apiVersion: networking.k8s.io/v1
      time: '2021-12-11T15:05:17Z'
      fieldsType: FieldsV1
      fieldsV1:
        'f:status':
          'f:loadBalancer':
            'f:ingress': {}
  selfLink: /apis/networking.k8s.io/v1/namespaces/default/ingresses/echoserver
status:
  loadBalancer:
    ingress:
      - {}
spec:
  rules:
    - host: echoserver.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: echoserver
                port:
                  number: 8080

```

**Comment by usernameisnull** [comment]
The **EXTERNAL-IP** of service/haproxy-ingress  is pending, is that right?

**Comment by usernameisnull** [comment]
but if I use some other examples,it seems ok, something wrong with the echoserver example?
---
1. kubectl run haproxy-ingress-demo --image=nginx:1.7.9 --port=80 --replicas=1 --expose
2. install ingress
```yaml
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: haproxy-ingress-demo 
  labels:
    ingresscontroller: haproxy 
  annotations:
    kubernetes.io/ingress.class: haproxy 
spec:
  rules:
  - host: www.mabing456.com
    http:
      paths:
      - path: /
        backend:
          serviceName: haproxy-ingress-demo 
          servicePort: 80
```
