### ISSUE TITLE
How to verify when I use the secure-backends?

### ISSUE THREAD

**Issue by Gezx** [jcmoraisjr/haproxy-ingress#882]
**Here is my ingress:**

```yaml
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: haproxy-ingress-demo
  labels:
    ingresscontroller: haproxy
  annotations:
    kubernetes.io/ingress.class: haproxy
    ingress.kubernetes.io/secure-backends: "true"
    ingress.kubernetes.io/secure-crt-secret: "default/haproxy-tls"
spec:
  tls:
  - hosts:
    - www.happylau.cn
    secretName: haproxy-tls
  rules:
  - host: www.happylau.cn
    http:
      paths:
      - path: /
        backend:
          serviceName: nginx
          servicePort: 80
```

**I want to verify the secure-backends, so I use `curl https://www.happylau.cn:443 --resolve www.happylau.cn:443:10.100.1.52 --cacert tls.crt -vvv`, the result as the follows:**

```
* Added www.happylau.cn:443:10.100.1.52 to DNS cache
* About to connect() to www.happylau.cn port 443 (#0)
*   Trying 10.100.1.52...
* Connected to www.happylau.cn (10.100.1.52) port 443 (#0)
* Initializing NSS with certpath: sql:/etc/pki/nssdb
*   CAfile: tls.crt
  CApath: none
* SSL connection using TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
* Server certificate:
*       subject: E=2771485026@qq.com,CN=www.happylau.cn,OU=HappyLau,O=11,L=beijing,ST=BJ,C=CN
*       start date: Dec 30 08:20:01 2021 GMT
*       expire date: Dec 30 08:20:01 2022 GMT
*       common name: www.happylau.cn
*       issuer: E=2771485026@qq.com,CN=www.happylau.cn,OU=HappyLau,O=11,L=beijing,ST=BJ,C=CN
> GET / HTTP/1.1
> User-Agent: curl/7.29.0
> Host: www.happylau.cn
> Accept: */*
>
< HTTP/1.1 503 Service Unavailable
< content-length: 107
< cache-control: no-cache
< content-type: text/html
<
No server is available to handle this request.
</body></html>
* Connection #0 to host www.happylau.cn left intact
```

**So I want to know how to use secure backend**
