### ISSUE TITLE
CORS issue

### ISSUE THREAD

**Issue by mikejk8s** [jcmoraisjr/haproxy-ingress#91]
I'm having issues with CORS and I'm not 100% sure how to set the annotations, some guidance would be helpful. Right now my websockets are getting the following error;

```
No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'https://subdomain.mydomain.com' is therefore not allowed access. The response had HTTP status code 404.
```

I've tried various mixtures of the annotations below but am not seeing any difference. 

```
  annotations:
    kubernetes.io/ingress.class: client-socket-haproxy
    ingress.kubernetes.io/affinity: "cookie"
    ingress.kubernetes.io/enable-cors: true
    ingress.kubernetes.io/cors-allow-origin: "*"
    ingress.kubernetes.io/cors-allow-headers: "DNT,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Range"
    ingress.kubernetes.io/cors-allow-methods: "GET, POST, OPTIONS"
```

This is 0.5.-beta.1
