### ISSUE TITLE
TLS termination with SNI-based routing on TCP port always delays connection by 5 seconds

### ISSUE THREAD

**Issue by PaleoCrafter** [jcmoraisjr/haproxy-ingress#912]
**Description of the problem**

Enabling TLS termination and SNI-based routing on a TCP service (using the `tcp-service-port` annotation) with a specific host-rule causes a delay of 5 seconds regardless of the value of the server name transmitted by the client.

The culprit appears to be this line in the configuration template:
https://github.com/jcmoraisjr/haproxy-ingress/blob/b30446862cb1e29efbc12fcddda8fef5a2f47f08/rootfs/etc/templates/haproxy/haproxy.tmpl#L1031

The delay comes from the `tcp-request inspect-delay 5s` instruction, but the delay should *not* be hit as the variable match on `req.ssl_fc_sni` should occur long before the delay is over.

As the frontend at that point has a `bind [...] ssl [...]` instruction, the `req.ssl_hello_type` value will not be set in this case, see the [HAProxy configuration manual](https://cbonte.github.io/haproxy-dconv/2.0/configuration.html#7.3.5-req.ssl_hello_type) for details. I think the fix is as simple as removing that line, since we know our connection is TLS-enabled at that point, but I didn't want to submit a PR yet in case there's something I'm missing there.

I've amended the template in my own instance and the connection was established immediately when initiated with the correct SNI information, but closed if the host didn't match the configured one. So this one-line change would definitely solve my particular case.

**Expected behavior**

The connection to the appropriate backend (based on SNI) should be established immediately after the TLS handshake.

**Steps to reproduce the problem**

1. Create an ingress with `tcp-service-port`, a `tls` section and a `rule` matching the desired host
   * Do this for e.g. a simple echo server
2. Connect to the service using e.g. `openssl s_client`
3. Observe a delay of 5 seconds before the backend sends an answer

**Environment information**

HAProxy Ingress version: `v0.13.6`

Ingress objects:

```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: tcp-echo
  annotations:
    kubernetes.io/ingress.class: haproxy
    haproxy-ingress.github.io/tcp-service-port: 12345
spec:
  tls:
    - hosts:
        - tcp-echo.example.com
  rules:
    - host: tcp-echo.example.com
      http:
        paths:
          - pathType: Prefix
            path: /
            backend:
              service:
                name: tcp-echo-service
                port:
                  number: 2701
```
