### ISSUE TITLE
HAProxy ingress controller is creating ELBs, which are deprecated in AWS and will be removed after August 2022

### ISSUE THREAD

**Issue by dbarvitsky** [jcmoraisjr/haproxy-ingress#920]
**Description of the problem**

I was looking into a way of controlling request affinity in Kubernetes and followed the instructions in the docs. Our Kubernetes clusters are running in AWS, specifically EKS. I noticed that running in LoadBalancer mode creates an AWS load balancer of the ELB type, which is [deprecated](https://docs.aws.amazon.com/elasticloadbalancing/latest/userguide/migrate-classic-load-balancer.html) per AWS and will no longer be able to run after August 2022. I looked through help and configuration options and didn't find an apparent way to force HAProxy to use NLBs or ALBs instead. 

As a workaround, it is possible to use node ports, but that doesn't work for general case in microservice environment (requires coordination between teams and port assignments).

**Expected behavior**

NLB or ALB load balancer should be created when running in the LoadBalancer mode.

**Steps to reproduce the problem**

1. Create a VPC with EKS cluster
2. Follow the demo instructions
3. Observe: the type of the load balancer created in AWS is ELB.

**Environment information**

HAProxy Ingress version: `v0.13.6`

**Comment by dbarvitsky** [comment]
Found a way to do it with NLB (inspired by #713).

I ended up adding annotations to the ingress service:

```yaml
# haproxy-ingress-values.yaml
controller:
  hostNetwork: true
  ...
  service:
    type: LoadBalancer
    annotations:
      service.beta.kubernetes.io/aws-load-balancer-type: nlb
      # This is irrelevant, but might be useful too.
      service.beta.kubernetes.io/aws-load-balancer-internal: "true"
```

And then install as usual:
```bash
$> helm3 install --namespace whatever  haproxy-ingress haproxy-ingress/haproxy-ingress --version 0.13.6 -f haproxy-ingress-values.yaml
```

Relevant documentation is [available in sigs](https://kubernetes-sigs.github.io/aws-load-balancer-controller/v2.2/guide/service/annotations/#lb-type). Admittedly, this can be considered common knowledge and hence lack of my expertise trying to setting up HAProxy ingress. I think a noob like me could benefit from a note in [getting started](https://haproxy-ingress.github.io/docs/getting-started/) to tripping over it.
