### ISSUE TITLE
Unable to retrive the requested URL in external auth-server while using auth-url annotation

### ISSUE THREAD

**Issue by rohan-97** [jcmoraisjr/haproxy-ingress#926]
**Description of the problem**

Hello, I am trying to integrate an external authentication server using ha-proxy ingress using the [auth-url](https://haproxy-ingress.github.io/docs/configuration/keys/#auth-external) annotation.

the authentication server(Flask server) expects following information to be present in the headers.

1. Basic auth header
2. url which was requested from client side
3. Client IP address

**Expected behavior**
 It is expected that when ha-proxy ingress controller creates a request to auth-server, it adds all the headers from the client request and also adds above 3 values in headers.
 
 However when I set up the auth-url, I am able to fetch the basic auth headers and  client IP but unable to identify the url which was requested in headers.
 
 Following are the headers received at auth-server by ha-proxy ingress controller

requested url : http://localhost/endpoint

``` 
User-Agent: curl/7.74.0
X-Real-Ip: 127.0.0.1
X-Forwarded-Proto: http
Accept: */*
Authorization: Basic dXNlcjE6cGFzc3dvcmQ=
Host: auth-server-service.test-namespace.svc.cluster.local
X-Forwarded-For: 127.0.0.1
```

I tried same thing with nginx-ingress controller and I get following headers in same auth-server from nginx-controller

```
X-Request-Id: 67085ed4b2c9f29aefb8f2aeb9dc2434
Host: auth-server-service.test-namespace.svc.cluster.local
X-Original-Url: http://localhost/endpoint
X-Original-Method: GET
X-Sent-From: nginx-ingress-controller
X-Real-Ip: 10.31.2.238
X-Forwarded-For: 10.31.2.238
X-Auth-Request-Redirect: /endpoint
Connection: close
Authorization: Basic dXNlcjE6cGFzc3dvcmQ=
User-Agent: curl/7.74.0
Accept: */*
```
refer X-Auth-Request-Redirect or X-Original-Url header in nginx headers,
we get the requested URL in the headers, however this information is not present in headers added by haproxy ingress.

It is very important to identify which URL was requested so that auth-server can perform custom authentication based on accessed URL.

**Steps to reproduce the problem**

1. Setup kubernetes cluster using microk8s
2. Create a sample echo server  listening at url http://localhost/endpoint
3. Expose echoserver using a service
4. Add rules to redirect incoming requet to the service.
5. Add annotation haproxy-ingress.github.io/auth-url: "http://auth-server-service.test-namespace.svc.cluster.local/auth"
6. Make REST API calls with basic auth headers

CURL syntax:
```
curl --user user1:password http://localhost/endpoint
```

**Environment information**

HAProxy Ingress version: `v0.13`

Ingress objects:

Ingress yaml file
```

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: haproxy-ingress
  namespace: test-namespace
  annotations:
    kubernetes.io/ingress.class: haproxy
    haproxy-ingress.github.io/auth-url: "http://auth-server-service.test-namespace.svc.cluster.local/auth"
spec:
  rules:
    - host: localhost
      http:
        paths:
          - path: /endpoint
            pathType: Prefix
            backend:
              service:
                name: target-app-service
                port:
                  number: 4567
    - host: localhost
      http:
        paths:
          - path: /token
            pathType: Prefix
            backend:
              service:
                name: auth-server-service
                port:
                  number: 80
    - host: localhost
      http:
        paths:
          - path: /echo
            pathType: Prefix
            backend:
              service:
                name: echoserver
                port:
                  number: 8080
                  
         
```
haproxy-ingress-values.yaml

```
# Default values are present here : https://github.com/haproxy-ingress/charts/blob/release-0.13/haproxy-ingress/values.yaml
controller:
  hostNetwork: true
  dnsPolicy: ClusterFirstWithHostNet
  
```

**Comment by rohan-97** [comment]
Hi Guys,  
Is there any update on this?  
Please let me know if I am doing anything wrong or if there are other options/configuration available to achieve this?  

Also let me know if anything is the issue is not clear

**Comment by jcmoraisjr** [comment]
Hi, thanks for the detailed report and sorry about the long delay. Yes it's pretty clear and your request makes sense. I'm not sure you can dynamically configure it, anyway a new tag should be issued shortly adding some new headers.

**Comment by rohan-97** [comment]
Hi @jcmoraisjr ,  

I used config-backend ingress annotation to add the requested URL in the request headers.

```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: haproxy-ingress
  namespace: default
  annotations:
    kubernetes.io/ingress.class: haproxy
    haproxy-ingress.github.io/config-backend: |
      http-request set-header X-Auth-Request-Redirect %[capture.req.uri]
```

This configuration works fine, in the endpoint I am able to see X-Auth-Request-Redirect headers set with requested URL.

But when I include auth-server in configuration (refer below yaml file for configuration)
I am not able to see the headers getting set in the request received by auth-server

```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: haproxy-ingress
  namespace: pty-service-dispatcher
  annotations:
    kubernetes.io/ingress.class: haproxy
    haproxy-ingress.github.io/config-backend: |
      http-request set-header X-Auth-Request-Redirect %[capture.req.uri]
    haproxy-ingress.github.io/auth-url: "http://auth-server-service.default.svc.cluster.local/auth"
```
