### ISSUE TITLE
Unable to add custom header using config-backend and config-frontend options

### ISSUE THREAD

**Issue by rohan-97** [jcmoraisjr/haproxy-ingress#929]
**Description of the problem**

Hello, 
I am trying to add a custom header in the request using [configuration snippet](https://haproxy-ingress.github.io/docs/configuration/keys/#configuration-snippet) annotation provided in haproxy-ingress.

**Expected behavior**

I am trying to add a custom header in request with a hardcoded string and I am expecting this header to be received by upstream endpoints in kubernetes cluster but I am not able to see the headers getting set.

**Steps to reproduce the problem**

1. Install a new instance using helm charts using following addition to values.yaml
```
controller:
  hostNetwork: true
  dnsPolicy: ClusterFirstWithHostNet
config:
  config-backend: |
    http-request set-header x-forwarded-uri "test-header"
```    
Also tried this values.yaml
```
controller:
  hostNetwork: true
  dnsPolicy: ClusterFirstWithHostNet
config:
  config-frontend: |
    http-request set-header x-forwarded-uri "test-header"
```    

2. add a echoserver which echoes back the headers received,(the service corresponding to echoserver is named as echoserver-service in this example) 
3. make REST API call to echoserver and search for `x-forwarded-uri` headers being set with value "test-header"
```
root@ip-10-31-2-64:~# curl --user user1:protegrity http://localhost/endpoint
Hello, From endpoint! headers received : {'ACTUAL_SERVER_PROTOCOL': 'HTTP/1.1', 'PATH_INFO': '/endpoint', 'QUERY_STRING': '', 'REMOTE_ADDR': '10.31.2.64', 'REMOTE_PORT': '52662', 'REQUEST_METHOD': 'GET', 'REQUEST_URI': '/endpoint', 'SCRIPT_NAME': '', 'SERVER_NAME': 'localhost', 'SERVER_PROTOCOL': 'HTTP/1.1', 'SERVER_SOFTWARE': 'Cheroot/unknown Server', 'wsgi.errors': <_io.TextIOWrapper name='<stderr>' mode='w' encoding='utf-8'>, 'wsgi.input': <cheroot.server.KnownLengthRFile object at 0x7f89240e8e50>, 'wsgi.input_terminated': False, 'wsgi.multiprocess': False, 'wsgi.multithread': True, 'wsgi.run_once': False, 'wsgi.url_scheme': 'http', 'wsgi.version': (1, 0), 'SERVER_PORT': '4567', 'HTTP_HOST': 'localhost', 'HTTP_AUTHORIZATION': 'Basic dXNlcjE6cHJvdGVncml0eQ==', 'HTTP_USER_AGENT': 'curl/7.74.0', 'HTTP_ACCEPT': '*/*', 'HTTP_X_FORWARDED_PROTO': 'http', 'HTTP_X_FORWARDED_FOR': '127.0.0.1'}
```
4.I didn't find `x-forwarded-uri` header being set 

**Environment information**

HAProxy Ingress version: `0.13.7`

Command-line options:

```
default
```

Global options:

```
default
```

Ingress objects:

```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: haproxy-ingress
  namespace: example-namespace
  annotations:
    kubernetes.io/ingress.class: haproxy
spec:
  rules:
    - host: localhost
      http:
        paths:
          - path: /endpoint
            pathType: Prefix
            backend:
              service:
                name: echoserver-service
                port:
                  number: 4567
```

**Comment by jcmoraisjr** [comment]
Hi, `config` belongs to `controller`, can you confirm if you still have this issue indenting it?

**Comment by rohan-97** [comment]
Hello,

I tried to indent the config but it didn't work,
Later I changed the kubernetes cluster....

I switched to microk8s based cluster and there the following configuration worked.

```
# Default values are present here : https://github.com/haproxy-ingress/charts/blob/release-0.13/haproxy-ingress/values.yaml
controller:
  hostNetwork: true
  dnsPolicy: ClusterFirstWithHostNet
config:
  config-backend: |
    http-request set-header x-forwarded-uri "test-header"
```

I think this issue might be related to my Kubernetes environment where I tried to install vanilla Kubernetes.
As this configuration is working fine, I am closing this issue

Thanks a lot for the support....!!!
