### ISSUE TITLE
Use TCP frontend and HTTP backend

### ISSUE THREAD

**Issue by mielmat** [jcmoraisjr/haproxy-ingress#930]
Hello,
I need some help with configuring haproxy ingress. I used version 0.7 of controller, and  that one created TCP frontend bound to port 443, then TCP backend which had 'server' directive with unix socket and then another pair of frontend - backend in HTTP mode. Then I upgraded to latest version and things stopped working, as by default all frontend were created in HTTP mode. I used 
```yaml
ingress.kubernetes.io/tcp-service-port: "443"
    ingress.kubernetes.io/config-tcp-service: |
    ....
```
in my k8s ingress definition, but https frontend is also bounded to port 443 - so now traffic is load balanced by both frontends - tcp and http. Is there any way to make the configuration similar to the old one? Any proxying option can be used to redirect all traffic to tcp frontend on port 443 and then do the routing to proper backends?

Thanks in advance
