### ISSUE TITLE
ssl-redirect not working when ssl-passthrough is enabled

### ISSUE THREAD

**Issue by yerkanian** [jcmoraisjr/haproxy-ingress#931]
**Description of the problem**

I’m trying to set up ssl-passthrough to container’s port 443 with ssl-redirect on port 80, but no matter what I try haproxy-ingress gives 404 on port 80.

**Expected behavior**

haproxy-ingress should generate a redirect for requests arriving on port 80 to the service port 443.

**Configuration to reproduce the problem**

```
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: test-ingress
  namespace: test
  annotations:
    haproxy-ingress.github.io/ssl-redirect: "true"
    haproxy-ingress.github.io/ssl-redirect-code: "301"
    haproxy-ingress.github.io/ssl-passthrough: "true"
spec:
  tls:
  - hosts:
    - test.local
  rules:
  - host: test.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: echoapp
            port: 
              number: 443
```
