### ISSUE TITLE
Doesn't work behind Azure load balancer

### ISSUE THREAD

**Issue by IvanovOleg** [jcmoraisjr/haproxy-ingress#94]
I have Kubernetes 1.9.1 installed in Azure Cloud. I tried to use the haproxy ingress controller with the next service definition:
```
---
kind: Service
apiVersion: v1
metadata:
  name: haproxy-ingress
  namespace: test
  labels:
    app: haproxy-ingress
spec:
  externalTrafficPolicy: Local
  type: LoadBalancer
  selector:
    app: haproxy-ingress
  ports:
    - name: http
      port: 80
      targetPort: http
    - name: https
      port: 443
      targetPort: https
    - name: stat
      port: 1936
      targetPort: stat
```

All ingresses get the kubernetes node ip instead of the external ip of the created Azure load balancer. Unable to connect to all of them. There is no such issue with nginx ingress controller.
```
[vagrant@localhost haproxy]$ kubectl get svc --namespace=test
NAME                   TYPE           CLUSTER-IP     EXTERNAL-IP     PORT(S)                                                                              AGE
default-http-backend   ClusterIP      10.0.138.40    <none>          80/TCP                                                                               2h
echoheaders            ClusterIP      None           <none>          80/TCP                                                                               1h
haproxy-ingress        LoadBalancer   10.0.193.111   13.81.102.217   80:31808/TCP,443:30782/TCP,1936:31872/TCP   34m
```

```
[vagrant@localhost haproxy]$ kubectl get ing --namespace=test
NAME      HOSTS                ADDRESS       PORTS     AGE
echo      xxx.xxxxxxxx.com   10.240.0.66     80        55m
```
