### ISSUE TITLE
Custom TCP port proxy doesn't work

### ISSUE THREAD

**Issue by IvanovOleg** [jcmoraisjr/haproxy-ingress#96]
Hi! I tried to use the haproxy ingress controller to serve postgresql port 5432 as described in documentation, but the haproxy-ingress pod doesn't transfer packets. Here is my configuration:
**haproxy-ingress.yml:**
```
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: haproxy-ingress
  namespace: default
spec:
  selector:
    matchLabels:
      app: haproxy-ingress
  template:
    metadata:
      labels:
        app: haproxy-ingress
    spec:
      serviceAccountName: ingress-controller
      containers:
        - name: haproxy-ingress
          image: quay.io/jcmoraisjr/haproxy-ingress
          args:
            - --default-backend-service=$(POD_NAMESPACE)/default-http-backend
            - --default-ssl-certificate=$(POD_NAMESPACE)/example-tls
            - --configmap=$(POD_NAMESPACE)/haproxy-ingress
            - --tcp-services-configmap=$(POD_NAMESPACE)/haproxy-tcp
            - --publish-service=$(POD_NAMESPACE)/haproxy-ingress
          ports:
            - name: http
              containerPort: 80
            - name: https
              containerPort: 443
            - name: stat
              containerPort: 1936
            - name: postgresql
              containerPort: 5432
          env:
          - name: POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: POD_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
```
**configmap.yml:**
```
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: haproxy-ingress
  namespace: default
  labels:
    app: haproxy-ingress

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: haproxy-tcp
  namespace: default
data:
  "5432": "default/postgres:5432"

```
**service.yml:**
```
---
kind: Service
apiVersion: v1
metadata:
  name: haproxy-ingress
  namespace: default
  labels:
    app: haproxy-ingress
spec:
  externalTrafficPolicy: Local
  type: LoadBalancer
  selector:
    app: haproxy-ingress
  ports:
    - name: http
      port: 80
      targetPort: http
    - name: https
      port: 443
      targetPort: https
    - name: stat
      port: 1936
      targetPort: stat
    - name: postgresql
      port: 5432
      targetPort: postgresql
```
I tried to connect via **psql** from remote PC using domain name, using public IP and got **psql: could not connect to server: Connection refused**. Then I thought that this is load balancer related issue and tried to connect from postgresql container in the same cluster via **psql -h "haproxy pod ip" -p 5432** and got the same issue. The same configuration works fine with nginx ingress controller, but I want to use some of the haproxy features.
