### ISSUE TITLE
auth-url does not handle well service with port names instead of numbers

### ISSUE THREAD

**Issue by didiercolens** [jcmoraisjr/haproxy-ingress#981]
**Description of the problem**

Assume a service with the following manifest (snippet):
```yaml
  name: my-authentication
spec:
  ports:
  - name: authentication
    port: 1234
    protocol: TCP
    targetPort: authentication
```
the corresponding deployment has the following port definition:
```yaml
spec:
  containers:
  - ports:
      - containerPort: 1234
        name: authentication
```

if an ingress is configured as follows (the documentation says to use port number):
```
haproxy-ingress.github.io/auth-url: svc://bdb-authentication:1234/api/v2/auth
```

it will silently fail (no error logged anywhere) and always deny all requests 

**Expected behaviour**

Either an error is logged to warn that the backend could not be found or the code always converts ports to port number so it works in both cases.

What works is haproxy-ingress.github.io/auth-url: svc://bdb-authentication:authentication/api/v2/auth

So an alternate (quick) solution is to update the doc and specify that the port should match the targetPort value in the service.

**Steps to reproduce the problem**

1. create a deployment that has a port name
2. expose that deployment and make sure targetPort uses the port name
3. set haproxy-ingress.github.io/auth-url to svc url with port number used

**Environment information**

HAProxy Ingress version: `v0.14.0`
